// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: common/common.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "common";

/** Filter operators */
export enum FilterOperator {
  FILTER_OPERATOR_UNSPECIFIED = 0,
  FILTER_OPERATOR_EQUALS = 1,
  FILTER_OPERATOR_NOT_EQUALS = 2,
  FILTER_OPERATOR_GREATER_THAN = 3,
  FILTER_OPERATOR_GREATER_THAN_OR_EQUALS = 4,
  FILTER_OPERATOR_LESS_THAN = 5,
  FILTER_OPERATOR_LESS_THAN_OR_EQUALS = 6,
  FILTER_OPERATOR_IN = 7,
  FILTER_OPERATOR_NOT_IN = 8,
  FILTER_OPERATOR_CONTAINS = 9,
  FILTER_OPERATOR_STARTS_WITH = 10,
  FILTER_OPERATOR_ENDS_WITH = 11,
  FILTER_OPERATOR_IS_NULL = 12,
  FILTER_OPERATOR_IS_NOT_NULL = 13,
  FILTER_OPERATOR_BETWEEN = 14,
  UNRECOGNIZED = -1,
}

/** Standard pagination request for list operations */
export interface PaginationRequest {
  /** Page number (1-indexed, default: 1) */
  page: number;
  /** Number of items per page (default: 20, max: 100) */
  limit: number;
  /** Field to sort by (e.g., "created_at", "nom") */
  sortBy: string;
  /** Sort direction: "asc" or "desc" (default: "desc") */
  sortOrder: string;
}

/** Standard pagination response metadata */
export interface PaginationResponse {
  /** Total number of items across all pages */
  total: number;
  /** Current page number */
  page: number;
  /** Items per page */
  limit: number;
  /** Total number of pages */
  totalPages: number;
  /** Whether there is a next page */
  hasNext: boolean;
  /** Whether there is a previous page */
  hasPrevious: boolean;
}

/** Empty message for requests/responses with no data */
export interface Empty {
}

/** Standard response for delete operations */
export interface DeleteResponse {
  /** Whether the deletion was successful */
  success: boolean;
  /** Optional message (e.g., error details or confirmation) */
  message: string;
}

/** Standard response for bulk operations */
export interface BulkOperationResponse {
  /** Number of items successfully processed */
  successCount: number;
  /** Number of items that failed */
  failureCount: number;
  /** Total items attempted */
  totalCount: number;
  /** Details of failures */
  errors: OperationError[];
}

/** Error details for bulk operations */
export interface OperationError {
  /** Identifier of the failed item */
  itemId: string;
  /** Error code */
  errorCode: string;
  /** Human-readable error message */
  errorMessage: string;
}

/**
 * Represents a monetary amount with currency
 * Uses string to avoid IEEE 754 floating-point precision issues
 */
export interface Money {
  /** Decimal amount as string (e.g., "123.45", "-50.00") */
  amount: string;
  /** ISO 4217 currency code (e.g., "EUR", "USD") */
  currency: string;
}

/** Represents a percentage value */
export interface Percentage {
  /** Percentage as string (e.g., "15.5" for 15.5%) */
  value: string;
}

/** Represents a date range for filtering */
export interface DateRange {
  /** Start date (inclusive) */
  start:
    | Timestamp
    | undefined;
  /** End date (inclusive) */
  end: Timestamp | undefined;
}

/** Represents a period (year-month format) */
export interface Period {
  /** Year (e.g., 2024) */
  year: number;
  /** Month (1-12) */
  month: number;
}

/** Audit metadata attached to operations */
export interface AuditMetadata {
  /** Correlation ID for distributed tracing */
  correlationId: string;
  /** User ID who performed the action */
  userId: string;
  /** User display name */
  userName: string;
  /** IP address of the request origin */
  ipAddress: string;
  /** User agent string */
  userAgent: string;
  /** Timestamp of the operation */
  timestamp:
    | Timestamp
    | undefined;
  /** Source service name */
  sourceService: string;
}

/** Event envelope for domain events */
export interface EventEnvelope {
  /** Unique event ID (UUID) for idempotency */
  eventId: string;
  /** Unix timestamp in milliseconds */
  timestamp: number;
  /** Correlation ID for tracing */
  correlationId: string;
  /** Causation ID (event that caused this event) */
  causationId: string;
  /** Event type (e.g., "ContractSigned", "PaymentReceived") */
  eventType: string;
  /** Event version for schema evolution */
  eventVersion: number;
  /** Source aggregate type */
  aggregateType: string;
  /** Source aggregate ID */
  aggregateId: string;
}

/** Standard address structure */
export interface Address {
  /** Address line 1 (street, number) */
  line1: string;
  /** Address line 2 (apartment, building, etc.) */
  line2: string;
  /** Postal/ZIP code */
  postalCode: string;
  /** City name */
  city: string;
  /** State/Province/Region */
  region: string;
  /** ISO 3166-1 alpha-2 country code (e.g., "FR", "BE") */
  countryCode: string;
  /** Address type (e.g., "billing", "shipping", "legal") */
  type: string;
  /** Whether this is the primary address */
  isPrimary: boolean;
}

/** Phone number with type */
export interface PhoneNumber {
  /** Phone number in E.164 format (e.g., "+33612345678") */
  number: string;
  /** Phone type: "mobile", "landline", "fax" */
  type: string;
  /** Whether this is the primary phone */
  isPrimary: boolean;
}

/** Email address with type */
export interface EmailAddress {
  /** Email address */
  email: string;
  /** Email type: "personal", "professional", "billing" */
  type: string;
  /** Whether this is the primary email */
  isPrimary: boolean;
  /** Whether the email is verified */
  isVerified: boolean;
}

/** Generic filter for list operations */
export interface Filter {
  /** Field name to filter on */
  field: string;
  /** Filter operator */
  operator: FilterOperator;
  /** Value(s) to filter by */
  values: string[];
}

/** File metadata */
export interface FileInfo {
  /** File name */
  name: string;
  /** MIME type (e.g., "application/pdf") */
  mimeType: string;
  /** File size in bytes */
  sizeBytes: number;
  /** File URL or path */
  url: string;
  /** SHA-256 hash for integrity */
  hashSha256: string;
  /** Upload timestamp */
  uploadedAt: Timestamp | undefined;
}

/** Reference to another entity (for loose coupling) */
export interface EntityReference {
  /** Entity type (e.g., "Client", "Contrat", "Facture") */
  entityType: string;
  /** Entity ID */
  entityId: string;
  /** Optional display name for UI */
  displayName: string;
}

/** Generic status with metadata */
export interface StatusInfo {
  /** Status code */
  code: string;
  /** Human-readable status name */
  name: string;
  /** Status description */
  description: string;
  /** Status category for grouping */
  category: string;
  /** Whether this is a terminal/final status */
  isTerminal: boolean;
  /** Display order */
  displayOrder: number;
}

/** Localized string for multi-language support */
export interface LocalizedString {
  /** Default value (fallback) */
  defaultValue: string;
  /** Translations by locale (e.g., "fr-FR", "en-US") */
  translations: { [key: string]: string };
}

export interface LocalizedString_TranslationsEntry {
  key: string;
  value: string;
}

/** Standard request for getting multiple items by IDs */
export interface GetByIdsRequest {
  /** List of IDs to retrieve */
  ids: string[];
}

/** Standard request for getting a single item by ID */
export interface GetByIdRequest {
  /** Item ID */
  id: string;
}

/** Standard request scoped to an organisation */
export interface OrganisationScopedRequest {
  /** Organisation/tenant ID */
  organisationId: string;
}

export const COMMON_PACKAGE_NAME = "common";

function createBasePaginationRequest(): PaginationRequest {
  return { page: 0, limit: 0, sortBy: "", sortOrder: "" };
}

export const PaginationRequest: MessageFns<PaginationRequest> = {
  encode(message: PaginationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== 0) {
      writer.uint32(8).int32(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    if (message.sortBy !== "") {
      writer.uint32(26).string(message.sortBy);
    }
    if (message.sortOrder !== "") {
      writer.uint32(34).string(message.sortOrder);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PaginationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePaginationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sortBy = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sortOrder = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBasePaginationResponse(): PaginationResponse {
  return { total: 0, page: 0, limit: 0, totalPages: 0, hasNext: false, hasPrevious: false };
}

export const PaginationResponse: MessageFns<PaginationResponse> = {
  encode(message: PaginationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.total !== 0) {
      writer.uint32(8).int32(message.total);
    }
    if (message.page !== 0) {
      writer.uint32(16).int32(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(24).int32(message.limit);
    }
    if (message.totalPages !== 0) {
      writer.uint32(32).int32(message.totalPages);
    }
    if (message.hasNext !== false) {
      writer.uint32(40).bool(message.hasNext);
    }
    if (message.hasPrevious !== false) {
      writer.uint32(48).bool(message.hasPrevious);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PaginationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePaginationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.totalPages = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.hasNext = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.hasPrevious = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteResponse(): DeleteResponse {
  return { success: false, message: "" };
}

export const DeleteResponse: MessageFns<DeleteResponse> = {
  encode(message: DeleteResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseBulkOperationResponse(): BulkOperationResponse {
  return { successCount: 0, failureCount: 0, totalCount: 0, errors: [] };
}

export const BulkOperationResponse: MessageFns<BulkOperationResponse> = {
  encode(message: BulkOperationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.successCount !== 0) {
      writer.uint32(8).int32(message.successCount);
    }
    if (message.failureCount !== 0) {
      writer.uint32(16).int32(message.failureCount);
    }
    if (message.totalCount !== 0) {
      writer.uint32(24).int32(message.totalCount);
    }
    for (const v of message.errors) {
      OperationError.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BulkOperationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBulkOperationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.successCount = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.failureCount = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalCount = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.errors.push(OperationError.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseOperationError(): OperationError {
  return { itemId: "", errorCode: "", errorMessage: "" };
}

export const OperationError: MessageFns<OperationError> = {
  encode(message: OperationError, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.itemId !== "") {
      writer.uint32(10).string(message.itemId);
    }
    if (message.errorCode !== "") {
      writer.uint32(18).string(message.errorCode);
    }
    if (message.errorMessage !== "") {
      writer.uint32(26).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OperationError {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOperationError();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.itemId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.errorCode = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMoney(): Money {
  return { amount: "", currency: "" };
}

export const Money: MessageFns<Money> = {
  encode(message: Money, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.amount !== "") {
      writer.uint32(10).string(message.amount);
    }
    if (message.currency !== "") {
      writer.uint32(18).string(message.currency);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Money {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMoney();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBasePercentage(): Percentage {
  return { value: "" };
}

export const Percentage: MessageFns<Percentage> = {
  encode(message: Percentage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== "") {
      writer.uint32(10).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Percentage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePercentage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDateRange(): DateRange {
  return { start: undefined, end: undefined };
}

export const DateRange: MessageFns<DateRange> = {
  encode(message: DateRange, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.start !== undefined) {
      Timestamp.encode(message.start, writer.uint32(10).fork()).join();
    }
    if (message.end !== undefined) {
      Timestamp.encode(message.end, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DateRange {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDateRange();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.start = Timestamp.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.end = Timestamp.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBasePeriod(): Period {
  return { year: 0, month: 0 };
}

export const Period: MessageFns<Period> = {
  encode(message: Period, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.year !== 0) {
      writer.uint32(8).int32(message.year);
    }
    if (message.month !== 0) {
      writer.uint32(16).int32(message.month);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Period {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePeriod();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.year = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.month = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAuditMetadata(): AuditMetadata {
  return {
    correlationId: "",
    userId: "",
    userName: "",
    ipAddress: "",
    userAgent: "",
    timestamp: undefined,
    sourceService: "",
  };
}

export const AuditMetadata: MessageFns<AuditMetadata> = {
  encode(message: AuditMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.correlationId !== "") {
      writer.uint32(10).string(message.correlationId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.userName !== "") {
      writer.uint32(26).string(message.userName);
    }
    if (message.ipAddress !== "") {
      writer.uint32(34).string(message.ipAddress);
    }
    if (message.userAgent !== "") {
      writer.uint32(42).string(message.userAgent);
    }
    if (message.timestamp !== undefined) {
      Timestamp.encode(message.timestamp, writer.uint32(50).fork()).join();
    }
    if (message.sourceService !== "") {
      writer.uint32(58).string(message.sourceService);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuditMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuditMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ipAddress = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.userAgent = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = Timestamp.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.sourceService = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseEventEnvelope(): EventEnvelope {
  return {
    eventId: "",
    timestamp: 0,
    correlationId: "",
    causationId: "",
    eventType: "",
    eventVersion: 0,
    aggregateType: "",
    aggregateId: "",
  };
}

export const EventEnvelope: MessageFns<EventEnvelope> = {
  encode(message: EventEnvelope, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== "") {
      writer.uint32(10).string(message.eventId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).int64(message.timestamp);
    }
    if (message.correlationId !== "") {
      writer.uint32(26).string(message.correlationId);
    }
    if (message.causationId !== "") {
      writer.uint32(34).string(message.causationId);
    }
    if (message.eventType !== "") {
      writer.uint32(42).string(message.eventType);
    }
    if (message.eventVersion !== 0) {
      writer.uint32(48).int32(message.eventVersion);
    }
    if (message.aggregateType !== "") {
      writer.uint32(58).string(message.aggregateType);
    }
    if (message.aggregateId !== "") {
      writer.uint32(66).string(message.aggregateId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventEnvelope {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventEnvelope();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.causationId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.eventType = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.eventVersion = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.aggregateType = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.aggregateId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAddress(): Address {
  return { line1: "", line2: "", postalCode: "", city: "", region: "", countryCode: "", type: "", isPrimary: false };
}

export const Address: MessageFns<Address> = {
  encode(message: Address, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.line1 !== "") {
      writer.uint32(10).string(message.line1);
    }
    if (message.line2 !== "") {
      writer.uint32(18).string(message.line2);
    }
    if (message.postalCode !== "") {
      writer.uint32(26).string(message.postalCode);
    }
    if (message.city !== "") {
      writer.uint32(34).string(message.city);
    }
    if (message.region !== "") {
      writer.uint32(42).string(message.region);
    }
    if (message.countryCode !== "") {
      writer.uint32(50).string(message.countryCode);
    }
    if (message.type !== "") {
      writer.uint32(58).string(message.type);
    }
    if (message.isPrimary !== false) {
      writer.uint32(64).bool(message.isPrimary);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Address {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.line1 = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.line2 = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.postalCode = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.city = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.region = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.countryCode = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.isPrimary = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBasePhoneNumber(): PhoneNumber {
  return { number: "", type: "", isPrimary: false };
}

export const PhoneNumber: MessageFns<PhoneNumber> = {
  encode(message: PhoneNumber, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.number !== "") {
      writer.uint32(10).string(message.number);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    if (message.isPrimary !== false) {
      writer.uint32(24).bool(message.isPrimary);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PhoneNumber {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePhoneNumber();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.number = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isPrimary = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseEmailAddress(): EmailAddress {
  return { email: "", type: "", isPrimary: false, isVerified: false };
}

export const EmailAddress: MessageFns<EmailAddress> = {
  encode(message: EmailAddress, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    if (message.isPrimary !== false) {
      writer.uint32(24).bool(message.isPrimary);
    }
    if (message.isVerified !== false) {
      writer.uint32(32).bool(message.isVerified);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmailAddress {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailAddress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isPrimary = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isVerified = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseFilter(): Filter {
  return { field: "", operator: 0, values: [] };
}

export const Filter: MessageFns<Filter> = {
  encode(message: Filter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.field !== "") {
      writer.uint32(10).string(message.field);
    }
    if (message.operator !== 0) {
      writer.uint32(16).int32(message.operator);
    }
    for (const v of message.values) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Filter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.field = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.operator = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.values.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseFileInfo(): FileInfo {
  return { name: "", mimeType: "", sizeBytes: 0, url: "", hashSha256: "", uploadedAt: undefined };
}

export const FileInfo: MessageFns<FileInfo> = {
  encode(message: FileInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.mimeType !== "") {
      writer.uint32(18).string(message.mimeType);
    }
    if (message.sizeBytes !== 0) {
      writer.uint32(24).int64(message.sizeBytes);
    }
    if (message.url !== "") {
      writer.uint32(34).string(message.url);
    }
    if (message.hashSha256 !== "") {
      writer.uint32(42).string(message.hashSha256);
    }
    if (message.uploadedAt !== undefined) {
      Timestamp.encode(message.uploadedAt, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.mimeType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.sizeBytes = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.hashSha256 = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.uploadedAt = Timestamp.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseEntityReference(): EntityReference {
  return { entityType: "", entityId: "", displayName: "" };
}

export const EntityReference: MessageFns<EntityReference> = {
  encode(message: EntityReference, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entityType !== "") {
      writer.uint32(10).string(message.entityType);
    }
    if (message.entityId !== "") {
      writer.uint32(18).string(message.entityId);
    }
    if (message.displayName !== "") {
      writer.uint32(26).string(message.displayName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EntityReference {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEntityReference();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entityType = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.entityId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseStatusInfo(): StatusInfo {
  return { code: "", name: "", description: "", category: "", isTerminal: false, displayOrder: 0 };
}

export const StatusInfo: MessageFns<StatusInfo> = {
  encode(message: StatusInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.category !== "") {
      writer.uint32(34).string(message.category);
    }
    if (message.isTerminal !== false) {
      writer.uint32(40).bool(message.isTerminal);
    }
    if (message.displayOrder !== 0) {
      writer.uint32(48).int32(message.displayOrder);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StatusInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatusInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.category = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isTerminal = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.displayOrder = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseLocalizedString(): LocalizedString {
  return { defaultValue: "", translations: {} };
}

export const LocalizedString: MessageFns<LocalizedString> = {
  encode(message: LocalizedString, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.defaultValue !== "") {
      writer.uint32(10).string(message.defaultValue);
    }
    globalThis.Object.entries(message.translations).forEach(([key, value]: [string, string]) => {
      LocalizedString_TranslationsEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LocalizedString {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocalizedString();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.defaultValue = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = LocalizedString_TranslationsEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.translations[entry2.key] = entry2.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseLocalizedString_TranslationsEntry(): LocalizedString_TranslationsEntry {
  return { key: "", value: "" };
}

export const LocalizedString_TranslationsEntry: MessageFns<LocalizedString_TranslationsEntry> = {
  encode(message: LocalizedString_TranslationsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LocalizedString_TranslationsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocalizedString_TranslationsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetByIdsRequest(): GetByIdsRequest {
  return { ids: [] };
}

export const GetByIdsRequest: MessageFns<GetByIdsRequest> = {
  encode(message: GetByIdsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.ids) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetByIdsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetByIdsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetByIdRequest(): GetByIdRequest {
  return { id: "" };
}

export const GetByIdRequest: MessageFns<GetByIdRequest> = {
  encode(message: GetByIdRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetByIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetByIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseOrganisationScopedRequest(): OrganisationScopedRequest {
  return { organisationId: "" };
}

export const OrganisationScopedRequest: MessageFns<OrganisationScopedRequest> = {
  encode(message: OrganisationScopedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.organisationId !== "") {
      writer.uint32(10).string(message.organisationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrganisationScopedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrganisationScopedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
