import type {
  ProvisioningLifecycle,
  GetProvisioningStatsResponse,
} from "@proto/telecom/telecom";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

function daysFromNow(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString();
}

// ---------------------------------------------------------------------------
// Mock Lifecycles
// ---------------------------------------------------------------------------

export const MOCK_LIFECYCLES: ProvisioningLifecycle[] = [
  {
    id: "prov-001",
    organisationId: "org-mock-001",
    contratId: "CTR-2026-0142",
    clientId: "CLI-DUPONT",
    commercialId: "COM-MARTIN",
    dateSignature: daysAgo(3),
    dateFinRetractation: daysFromNow(11),
    abonnementStatus: "PENDING",
    provisioningState: "EN_ATTENTE_RETRACTATION",
    montantAbonnement: 29.99,
    devise: "EUR",
    sepaMandateId: "",
    gocardlessSubscriptionId: "",
    compensationDone: false,
    lastError: "",
    metadata: JSON.stringify({
      contratSigneAt: daysAgo(3),
    }),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: "prov-002",
    organisationId: "org-mock-001",
    contratId: "CTR-2026-0138",
    clientId: "CLI-BERNARD",
    commercialId: "COM-PETIT",
    dateSignature: daysAgo(18),
    dateFinRetractation: daysAgo(4),
    abonnementStatus: "ACTIVE",
    provisioningState: "ACTIVE",
    montantAbonnement: 49.99,
    devise: "EUR",
    sepaMandateId: "MD000A7B2C3D4",
    gocardlessSubscriptionId: "SB000E5F6G7H8",
    compensationDone: true,
    lastError: "",
    metadata: JSON.stringify({
      contratSigneAt: daysAgo(18),
      compensationAt: daysAgo(14),
      finRetractationAt: daysAgo(4),
      simExpedieeAt: daysAgo(4),
      simTrackingNumber: "8R00234567891",
      simCarrier: "Colissimo",
      simLivreeAt: daysAgo(2),
      premiereConnexionAt: daysAgo(2),
      activatedAt: daysAgo(2),
      premierPrelevementAt: daysAgo(1),
      lastPaymentAt: daysAgo(1),
    }),
    createdAt: daysAgo(18),
    updatedAt: daysAgo(1),
  },
  {
    id: "prov-003",
    organisationId: "org-mock-001",
    contratId: "CTR-2026-0145",
    clientId: "CLI-MOREAU",
    commercialId: "COM-MARTIN",
    dateSignature: daysAgo(10),
    dateFinRetractation: daysFromNow(4),
    abonnementStatus: "PENDING",
    provisioningState: "DELAI_RETRACTATION_ECOULE",
    montantAbonnement: 39.99,
    devise: "EUR",
    sepaMandateId: "MD000X1Y2Z3A4",
    gocardlessSubscriptionId: "",
    compensationDone: false,
    lastError: "",
    metadata: JSON.stringify({
      contratSigneAt: daysAgo(10),
      finRetractationAt: daysAgo(0),
    }),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },
  {
    id: "prov-004",
    organisationId: "org-mock-001",
    contratId: "CTR-2026-0130",
    clientId: "CLI-LAURENT",
    commercialId: "COM-DURAND",
    dateSignature: daysAgo(25),
    dateFinRetractation: daysAgo(11),
    abonnementStatus: "ACTIVE",
    provisioningState: "EN_COURS",
    montantAbonnement: 59.99,
    devise: "EUR",
    sepaMandateId: "MD000P9Q8R7S6",
    gocardlessSubscriptionId: "SB000T5U4V3W2",
    compensationDone: true,
    lastError: "",
    metadata: JSON.stringify({
      contratSigneAt: daysAgo(25),
      compensationAt: daysAgo(18),
      finRetractationAt: daysAgo(11),
      simExpedieeAt: daysAgo(11),
      simTrackingNumber: "6A01987654321",
      simCarrier: "Colissimo",
    }),
    createdAt: daysAgo(25),
    updatedAt: daysAgo(3),
  },
  {
    id: "prov-005",
    organisationId: "org-mock-001",
    contratId: "CTR-2026-0127",
    clientId: "CLI-GARCIA",
    commercialId: "COM-PETIT",
    dateSignature: daysAgo(30),
    dateFinRetractation: daysAgo(16),
    abonnementStatus: "ERROR",
    provisioningState: "ERREUR_TECHNIQUE",
    montantAbonnement: 34.99,
    devise: "EUR",
    sepaMandateId: "MD000K1L2M3N4",
    gocardlessSubscriptionId: "",
    compensationDone: false,
    lastError: "Transatel API timeout: activation request failed after 3 retries. Code: ETIMEOUT",
    metadata: JSON.stringify({
      contratSigneAt: daysAgo(30),
      compensationAt: daysAgo(22),
      finRetractationAt: daysAgo(16),
      simExpedieeAt: daysAgo(16),
      simTrackingNumber: "CK00879241952",
      simCarrier: "Chronopost",
      simLivreeAt: daysAgo(14),
      lastRetryAt: daysAgo(1),
      retryCount: 3,
    }),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: "prov-006",
    organisationId: "org-mock-001",
    contratId: "CTR-2026-0150",
    clientId: "CLI-THOMAS",
    commercialId: "COM-MARTIN",
    dateSignature: daysAgo(1),
    dateFinRetractation: daysFromNow(13),
    abonnementStatus: "PENDING",
    provisioningState: "EN_ATTENTE_RETRACTATION",
    montantAbonnement: 24.99,
    devise: "EUR",
    sepaMandateId: "",
    gocardlessSubscriptionId: "",
    compensationDone: false,
    lastError: "",
    metadata: JSON.stringify({
      contratSigneAt: daysAgo(1),
    }),
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
  },
  {
    id: "prov-007",
    organisationId: "org-mock-001",
    contratId: "CTR-2026-0120",
    clientId: "CLI-ROBERT",
    commercialId: "COM-DURAND",
    dateSignature: daysAgo(45),
    dateFinRetractation: daysAgo(31),
    abonnementStatus: "ACTIVE",
    provisioningState: "ACTIVE",
    montantAbonnement: 44.99,
    devise: "EUR",
    sepaMandateId: "MD000F1G2H3J4",
    gocardlessSubscriptionId: "SB000K5L6M7N8",
    compensationDone: true,
    lastError: "",
    metadata: JSON.stringify({
      contratSigneAt: daysAgo(45),
      compensationAt: daysAgo(38),
      finRetractationAt: daysAgo(31),
      simExpedieeAt: daysAgo(31),
      simTrackingNumber: "8D00432154789",
      simCarrier: "Colissimo",
      simLivreeAt: daysAgo(29),
      premiereConnexionAt: daysAgo(29),
      activatedAt: daysAgo(29),
      premierPrelevementAt: daysAgo(28),
      lastPaymentAt: daysAgo(5),
    }),
    createdAt: daysAgo(45),
    updatedAt: daysAgo(5),
  },
  {
    id: "prov-008",
    organisationId: "org-mock-001",
    contratId: "CTR-2026-0135",
    clientId: "CLI-RICHARD",
    commercialId: "COM-PETIT",
    dateSignature: daysAgo(20),
    dateFinRetractation: daysAgo(6),
    abonnementStatus: "ACTIVE",
    provisioningState: "EN_COURS",
    montantAbonnement: 54.99,
    devise: "EUR",
    sepaMandateId: "MD000W1X2Y3Z4",
    gocardlessSubscriptionId: "SB000A5B6C7D8",
    compensationDone: true,
    lastError: "",
    metadata: JSON.stringify({
      contratSigneAt: daysAgo(20),
      compensationAt: daysAgo(14),
      finRetractationAt: daysAgo(6),
      simExpedieeAt: daysAgo(6),
      simTrackingNumber: "7Q00556677889",
      simCarrier: "Colissimo",
    }),
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
  },
  {
    id: "prov-009",
    organisationId: "org-mock-001",
    contratId: "CTR-2026-0148",
    clientId: "CLI-SIMON",
    commercialId: "COM-MARTIN",
    dateSignature: daysAgo(5),
    dateFinRetractation: daysFromNow(9),
    abonnementStatus: "PENDING",
    provisioningState: "EN_ATTENTE_RETRACTATION",
    montantAbonnement: 19.99,
    devise: "EUR",
    sepaMandateId: "",
    gocardlessSubscriptionId: "",
    compensationDone: false,
    lastError: "",
    metadata: JSON.stringify({
      contratSigneAt: daysAgo(5),
    }),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
  },
  {
    id: "prov-010",
    organisationId: "org-mock-001",
    contratId: "CTR-2026-0115",
    clientId: "CLI-LEFEVRE",
    commercialId: "COM-DURAND",
    dateSignature: daysAgo(60),
    dateFinRetractation: daysAgo(46),
    abonnementStatus: "ACTIVE",
    provisioningState: "ACTIVE",
    montantAbonnement: 69.99,
    devise: "EUR",
    sepaMandateId: "MD000R1S2T3U4",
    gocardlessSubscriptionId: "SB000V5W6X7Y8",
    compensationDone: true,
    lastError: "",
    metadata: JSON.stringify({
      contratSigneAt: daysAgo(60),
      compensationAt: daysAgo(52),
      finRetractationAt: daysAgo(46),
      simExpedieeAt: daysAgo(46),
      simTrackingNumber: "8R00112233445",
      simCarrier: "Colissimo",
      simLivreeAt: daysAgo(44),
      premiereConnexionAt: daysAgo(44),
      activatedAt: daysAgo(44),
      premierPrelevementAt: daysAgo(43),
      lastPaymentAt: daysAgo(2),
    }),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(2),
  },
];

// ---------------------------------------------------------------------------
// Mock Stats (coherent with lifecycles above)
// ---------------------------------------------------------------------------

export const MOCK_STATS: GetProvisioningStatsResponse = {
  total: 10,
  enAttente: 3,   // prov-001, 006, 009
  delaiEcoule: 1, // prov-003
  enCours: 2,     // prov-004, 008
  active: 3,      // prov-002, 007, 010
  erreur: 1,      // prov-005
  suspendu: 0,
  resilie: 0,
};
