export enum CspNeoliane {
  SALARIE_59_ANS_OU_MOINS = 'SALARIE_59_ANS_OU_MOINS',
  FRONTALIER = 'FRONTALIER',
  FONCTIONNAIRE = 'FONCTIONNAIRE',
  TNS_INDEPENDANT = 'TNS_INDEPENDANT',
  PROFESSION_LIBERALE = 'PROFESSION_LIBERALE',
  CHEF_ENTREPRISE = 'CHEF_ENTREPRISE',
  RETRAITE = 'RETRAITE',
  ETUDIANT = 'ETUDIANT',
  AUTRE = 'AUTRE',
}
