export enum Profession {
  AGRICULTEUR_EXPLOITANT = 'AGRICULTEUR_EXPLOITANT',
  ARTISAN_COMMERCANT_CHEF_ENTREPRISE = 'ARTISAN_COMMERCANT_CHEF_ENTREPRISE',
  CADRE_PROFESSION_INTELLECTUELLE = 'CADRE_PROFESSION_INTELLECTUELLE',
  EMPLOYE = 'EMPLOYE',
  OUVRIER = 'OUVRIER',
  RETRAITE = 'RETRAITE',
  SANS_ACTIVITE_DEMANDEUR_EMPLOI = 'SANS_ACTIVITE_DEMANDEUR_EMPLOI',
  ETUDIANT = 'ETUDIANT',
}
