export enum RegimeSocial {
  SALARIE = 'SALARIE',
  TNS = 'TNS',
  EXPLOITANT_AGRICOLE = 'EXPLOITANT_AGRICOLE',
  RETRAITE_SALARIE = 'RETRAITE_SALARIE',
  FONCTIONNAIRE = 'FONCTIONNAIRE',
  ETUDIANT = 'ETUDIANT',
  SANS_EMPLOI = 'SANS_EMPLOI',
  ALSACE_MOSELLE = 'ALSACE_MOSELLE',
}
