services:
  crm-frontend:
    build:
      context: ../..
      dockerfile: frontend/Dockerfile
      target: production
      args:
        BUILD_ENV: staging
    container_name: staging-crm-frontend
    ports:
      - "3100:3100"
    env_file:
      - ../../frontend/.env.staging
    environment:
      PORT: 3100
    depends_on:
      postgres-main:
        condition: service_healthy
      nats:
        condition: service_started
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3100/api/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
