// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: commission/commission-crud.proto

/* eslint-disable */
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import {
  BaremeListResponse,
  BaremeResponse,
  CommissionListResponse,
  CommissionResponse,
  CreateBaremeRequest,
  CreateCommissionRequest,
  CreatePalierRequest,
  CreateStatutRequest,
  DeleteResponse,
  GetBaremeApplicableRequest,
  GetBaremesRequest,
  GetByApporteurRequest,
  GetByBaremeRequest,
  GetByIdRequest,
  GetByPeriodeRequest,
  GetCommissionsRequest,
  GetStatutByCodeRequest,
  GetStatutsRequest,
  PalierListResponse,
  PalierResponse,
  StatutListResponse,
  StatutResponse,
  UpdateBaremeRequest,
  UpdateCommissionRequest,
  UpdatePalierRequest,
  UpdateStatutRequest,
} from "./commission";

export const protobufPackage = "commission";

export type CommissionCrudServiceService = typeof CommissionCrudServiceService;
export const CommissionCrudServiceService = {
  createCommission: {
    path: "/commission.CommissionCrudService/CreateCommission",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateCommissionRequest): Buffer =>
      Buffer.from(CreateCommissionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateCommissionRequest => CreateCommissionRequest.decode(value),
    responseSerialize: (value: CommissionResponse): Buffer => Buffer.from(CommissionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CommissionResponse => CommissionResponse.decode(value),
  },
  getCommission: {
    path: "/commission.CommissionCrudService/GetCommission",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetByIdRequest): Buffer => Buffer.from(GetByIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetByIdRequest => GetByIdRequest.decode(value),
    responseSerialize: (value: CommissionResponse): Buffer => Buffer.from(CommissionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CommissionResponse => CommissionResponse.decode(value),
  },
  getCommissions: {
    path: "/commission.CommissionCrudService/GetCommissions",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetCommissionsRequest): Buffer =>
      Buffer.from(GetCommissionsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetCommissionsRequest => GetCommissionsRequest.decode(value),
    responseSerialize: (value: CommissionListResponse): Buffer =>
      Buffer.from(CommissionListResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CommissionListResponse => CommissionListResponse.decode(value),
  },
  getCommissionsByApporteur: {
    path: "/commission.CommissionCrudService/GetCommissionsByApporteur",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetByApporteurRequest): Buffer =>
      Buffer.from(GetByApporteurRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetByApporteurRequest => GetByApporteurRequest.decode(value),
    responseSerialize: (value: CommissionListResponse): Buffer =>
      Buffer.from(CommissionListResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CommissionListResponse => CommissionListResponse.decode(value),
  },
  getCommissionsByPeriode: {
    path: "/commission.CommissionCrudService/GetCommissionsByPeriode",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetByPeriodeRequest): Buffer => Buffer.from(GetByPeriodeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetByPeriodeRequest => GetByPeriodeRequest.decode(value),
    responseSerialize: (value: CommissionListResponse): Buffer =>
      Buffer.from(CommissionListResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CommissionListResponse => CommissionListResponse.decode(value),
  },
  updateCommission: {
    path: "/commission.CommissionCrudService/UpdateCommission",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateCommissionRequest): Buffer =>
      Buffer.from(UpdateCommissionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateCommissionRequest => UpdateCommissionRequest.decode(value),
    responseSerialize: (value: CommissionResponse): Buffer => Buffer.from(CommissionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CommissionResponse => CommissionResponse.decode(value),
  },
  deleteCommission: {
    path: "/commission.CommissionCrudService/DeleteCommission",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetByIdRequest): Buffer => Buffer.from(GetByIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetByIdRequest => GetByIdRequest.decode(value),
    responseSerialize: (value: DeleteResponse): Buffer => Buffer.from(DeleteResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeleteResponse => DeleteResponse.decode(value),
  },
  createBareme: {
    path: "/commission.CommissionCrudService/CreateBareme",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateBaremeRequest): Buffer => Buffer.from(CreateBaremeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateBaremeRequest => CreateBaremeRequest.decode(value),
    responseSerialize: (value: BaremeResponse): Buffer => Buffer.from(BaremeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): BaremeResponse => BaremeResponse.decode(value),
  },
  getBareme: {
    path: "/commission.CommissionCrudService/GetBareme",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetByIdRequest): Buffer => Buffer.from(GetByIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetByIdRequest => GetByIdRequest.decode(value),
    responseSerialize: (value: BaremeResponse): Buffer => Buffer.from(BaremeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): BaremeResponse => BaremeResponse.decode(value),
  },
  getBaremes: {
    path: "/commission.CommissionCrudService/GetBaremes",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetBaremesRequest): Buffer => Buffer.from(GetBaremesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetBaremesRequest => GetBaremesRequest.decode(value),
    responseSerialize: (value: BaremeListResponse): Buffer => Buffer.from(BaremeListResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): BaremeListResponse => BaremeListResponse.decode(value),
  },
  getBaremeApplicable: {
    path: "/commission.CommissionCrudService/GetBaremeApplicable",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetBaremeApplicableRequest): Buffer =>
      Buffer.from(GetBaremeApplicableRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetBaremeApplicableRequest => GetBaremeApplicableRequest.decode(value),
    responseSerialize: (value: BaremeResponse): Buffer => Buffer.from(BaremeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): BaremeResponse => BaremeResponse.decode(value),
  },
  updateBareme: {
    path: "/commission.CommissionCrudService/UpdateBareme",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateBaremeRequest): Buffer => Buffer.from(UpdateBaremeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateBaremeRequest => UpdateBaremeRequest.decode(value),
    responseSerialize: (value: BaremeResponse): Buffer => Buffer.from(BaremeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): BaremeResponse => BaremeResponse.decode(value),
  },
  deleteBareme: {
    path: "/commission.CommissionCrudService/DeleteBareme",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetByIdRequest): Buffer => Buffer.from(GetByIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetByIdRequest => GetByIdRequest.decode(value),
    responseSerialize: (value: DeleteResponse): Buffer => Buffer.from(DeleteResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeleteResponse => DeleteResponse.decode(value),
  },
  createPalier: {
    path: "/commission.CommissionCrudService/CreatePalier",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreatePalierRequest): Buffer => Buffer.from(CreatePalierRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreatePalierRequest => CreatePalierRequest.decode(value),
    responseSerialize: (value: PalierResponse): Buffer => Buffer.from(PalierResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PalierResponse => PalierResponse.decode(value),
  },
  getPalier: {
    path: "/commission.CommissionCrudService/GetPalier",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetByIdRequest): Buffer => Buffer.from(GetByIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetByIdRequest => GetByIdRequest.decode(value),
    responseSerialize: (value: PalierResponse): Buffer => Buffer.from(PalierResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PalierResponse => PalierResponse.decode(value),
  },
  getPaliersByBareme: {
    path: "/commission.CommissionCrudService/GetPaliersByBareme",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetByBaremeRequest): Buffer => Buffer.from(GetByBaremeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetByBaremeRequest => GetByBaremeRequest.decode(value),
    responseSerialize: (value: PalierListResponse): Buffer => Buffer.from(PalierListResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PalierListResponse => PalierListResponse.decode(value),
  },
  updatePalier: {
    path: "/commission.CommissionCrudService/UpdatePalier",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdatePalierRequest): Buffer => Buffer.from(UpdatePalierRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdatePalierRequest => UpdatePalierRequest.decode(value),
    responseSerialize: (value: PalierResponse): Buffer => Buffer.from(PalierResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PalierResponse => PalierResponse.decode(value),
  },
  deletePalier: {
    path: "/commission.CommissionCrudService/DeletePalier",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetByIdRequest): Buffer => Buffer.from(GetByIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetByIdRequest => GetByIdRequest.decode(value),
    responseSerialize: (value: DeleteResponse): Buffer => Buffer.from(DeleteResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeleteResponse => DeleteResponse.decode(value),
  },
  createStatut: {
    path: "/commission.CommissionCrudService/CreateStatut",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateStatutRequest): Buffer => Buffer.from(CreateStatutRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateStatutRequest => CreateStatutRequest.decode(value),
    responseSerialize: (value: StatutResponse): Buffer => Buffer.from(StatutResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): StatutResponse => StatutResponse.decode(value),
  },
  getStatut: {
    path: "/commission.CommissionCrudService/GetStatut",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetByIdRequest): Buffer => Buffer.from(GetByIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetByIdRequest => GetByIdRequest.decode(value),
    responseSerialize: (value: StatutResponse): Buffer => Buffer.from(StatutResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): StatutResponse => StatutResponse.decode(value),
  },
  getStatuts: {
    path: "/commission.CommissionCrudService/GetStatuts",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetStatutsRequest): Buffer => Buffer.from(GetStatutsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetStatutsRequest => GetStatutsRequest.decode(value),
    responseSerialize: (value: StatutListResponse): Buffer => Buffer.from(StatutListResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): StatutListResponse => StatutListResponse.decode(value),
  },
  getStatutByCode: {
    path: "/commission.CommissionCrudService/GetStatutByCode",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetStatutByCodeRequest): Buffer =>
      Buffer.from(GetStatutByCodeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetStatutByCodeRequest => GetStatutByCodeRequest.decode(value),
    responseSerialize: (value: StatutResponse): Buffer => Buffer.from(StatutResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): StatutResponse => StatutResponse.decode(value),
  },
  updateStatut: {
    path: "/commission.CommissionCrudService/UpdateStatut",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateStatutRequest): Buffer => Buffer.from(UpdateStatutRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateStatutRequest => UpdateStatutRequest.decode(value),
    responseSerialize: (value: StatutResponse): Buffer => Buffer.from(StatutResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): StatutResponse => StatutResponse.decode(value),
  },
  deleteStatut: {
    path: "/commission.CommissionCrudService/DeleteStatut",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetByIdRequest): Buffer => Buffer.from(GetByIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetByIdRequest => GetByIdRequest.decode(value),
    responseSerialize: (value: DeleteResponse): Buffer => Buffer.from(DeleteResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeleteResponse => DeleteResponse.decode(value),
  },
} as const;

export interface CommissionCrudServiceServer extends UntypedServiceImplementation {
  createCommission: handleUnaryCall<CreateCommissionRequest, CommissionResponse>;
  getCommission: handleUnaryCall<GetByIdRequest, CommissionResponse>;
  getCommissions: handleUnaryCall<GetCommissionsRequest, CommissionListResponse>;
  getCommissionsByApporteur: handleUnaryCall<GetByApporteurRequest, CommissionListResponse>;
  getCommissionsByPeriode: handleUnaryCall<GetByPeriodeRequest, CommissionListResponse>;
  updateCommission: handleUnaryCall<UpdateCommissionRequest, CommissionResponse>;
  deleteCommission: handleUnaryCall<GetByIdRequest, DeleteResponse>;
  createBareme: handleUnaryCall<CreateBaremeRequest, BaremeResponse>;
  getBareme: handleUnaryCall<GetByIdRequest, BaremeResponse>;
  getBaremes: handleUnaryCall<GetBaremesRequest, BaremeListResponse>;
  getBaremeApplicable: handleUnaryCall<GetBaremeApplicableRequest, BaremeResponse>;
  updateBareme: handleUnaryCall<UpdateBaremeRequest, BaremeResponse>;
  deleteBareme: handleUnaryCall<GetByIdRequest, DeleteResponse>;
  createPalier: handleUnaryCall<CreatePalierRequest, PalierResponse>;
  getPalier: handleUnaryCall<GetByIdRequest, PalierResponse>;
  getPaliersByBareme: handleUnaryCall<GetByBaremeRequest, PalierListResponse>;
  updatePalier: handleUnaryCall<UpdatePalierRequest, PalierResponse>;
  deletePalier: handleUnaryCall<GetByIdRequest, DeleteResponse>;
  createStatut: handleUnaryCall<CreateStatutRequest, StatutResponse>;
  getStatut: handleUnaryCall<GetByIdRequest, StatutResponse>;
  getStatuts: handleUnaryCall<GetStatutsRequest, StatutListResponse>;
  getStatutByCode: handleUnaryCall<GetStatutByCodeRequest, StatutResponse>;
  updateStatut: handleUnaryCall<UpdateStatutRequest, StatutResponse>;
  deleteStatut: handleUnaryCall<GetByIdRequest, DeleteResponse>;
}
