// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               unknown
// source: notifications/notifications.proto

/* eslint-disable */

export enum NotificationType {
  NOTIFICATION_TYPE_UNSPECIFIED = 0,
  NOTIFICATION_TYPE_CONTRAT_EXPIRE = 1,
  NOTIFICATION_TYPE_CONTRAT_BIENTOT_EXPIRE = 2,
  NOTIFICATION_TYPE_IMPAYE = 3,
  NOTIFICATION_TYPE_NOUVEAU_CLIENT = 4,
  NOTIFICATION_TYPE_NOUVEAU_CONTRAT = 5,
  NOTIFICATION_TYPE_TACHE_ASSIGNEE = 6,
  NOTIFICATION_TYPE_RAPPEL = 7,
  NOTIFICATION_TYPE_ALERTE = 8,
  NOTIFICATION_TYPE_INFO = 9,
  NOTIFICATION_TYPE_SYSTEME = 10,
  UNRECOGNIZED = -1,
}

export interface EmptyRequest {
}

export interface DeleteResponse {
  success: boolean;
  message: string;
}

export interface OperationResponse {
  success: boolean;
  message: string;
  affectedCount: number;
}

export interface Notification {
  id: string;
  organisationId: string;
  utilisateurId: string;
  type: NotificationType;
  titre: string;
  message: string;
  lu: boolean;
  metadata: { [key: string]: string };
  lienUrl?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface Notification_MetadataEntry {
  key: string;
  value: string;
}

export interface CreateNotificationRequest {
  organisationId: string;
  utilisateurId: string;
  type: NotificationType;
  titre: string;
  message: string;
  metadata: { [key: string]: string };
  lienUrl?: string | undefined;
  broadcastWebsocket: boolean;
}

export interface CreateNotificationRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface GetNotificationRequest {
  id: string;
}

export interface GetNotificationsRequest {
  organisationId: string;
  limit?: number | undefined;
  offset?: number | undefined;
  typeFilter?: NotificationType | undefined;
  unreadOnly?: boolean | undefined;
}

export interface GetNotificationsByUserRequest {
  utilisateurId: string;
  limit?: number | undefined;
  offset?: number | undefined;
}

export interface UpdateNotificationRequest {
  id: string;
  titre?: string | undefined;
  message?: string | undefined;
  lu?: boolean | undefined;
  metadata: { [key: string]: string };
  lienUrl?: string | undefined;
}

export interface UpdateNotificationRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface DeleteNotificationRequest {
  id: string;
}

export interface NotificationResponse {
  notification?: Notification | undefined;
}

export interface NotificationListResponse {
  notifications: Notification[];
  total: number;
}

export interface MarkAsReadRequest {
  id: string;
}

export interface MarkAllAsReadRequest {
  utilisateurId: string;
}

export interface GetUnreadCountRequest {
  utilisateurId: string;
}

export interface UnreadCountResponse {
  total: number;
  unread: number;
}

export interface DeleteAllByUserRequest {
  utilisateurId: string;
}

export interface DeleteOlderThanRequest {
  date: string;
}

export interface NotifyNewClientRequest {
  organisationId: string;
  utilisateurId: string;
  clientId: string;
  clientNom: string;
}

export interface NotifyNewContratRequest {
  organisationId: string;
  utilisateurId: string;
  contratId: string;
  contratNumero: string;
  clientNom: string;
}

export interface NotifyContratExpiringRequest {
  organisationId: string;
  utilisateurId: string;
  contratId: string;
  contratNumero: string;
  dateExpiration: string;
  joursRestants: number;
}

export interface NotifyImpayeRequest {
  organisationId: string;
  utilisateurId: string;
  factureId: string;
  factureNumero: string;
  clientNom: string;
  montant: string;
}

export interface NotifyTacheRequest {
  organisationId: string;
  utilisateurId: string;
  tacheId: string;
  tacheTitre: string;
  assignePar: string;
}

export interface NotifyRappelRequest {
  organisationId: string;
  utilisateurId: string;
  titre: string;
  message: string;
  lienUrl?: string | undefined;
}

export interface NotifyAlerteRequest {
  organisationId: string;
  utilisateurId: string;
  titre: string;
  message: string;
  niveau: string;
}

export interface NotifyInfoRequest {
  organisationId: string;
  utilisateurId: string;
  titre: string;
  message: string;
}

export interface NotifyOrganisationRequest {
  organisationId: string;
  utilisateurIds: string[];
  type: NotificationType;
  titre: string;
  message: string;
  metadata: { [key: string]: string };
}

export interface NotifyOrganisationRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface ConnectedUsersResponse {
  count: number;
}

export interface IsUserConnectedRequest {
  utilisateurId: string;
}

export interface IsUserConnectedResponse {
  connected: boolean;
}
