// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: common/mcp.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

/** Message vide pour les requêtes sans paramètres */
export interface Empty {
}

/** Définition d'un tool MCP */
export interface ToolDefinition {
  name: string;
  description: string;
  /** JSON string du schéma */
  inputSchema: string;
}

/** Réponse contenant la liste des tools */
export interface ToolsResponse {
  tools: ToolDefinition[];
}

/** Requête pour exécuter un tool */
export interface ExecuteRequest {
  /** Nom du tool (ex: "search_clients") */
  toolName: string;
  /** Paramètres JSON (ex: {"organisationId": "abc", "limit": 10}) */
  input: string;
  /** ID unique de la requête pour traçabilité */
  requestId: string;
  /** ID du tenant (pour sécurité) */
  organisationId: string;
}

/** Réponse après exécution d'un tool */
export interface ExecuteResponse {
  /** Résultat JSON en cas de succès */
  result: string;
  /** Message d'erreur si échec */
  error: string;
  /** Indicateur de succès */
  success: boolean;
}

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

function createBaseToolDefinition(): ToolDefinition {
  return { name: "", description: "", inputSchema: "" };
}

export const ToolDefinition: MessageFns<ToolDefinition> = {
  encode(message: ToolDefinition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.inputSchema !== "") {
      writer.uint32(26).string(message.inputSchema);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolDefinition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolDefinition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.inputSchema = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolDefinition {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      inputSchema: isSet(object.inputSchema)
        ? globalThis.String(object.inputSchema)
        : isSet(object.input_schema)
        ? globalThis.String(object.input_schema)
        : "",
    };
  },

  toJSON(message: ToolDefinition): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.inputSchema !== "") {
      obj.inputSchema = message.inputSchema;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolDefinition>, I>>(base?: I): ToolDefinition {
    return ToolDefinition.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolDefinition>, I>>(object: I): ToolDefinition {
    const message = createBaseToolDefinition();
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.inputSchema = object.inputSchema ?? "";
    return message;
  },
};

function createBaseToolsResponse(): ToolsResponse {
  return { tools: [] };
}

export const ToolsResponse: MessageFns<ToolsResponse> = {
  encode(message: ToolsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tools) {
      ToolDefinition.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tools.push(ToolDefinition.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolsResponse {
    return {
      tools: globalThis.Array.isArray(object?.tools) ? object.tools.map((e: any) => ToolDefinition.fromJSON(e)) : [],
    };
  },

  toJSON(message: ToolsResponse): unknown {
    const obj: any = {};
    if (message.tools?.length) {
      obj.tools = message.tools.map((e) => ToolDefinition.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolsResponse>, I>>(base?: I): ToolsResponse {
    return ToolsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolsResponse>, I>>(object: I): ToolsResponse {
    const message = createBaseToolsResponse();
    message.tools = object.tools?.map((e) => ToolDefinition.fromPartial(e)) || [];
    return message;
  },
};

function createBaseExecuteRequest(): ExecuteRequest {
  return { toolName: "", input: "", requestId: "", organisationId: "" };
}

export const ExecuteRequest: MessageFns<ExecuteRequest> = {
  encode(message: ExecuteRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.toolName !== "") {
      writer.uint32(10).string(message.toolName);
    }
    if (message.input !== "") {
      writer.uint32(18).string(message.input);
    }
    if (message.requestId !== "") {
      writer.uint32(26).string(message.requestId);
    }
    if (message.organisationId !== "") {
      writer.uint32(34).string(message.organisationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecuteRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecuteRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.toolName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.input = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExecuteRequest {
    return {
      toolName: isSet(object.toolName)
        ? globalThis.String(object.toolName)
        : isSet(object.tool_name)
        ? globalThis.String(object.tool_name)
        : "",
      input: isSet(object.input) ? globalThis.String(object.input) : "",
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
    };
  },

  toJSON(message: ExecuteRequest): unknown {
    const obj: any = {};
    if (message.toolName !== "") {
      obj.toolName = message.toolName;
    }
    if (message.input !== "") {
      obj.input = message.input;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExecuteRequest>, I>>(base?: I): ExecuteRequest {
    return ExecuteRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecuteRequest>, I>>(object: I): ExecuteRequest {
    const message = createBaseExecuteRequest();
    message.toolName = object.toolName ?? "";
    message.input = object.input ?? "";
    message.requestId = object.requestId ?? "";
    message.organisationId = object.organisationId ?? "";
    return message;
  },
};

function createBaseExecuteResponse(): ExecuteResponse {
  return { result: "", error: "", success: false };
}

export const ExecuteResponse: MessageFns<ExecuteResponse> = {
  encode(message: ExecuteResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.result !== "") {
      writer.uint32(10).string(message.result);
    }
    if (message.error !== "") {
      writer.uint32(18).string(message.error);
    }
    if (message.success !== false) {
      writer.uint32(24).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecuteResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecuteResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.result = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExecuteResponse {
    return {
      result: isSet(object.result) ? globalThis.String(object.result) : "",
      error: isSet(object.error) ? globalThis.String(object.error) : "",
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
    };
  },

  toJSON(message: ExecuteResponse): unknown {
    const obj: any = {};
    if (message.result !== "") {
      obj.result = message.result;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExecuteResponse>, I>>(base?: I): ExecuteResponse {
    return ExecuteResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecuteResponse>, I>>(object: I): ExecuteResponse {
    const message = createBaseExecuteResponse();
    message.result = object.result ?? "";
    message.error = object.error ?? "";
    message.success = object.success ?? false;
    return message;
  },
};

/** Service MCP exposant les tools pour l'IA */
export type MCPServiceService = typeof MCPServiceService;
export const MCPServiceService = {
  /** Liste tous les tools disponibles */
  listTools: {
    path: "/mcp.MCPService/ListTools",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer): Empty => Empty.decode(value),
    responseSerialize: (value: ToolsResponse): Buffer => Buffer.from(ToolsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ToolsResponse => ToolsResponse.decode(value),
  },
  /** Exécute un tool spécifique */
  executeTool: {
    path: "/mcp.MCPService/ExecuteTool",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ExecuteRequest): Buffer => Buffer.from(ExecuteRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ExecuteRequest => ExecuteRequest.decode(value),
    responseSerialize: (value: ExecuteResponse): Buffer => Buffer.from(ExecuteResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ExecuteResponse => ExecuteResponse.decode(value),
  },
} as const;

export interface MCPServiceServer extends UntypedServiceImplementation {
  /** Liste tous les tools disponibles */
  listTools: handleUnaryCall<Empty, ToolsResponse>;
  /** Exécute un tool spécifique */
  executeTool: handleUnaryCall<ExecuteRequest, ExecuteResponse>;
}

export interface MCPServiceClient extends Client {
  /** Liste tous les tools disponibles */
  listTools(request: Empty, callback: (error: ServiceError | null, response: ToolsResponse) => void): ClientUnaryCall;
  listTools(
    request: Empty,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ToolsResponse) => void,
  ): ClientUnaryCall;
  listTools(
    request: Empty,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ToolsResponse) => void,
  ): ClientUnaryCall;
  /** Exécute un tool spécifique */
  executeTool(
    request: ExecuteRequest,
    callback: (error: ServiceError | null, response: ExecuteResponse) => void,
  ): ClientUnaryCall;
  executeTool(
    request: ExecuteRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ExecuteResponse) => void,
  ): ClientUnaryCall;
  executeTool(
    request: ExecuteRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ExecuteResponse) => void,
  ): ClientUnaryCall;
}

export const MCPServiceClient = makeGenericClientConstructor(MCPServiceService, "mcp.MCPService") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): MCPServiceClient;
  service: typeof MCPServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
