// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               unknown
// source: common/mcp.proto

/* eslint-disable */

/** Message vide pour les requêtes sans paramètres */
export interface Empty {
}

/** Définition d'un tool MCP */
export interface ToolDefinition {
  name: string;
  description: string;
  /** JSON string du schéma */
  inputSchema: string;
}

/** Réponse contenant la liste des tools */
export interface ToolsResponse {
  tools: ToolDefinition[];
}

/** Requête pour exécuter un tool */
export interface ExecuteRequest {
  /** Nom du tool (ex: "search_clients") */
  toolName: string;
  /** Paramètres JSON (ex: {"organisationId": "abc", "limit": 10}) */
  input: string;
  /** ID unique de la requête pour traçabilité */
  requestId: string;
  /** ID du tenant (pour sécurité) */
  organisationId: string;
}

/** Réponse après exécution d'un tool */
export interface ExecuteResponse {
  /** Résultat JSON en cas de succès */
  result: string;
  /** Message d'erreur si échec */
  error: string;
  /** Indicateur de succès */
  success: boolean;
}
