"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MAX_EMAIL_ATTACHMENTS = exports.DEFAULT_EMAIL_BATCH_SIZE = exports.ALLOWED_DOCUMENT_TYPES = exports.MAX_FILE_SIZE_BYTES = exports.MAX_FILE_SIZE_MB = exports.DEFAULT_HTTP_TIMEOUT_MS = exports.DEFAULT_GRPC_TIMEOUT_MS = exports.DEFAULT_RETRY_BACKOFF_MULTIPLIER = exports.DEFAULT_RETRY_DELAY_MS = exports.DEFAULT_MAX_RETRY_ATTEMPTS = exports.MAX_COMMISSION_RATE = exports.MIN_COMMISSION_RATE = exports.DEFAULT_COMMISSION_RATE = exports.DEFAULT_CONTRACT_DURATION_MONTHS = exports.DEFAULT_CONTRACT_STATUS = exports.DEFAULT_CLIENT_TYPE = exports.DEFAULT_CLIENT_STATUS = exports.INVOICE_NUMBER_PADDING = exports.DEFAULT_PAYMENT_TERMS_DAYS = exports.DEFAULT_INVOICE_PREFIX = exports.MAX_PAGE_SIZE = exports.DEFAULT_PAGE_SIZE_LARGE = exports.DEFAULT_PAGE_SIZE = exports.DEFAULT_DATETIME_FORMAT = exports.DEFAULT_DATE_FORMAT = exports.CURRENCY_SYMBOL = exports.DEFAULT_CURRENCY = exports.DEFAULT_COUNTRY_CODE = exports.DEFAULT_COUNTRY = exports.TVA_RATE_ZERO = exports.TVA_RATE_SUPER_REDUCED = exports.TVA_RATE_REDUCED = exports.DEFAULT_TVA_RATE = void 0;
exports.DEFAULT_TVA_RATE = 20;
exports.TVA_RATE_REDUCED = 10;
exports.TVA_RATE_SUPER_REDUCED = 5.5;
exports.TVA_RATE_ZERO = 0;
exports.DEFAULT_COUNTRY = 'France';
exports.DEFAULT_COUNTRY_CODE = 'FR';
exports.DEFAULT_CURRENCY = 'EUR';
exports.CURRENCY_SYMBOL = '€';
exports.DEFAULT_DATE_FORMAT = 'YYYY-MM-DD';
exports.DEFAULT_DATETIME_FORMAT = 'YYYY-MM-DD HH:mm:ss';
exports.DEFAULT_PAGE_SIZE = 20;
exports.DEFAULT_PAGE_SIZE_LARGE = 50;
exports.MAX_PAGE_SIZE = 100;
exports.DEFAULT_INVOICE_PREFIX = 'FAC';
exports.DEFAULT_PAYMENT_TERMS_DAYS = 30;
exports.INVOICE_NUMBER_PADDING = 6;
exports.DEFAULT_CLIENT_STATUS = 'ACTIF';
exports.DEFAULT_CLIENT_TYPE = 'PARTICULIER';
exports.DEFAULT_CONTRACT_STATUS = 'BROUILLON';
exports.DEFAULT_CONTRACT_DURATION_MONTHS = 12;
exports.DEFAULT_COMMISSION_RATE = 10;
exports.MIN_COMMISSION_RATE = 0;
exports.MAX_COMMISSION_RATE = 100;
exports.DEFAULT_MAX_RETRY_ATTEMPTS = 3;
exports.DEFAULT_RETRY_DELAY_MS = 1000;
exports.DEFAULT_RETRY_BACKOFF_MULTIPLIER = 2;
exports.DEFAULT_GRPC_TIMEOUT_MS = 5000;
exports.DEFAULT_HTTP_TIMEOUT_MS = 30000;
exports.MAX_FILE_SIZE_MB = 10;
exports.MAX_FILE_SIZE_BYTES = exports.MAX_FILE_SIZE_MB * 1024 * 1024;
exports.ALLOWED_DOCUMENT_TYPES = [
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'image/jpeg',
    'image/png',
];
exports.DEFAULT_EMAIL_BATCH_SIZE = 50;
exports.MAX_EMAIL_ATTACHMENTS = 5;
//# sourceMappingURL=defaults.js.map