// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: events/depanssur_events.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "events";

/** Abonnement created event */
export interface AbonnementCreatedEvent {
  /** Event metadata */
  eventId: string;
  /** Unix timestamp in milliseconds */
  timestamp: number;
  /** Optional, for tracing */
  correlationId: string;
  /** Event data */
  abonnementId: string;
  /** Client ID */
  clientId: string;
  /** Organisation ID (tenant) */
  organisationId: string;
  /** Formule (ESSENTIEL, CONFORT, SERENITE) */
  formule: string;
  /** Status (ACTIF, SUSPENDU, RESILIE) */
  statut: string;
  /** Start date */
  dateDebut:
    | Date
    | undefined;
  /** Creation timestamp */
  createdAt: Date | undefined;
}

/** Abonnement status changed event */
export interface AbonnementStatusChangedEvent {
  /** Event metadata */
  eventId: string;
  /** Unix timestamp in milliseconds */
  timestamp: number;
  /** Optional, for tracing */
  correlationId: string;
  /** Event data */
  abonnementId: string;
  /** Client ID */
  clientId: string;
  /** Organisation ID (tenant) */
  organisationId: string;
  /** Previous status */
  ancienStatut: string;
  /** New status */
  nouveauStatut: string;
  /** Reason for change (optional) */
  motif: string;
  /** Change timestamp */
  changedAt: Date | undefined;
}

/** Abonnement upgraded event */
export interface AbonnementUpgradedEvent {
  /** Event metadata */
  eventId: string;
  /** Unix timestamp in milliseconds */
  timestamp: number;
  /** Optional, for tracing */
  correlationId: string;
  /** Event data */
  abonnementId: string;
  /** Client ID */
  clientId: string;
  /** Organisation ID (tenant) */
  organisationId: string;
  /** Previous formule */
  ancienneFormule: string;
  /** New formule */
  nouvelleFormule: string;
  /** Upgrade timestamp */
  upgradedAt: Date | undefined;
}

/** Abonnement downgraded event */
export interface AbonnementDowngradedEvent {
  /** Event metadata */
  eventId: string;
  /** Unix timestamp in milliseconds */
  timestamp: number;
  /** Optional, for tracing */
  correlationId: string;
  /** Event data */
  abonnementId: string;
  /** Client ID */
  clientId: string;
  /** Organisation ID (tenant) */
  organisationId: string;
  /** Previous formule */
  ancienneFormule: string;
  /** New formule */
  nouvelleFormule: string;
  /** Downgrade timestamp */
  downgradedAt: Date | undefined;
}

/** Dossier created event */
export interface DossierCreatedEvent {
  /** Event metadata */
  eventId: string;
  /** Unix timestamp in milliseconds */
  timestamp: number;
  /** Optional, for tracing */
  correlationId: string;
  /** Event data */
  dossierId: string;
  /** Abonnement ID */
  abonnementId: string;
  /** Client ID */
  clientId: string;
  /** Organisation ID (tenant) */
  organisationId: string;
  /** Type of incident */
  typeSinistre: string;
  /** Declared amount */
  montantDeclare: number;
  /** Incident date */
  dateSinistre:
    | Date
    | undefined;
  /** Creation timestamp */
  createdAt: Date | undefined;
}

/** Dossier status changed event */
export interface DossierStatusChangedEvent {
  /** Event metadata */
  eventId: string;
  /** Unix timestamp in milliseconds */
  timestamp: number;
  /** Optional, for tracing */
  correlationId: string;
  /** Event data */
  dossierId: string;
  /** Abonnement ID */
  abonnementId: string;
  /** Client ID */
  clientId: string;
  /** Organisation ID (tenant) */
  organisationId: string;
  /** Previous status */
  ancienStatut: string;
  /** New status */
  nouveauStatut: string;
  /** Change timestamp */
  changedAt: Date | undefined;
}

/** Dossier decision event */
export interface DossierDecisionEvent {
  /** Event metadata */
  eventId: string;
  /** Unix timestamp in milliseconds */
  timestamp: number;
  /** Optional, for tracing */
  correlationId: string;
  /** Event data */
  dossierId: string;
  /** Abonnement ID */
  abonnementId: string;
  /** Client ID */
  clientId: string;
  /** Organisation ID (tenant) */
  organisationId: string;
  /** Decision (ACCEPTE, REFUSE, ACCEPTE_PARTIEL) */
  decision: string;
  /** Granted amount */
  montantAccorde: number;
  /** Refusal reason (if applicable) */
  motifRefus: string;
  /** Decision timestamp */
  decidedAt: Date | undefined;
}

/** Dossier closed event */
export interface DossierClosedEvent {
  /** Event metadata */
  eventId: string;
  /** Unix timestamp in milliseconds */
  timestamp: number;
  /** Optional, for tracing */
  correlationId: string;
  /** Event data */
  dossierId: string;
  /** Abonnement ID */
  abonnementId: string;
  /** Client ID */
  clientId: string;
  /** Organisation ID (tenant) */
  organisationId: string;
  /** Closure reason */
  motifCloture: string;
  /** Closure timestamp */
  closedAt: Date | undefined;
}

/** Plafond threshold reached event */
export interface PlafondThresholdReachedEvent {
  /** Event metadata */
  eventId: string;
  /** Unix timestamp in milliseconds */
  timestamp: number;
  /** Optional, for tracing */
  correlationId: string;
  /** Event data */
  abonnementId: string;
  /** Client ID */
  clientId: string;
  /** Organisation ID (tenant) */
  organisationId: string;
  /** Annual ceiling */
  plafondAnnuel: number;
  /** Amount used */
  montantUtilise: number;
  /** Percentage used (e.g., 80.0 for 80%) */
  pourcentageUtilise: number;
  /** Threshold reached timestamp */
  reachedAt: Date | undefined;
}

/** Plafond exceeded event */
export interface PlafondExceededEvent {
  /** Event metadata */
  eventId: string;
  /** Unix timestamp in milliseconds */
  timestamp: number;
  /** Optional, for tracing */
  correlationId: string;
  /** Event data */
  abonnementId: string;
  /** Client ID */
  clientId: string;
  /** Organisation ID (tenant) */
  organisationId: string;
  /** Annual ceiling */
  plafondAnnuel: number;
  /** Amount used */
  montantUtilise: number;
  /** Amount exceeded */
  montantDepasse: number;
  /** Exceeded timestamp */
  exceededAt: Date | undefined;
}

function createBaseAbonnementCreatedEvent(): AbonnementCreatedEvent {
  return {
    eventId: "",
    timestamp: 0,
    correlationId: "",
    abonnementId: "",
    clientId: "",
    organisationId: "",
    formule: "",
    statut: "",
    dateDebut: undefined,
    createdAt: undefined,
  };
}

export const AbonnementCreatedEvent: MessageFns<AbonnementCreatedEvent> = {
  encode(message: AbonnementCreatedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== "") {
      writer.uint32(10).string(message.eventId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).int64(message.timestamp);
    }
    if (message.correlationId !== "") {
      writer.uint32(26).string(message.correlationId);
    }
    if (message.abonnementId !== "") {
      writer.uint32(34).string(message.abonnementId);
    }
    if (message.clientId !== "") {
      writer.uint32(42).string(message.clientId);
    }
    if (message.organisationId !== "") {
      writer.uint32(50).string(message.organisationId);
    }
    if (message.formule !== "") {
      writer.uint32(58).string(message.formule);
    }
    if (message.statut !== "") {
      writer.uint32(66).string(message.statut);
    }
    if (message.dateDebut !== undefined) {
      Timestamp.encode(toTimestamp(message.dateDebut), writer.uint32(74).fork()).join();
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AbonnementCreatedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAbonnementCreatedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.abonnementId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.formule = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.statut = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.dateDebut = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AbonnementCreatedEvent {
    return {
      eventId: isSet(object.eventId)
        ? globalThis.String(object.eventId)
        : isSet(object.event_id)
        ? globalThis.String(object.event_id)
        : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      correlationId: isSet(object.correlationId)
        ? globalThis.String(object.correlationId)
        : isSet(object.correlation_id)
        ? globalThis.String(object.correlation_id)
        : "",
      abonnementId: isSet(object.abonnementId)
        ? globalThis.String(object.abonnementId)
        : isSet(object.abonnement_id)
        ? globalThis.String(object.abonnement_id)
        : "",
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      formule: isSet(object.formule) ? globalThis.String(object.formule) : "",
      statut: isSet(object.statut) ? globalThis.String(object.statut) : "",
      dateDebut: isSet(object.dateDebut)
        ? fromJsonTimestamp(object.dateDebut)
        : isSet(object.date_debut)
        ? fromJsonTimestamp(object.date_debut)
        : undefined,
      createdAt: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
        ? fromJsonTimestamp(object.created_at)
        : undefined,
    };
  },

  toJSON(message: AbonnementCreatedEvent): unknown {
    const obj: any = {};
    if (message.eventId !== "") {
      obj.eventId = message.eventId;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.correlationId !== "") {
      obj.correlationId = message.correlationId;
    }
    if (message.abonnementId !== "") {
      obj.abonnementId = message.abonnementId;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.formule !== "") {
      obj.formule = message.formule;
    }
    if (message.statut !== "") {
      obj.statut = message.statut;
    }
    if (message.dateDebut !== undefined) {
      obj.dateDebut = message.dateDebut.toISOString();
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AbonnementCreatedEvent>, I>>(base?: I): AbonnementCreatedEvent {
    return AbonnementCreatedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AbonnementCreatedEvent>, I>>(object: I): AbonnementCreatedEvent {
    const message = createBaseAbonnementCreatedEvent();
    message.eventId = object.eventId ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.correlationId = object.correlationId ?? "";
    message.abonnementId = object.abonnementId ?? "";
    message.clientId = object.clientId ?? "";
    message.organisationId = object.organisationId ?? "";
    message.formule = object.formule ?? "";
    message.statut = object.statut ?? "";
    message.dateDebut = object.dateDebut ?? undefined;
    message.createdAt = object.createdAt ?? undefined;
    return message;
  },
};

function createBaseAbonnementStatusChangedEvent(): AbonnementStatusChangedEvent {
  return {
    eventId: "",
    timestamp: 0,
    correlationId: "",
    abonnementId: "",
    clientId: "",
    organisationId: "",
    ancienStatut: "",
    nouveauStatut: "",
    motif: "",
    changedAt: undefined,
  };
}

export const AbonnementStatusChangedEvent: MessageFns<AbonnementStatusChangedEvent> = {
  encode(message: AbonnementStatusChangedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== "") {
      writer.uint32(10).string(message.eventId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).int64(message.timestamp);
    }
    if (message.correlationId !== "") {
      writer.uint32(26).string(message.correlationId);
    }
    if (message.abonnementId !== "") {
      writer.uint32(34).string(message.abonnementId);
    }
    if (message.clientId !== "") {
      writer.uint32(42).string(message.clientId);
    }
    if (message.organisationId !== "") {
      writer.uint32(50).string(message.organisationId);
    }
    if (message.ancienStatut !== "") {
      writer.uint32(58).string(message.ancienStatut);
    }
    if (message.nouveauStatut !== "") {
      writer.uint32(66).string(message.nouveauStatut);
    }
    if (message.motif !== "") {
      writer.uint32(74).string(message.motif);
    }
    if (message.changedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.changedAt), writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AbonnementStatusChangedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAbonnementStatusChangedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.abonnementId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.ancienStatut = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.nouveauStatut = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.motif = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.changedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AbonnementStatusChangedEvent {
    return {
      eventId: isSet(object.eventId)
        ? globalThis.String(object.eventId)
        : isSet(object.event_id)
        ? globalThis.String(object.event_id)
        : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      correlationId: isSet(object.correlationId)
        ? globalThis.String(object.correlationId)
        : isSet(object.correlation_id)
        ? globalThis.String(object.correlation_id)
        : "",
      abonnementId: isSet(object.abonnementId)
        ? globalThis.String(object.abonnementId)
        : isSet(object.abonnement_id)
        ? globalThis.String(object.abonnement_id)
        : "",
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      ancienStatut: isSet(object.ancienStatut)
        ? globalThis.String(object.ancienStatut)
        : isSet(object.ancien_statut)
        ? globalThis.String(object.ancien_statut)
        : "",
      nouveauStatut: isSet(object.nouveauStatut)
        ? globalThis.String(object.nouveauStatut)
        : isSet(object.nouveau_statut)
        ? globalThis.String(object.nouveau_statut)
        : "",
      motif: isSet(object.motif) ? globalThis.String(object.motif) : "",
      changedAt: isSet(object.changedAt)
        ? fromJsonTimestamp(object.changedAt)
        : isSet(object.changed_at)
        ? fromJsonTimestamp(object.changed_at)
        : undefined,
    };
  },

  toJSON(message: AbonnementStatusChangedEvent): unknown {
    const obj: any = {};
    if (message.eventId !== "") {
      obj.eventId = message.eventId;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.correlationId !== "") {
      obj.correlationId = message.correlationId;
    }
    if (message.abonnementId !== "") {
      obj.abonnementId = message.abonnementId;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.ancienStatut !== "") {
      obj.ancienStatut = message.ancienStatut;
    }
    if (message.nouveauStatut !== "") {
      obj.nouveauStatut = message.nouveauStatut;
    }
    if (message.motif !== "") {
      obj.motif = message.motif;
    }
    if (message.changedAt !== undefined) {
      obj.changedAt = message.changedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AbonnementStatusChangedEvent>, I>>(base?: I): AbonnementStatusChangedEvent {
    return AbonnementStatusChangedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AbonnementStatusChangedEvent>, I>>(object: I): AbonnementStatusChangedEvent {
    const message = createBaseAbonnementStatusChangedEvent();
    message.eventId = object.eventId ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.correlationId = object.correlationId ?? "";
    message.abonnementId = object.abonnementId ?? "";
    message.clientId = object.clientId ?? "";
    message.organisationId = object.organisationId ?? "";
    message.ancienStatut = object.ancienStatut ?? "";
    message.nouveauStatut = object.nouveauStatut ?? "";
    message.motif = object.motif ?? "";
    message.changedAt = object.changedAt ?? undefined;
    return message;
  },
};

function createBaseAbonnementUpgradedEvent(): AbonnementUpgradedEvent {
  return {
    eventId: "",
    timestamp: 0,
    correlationId: "",
    abonnementId: "",
    clientId: "",
    organisationId: "",
    ancienneFormule: "",
    nouvelleFormule: "",
    upgradedAt: undefined,
  };
}

export const AbonnementUpgradedEvent: MessageFns<AbonnementUpgradedEvent> = {
  encode(message: AbonnementUpgradedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== "") {
      writer.uint32(10).string(message.eventId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).int64(message.timestamp);
    }
    if (message.correlationId !== "") {
      writer.uint32(26).string(message.correlationId);
    }
    if (message.abonnementId !== "") {
      writer.uint32(34).string(message.abonnementId);
    }
    if (message.clientId !== "") {
      writer.uint32(42).string(message.clientId);
    }
    if (message.organisationId !== "") {
      writer.uint32(50).string(message.organisationId);
    }
    if (message.ancienneFormule !== "") {
      writer.uint32(58).string(message.ancienneFormule);
    }
    if (message.nouvelleFormule !== "") {
      writer.uint32(66).string(message.nouvelleFormule);
    }
    if (message.upgradedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.upgradedAt), writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AbonnementUpgradedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAbonnementUpgradedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.abonnementId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.ancienneFormule = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.nouvelleFormule = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.upgradedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AbonnementUpgradedEvent {
    return {
      eventId: isSet(object.eventId)
        ? globalThis.String(object.eventId)
        : isSet(object.event_id)
        ? globalThis.String(object.event_id)
        : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      correlationId: isSet(object.correlationId)
        ? globalThis.String(object.correlationId)
        : isSet(object.correlation_id)
        ? globalThis.String(object.correlation_id)
        : "",
      abonnementId: isSet(object.abonnementId)
        ? globalThis.String(object.abonnementId)
        : isSet(object.abonnement_id)
        ? globalThis.String(object.abonnement_id)
        : "",
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      ancienneFormule: isSet(object.ancienneFormule)
        ? globalThis.String(object.ancienneFormule)
        : isSet(object.ancienne_formule)
        ? globalThis.String(object.ancienne_formule)
        : "",
      nouvelleFormule: isSet(object.nouvelleFormule)
        ? globalThis.String(object.nouvelleFormule)
        : isSet(object.nouvelle_formule)
        ? globalThis.String(object.nouvelle_formule)
        : "",
      upgradedAt: isSet(object.upgradedAt)
        ? fromJsonTimestamp(object.upgradedAt)
        : isSet(object.upgraded_at)
        ? fromJsonTimestamp(object.upgraded_at)
        : undefined,
    };
  },

  toJSON(message: AbonnementUpgradedEvent): unknown {
    const obj: any = {};
    if (message.eventId !== "") {
      obj.eventId = message.eventId;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.correlationId !== "") {
      obj.correlationId = message.correlationId;
    }
    if (message.abonnementId !== "") {
      obj.abonnementId = message.abonnementId;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.ancienneFormule !== "") {
      obj.ancienneFormule = message.ancienneFormule;
    }
    if (message.nouvelleFormule !== "") {
      obj.nouvelleFormule = message.nouvelleFormule;
    }
    if (message.upgradedAt !== undefined) {
      obj.upgradedAt = message.upgradedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AbonnementUpgradedEvent>, I>>(base?: I): AbonnementUpgradedEvent {
    return AbonnementUpgradedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AbonnementUpgradedEvent>, I>>(object: I): AbonnementUpgradedEvent {
    const message = createBaseAbonnementUpgradedEvent();
    message.eventId = object.eventId ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.correlationId = object.correlationId ?? "";
    message.abonnementId = object.abonnementId ?? "";
    message.clientId = object.clientId ?? "";
    message.organisationId = object.organisationId ?? "";
    message.ancienneFormule = object.ancienneFormule ?? "";
    message.nouvelleFormule = object.nouvelleFormule ?? "";
    message.upgradedAt = object.upgradedAt ?? undefined;
    return message;
  },
};

function createBaseAbonnementDowngradedEvent(): AbonnementDowngradedEvent {
  return {
    eventId: "",
    timestamp: 0,
    correlationId: "",
    abonnementId: "",
    clientId: "",
    organisationId: "",
    ancienneFormule: "",
    nouvelleFormule: "",
    downgradedAt: undefined,
  };
}

export const AbonnementDowngradedEvent: MessageFns<AbonnementDowngradedEvent> = {
  encode(message: AbonnementDowngradedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== "") {
      writer.uint32(10).string(message.eventId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).int64(message.timestamp);
    }
    if (message.correlationId !== "") {
      writer.uint32(26).string(message.correlationId);
    }
    if (message.abonnementId !== "") {
      writer.uint32(34).string(message.abonnementId);
    }
    if (message.clientId !== "") {
      writer.uint32(42).string(message.clientId);
    }
    if (message.organisationId !== "") {
      writer.uint32(50).string(message.organisationId);
    }
    if (message.ancienneFormule !== "") {
      writer.uint32(58).string(message.ancienneFormule);
    }
    if (message.nouvelleFormule !== "") {
      writer.uint32(66).string(message.nouvelleFormule);
    }
    if (message.downgradedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.downgradedAt), writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AbonnementDowngradedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAbonnementDowngradedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.abonnementId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.ancienneFormule = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.nouvelleFormule = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.downgradedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AbonnementDowngradedEvent {
    return {
      eventId: isSet(object.eventId)
        ? globalThis.String(object.eventId)
        : isSet(object.event_id)
        ? globalThis.String(object.event_id)
        : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      correlationId: isSet(object.correlationId)
        ? globalThis.String(object.correlationId)
        : isSet(object.correlation_id)
        ? globalThis.String(object.correlation_id)
        : "",
      abonnementId: isSet(object.abonnementId)
        ? globalThis.String(object.abonnementId)
        : isSet(object.abonnement_id)
        ? globalThis.String(object.abonnement_id)
        : "",
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      ancienneFormule: isSet(object.ancienneFormule)
        ? globalThis.String(object.ancienneFormule)
        : isSet(object.ancienne_formule)
        ? globalThis.String(object.ancienne_formule)
        : "",
      nouvelleFormule: isSet(object.nouvelleFormule)
        ? globalThis.String(object.nouvelleFormule)
        : isSet(object.nouvelle_formule)
        ? globalThis.String(object.nouvelle_formule)
        : "",
      downgradedAt: isSet(object.downgradedAt)
        ? fromJsonTimestamp(object.downgradedAt)
        : isSet(object.downgraded_at)
        ? fromJsonTimestamp(object.downgraded_at)
        : undefined,
    };
  },

  toJSON(message: AbonnementDowngradedEvent): unknown {
    const obj: any = {};
    if (message.eventId !== "") {
      obj.eventId = message.eventId;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.correlationId !== "") {
      obj.correlationId = message.correlationId;
    }
    if (message.abonnementId !== "") {
      obj.abonnementId = message.abonnementId;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.ancienneFormule !== "") {
      obj.ancienneFormule = message.ancienneFormule;
    }
    if (message.nouvelleFormule !== "") {
      obj.nouvelleFormule = message.nouvelleFormule;
    }
    if (message.downgradedAt !== undefined) {
      obj.downgradedAt = message.downgradedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AbonnementDowngradedEvent>, I>>(base?: I): AbonnementDowngradedEvent {
    return AbonnementDowngradedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AbonnementDowngradedEvent>, I>>(object: I): AbonnementDowngradedEvent {
    const message = createBaseAbonnementDowngradedEvent();
    message.eventId = object.eventId ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.correlationId = object.correlationId ?? "";
    message.abonnementId = object.abonnementId ?? "";
    message.clientId = object.clientId ?? "";
    message.organisationId = object.organisationId ?? "";
    message.ancienneFormule = object.ancienneFormule ?? "";
    message.nouvelleFormule = object.nouvelleFormule ?? "";
    message.downgradedAt = object.downgradedAt ?? undefined;
    return message;
  },
};

function createBaseDossierCreatedEvent(): DossierCreatedEvent {
  return {
    eventId: "",
    timestamp: 0,
    correlationId: "",
    dossierId: "",
    abonnementId: "",
    clientId: "",
    organisationId: "",
    typeSinistre: "",
    montantDeclare: 0,
    dateSinistre: undefined,
    createdAt: undefined,
  };
}

export const DossierCreatedEvent: MessageFns<DossierCreatedEvent> = {
  encode(message: DossierCreatedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== "") {
      writer.uint32(10).string(message.eventId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).int64(message.timestamp);
    }
    if (message.correlationId !== "") {
      writer.uint32(26).string(message.correlationId);
    }
    if (message.dossierId !== "") {
      writer.uint32(34).string(message.dossierId);
    }
    if (message.abonnementId !== "") {
      writer.uint32(42).string(message.abonnementId);
    }
    if (message.clientId !== "") {
      writer.uint32(50).string(message.clientId);
    }
    if (message.organisationId !== "") {
      writer.uint32(58).string(message.organisationId);
    }
    if (message.typeSinistre !== "") {
      writer.uint32(66).string(message.typeSinistre);
    }
    if (message.montantDeclare !== 0) {
      writer.uint32(73).double(message.montantDeclare);
    }
    if (message.dateSinistre !== undefined) {
      Timestamp.encode(toTimestamp(message.dateSinistre), writer.uint32(82).fork()).join();
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DossierCreatedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDossierCreatedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.dossierId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.abonnementId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.typeSinistre = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 73) {
            break;
          }

          message.montantDeclare = reader.double();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.dateSinistre = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DossierCreatedEvent {
    return {
      eventId: isSet(object.eventId)
        ? globalThis.String(object.eventId)
        : isSet(object.event_id)
        ? globalThis.String(object.event_id)
        : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      correlationId: isSet(object.correlationId)
        ? globalThis.String(object.correlationId)
        : isSet(object.correlation_id)
        ? globalThis.String(object.correlation_id)
        : "",
      dossierId: isSet(object.dossierId)
        ? globalThis.String(object.dossierId)
        : isSet(object.dossier_id)
        ? globalThis.String(object.dossier_id)
        : "",
      abonnementId: isSet(object.abonnementId)
        ? globalThis.String(object.abonnementId)
        : isSet(object.abonnement_id)
        ? globalThis.String(object.abonnement_id)
        : "",
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      typeSinistre: isSet(object.typeSinistre)
        ? globalThis.String(object.typeSinistre)
        : isSet(object.type_sinistre)
        ? globalThis.String(object.type_sinistre)
        : "",
      montantDeclare: isSet(object.montantDeclare)
        ? globalThis.Number(object.montantDeclare)
        : isSet(object.montant_declare)
        ? globalThis.Number(object.montant_declare)
        : 0,
      dateSinistre: isSet(object.dateSinistre)
        ? fromJsonTimestamp(object.dateSinistre)
        : isSet(object.date_sinistre)
        ? fromJsonTimestamp(object.date_sinistre)
        : undefined,
      createdAt: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
        ? fromJsonTimestamp(object.created_at)
        : undefined,
    };
  },

  toJSON(message: DossierCreatedEvent): unknown {
    const obj: any = {};
    if (message.eventId !== "") {
      obj.eventId = message.eventId;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.correlationId !== "") {
      obj.correlationId = message.correlationId;
    }
    if (message.dossierId !== "") {
      obj.dossierId = message.dossierId;
    }
    if (message.abonnementId !== "") {
      obj.abonnementId = message.abonnementId;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.typeSinistre !== "") {
      obj.typeSinistre = message.typeSinistre;
    }
    if (message.montantDeclare !== 0) {
      obj.montantDeclare = message.montantDeclare;
    }
    if (message.dateSinistre !== undefined) {
      obj.dateSinistre = message.dateSinistre.toISOString();
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DossierCreatedEvent>, I>>(base?: I): DossierCreatedEvent {
    return DossierCreatedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DossierCreatedEvent>, I>>(object: I): DossierCreatedEvent {
    const message = createBaseDossierCreatedEvent();
    message.eventId = object.eventId ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.correlationId = object.correlationId ?? "";
    message.dossierId = object.dossierId ?? "";
    message.abonnementId = object.abonnementId ?? "";
    message.clientId = object.clientId ?? "";
    message.organisationId = object.organisationId ?? "";
    message.typeSinistre = object.typeSinistre ?? "";
    message.montantDeclare = object.montantDeclare ?? 0;
    message.dateSinistre = object.dateSinistre ?? undefined;
    message.createdAt = object.createdAt ?? undefined;
    return message;
  },
};

function createBaseDossierStatusChangedEvent(): DossierStatusChangedEvent {
  return {
    eventId: "",
    timestamp: 0,
    correlationId: "",
    dossierId: "",
    abonnementId: "",
    clientId: "",
    organisationId: "",
    ancienStatut: "",
    nouveauStatut: "",
    changedAt: undefined,
  };
}

export const DossierStatusChangedEvent: MessageFns<DossierStatusChangedEvent> = {
  encode(message: DossierStatusChangedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== "") {
      writer.uint32(10).string(message.eventId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).int64(message.timestamp);
    }
    if (message.correlationId !== "") {
      writer.uint32(26).string(message.correlationId);
    }
    if (message.dossierId !== "") {
      writer.uint32(34).string(message.dossierId);
    }
    if (message.abonnementId !== "") {
      writer.uint32(42).string(message.abonnementId);
    }
    if (message.clientId !== "") {
      writer.uint32(50).string(message.clientId);
    }
    if (message.organisationId !== "") {
      writer.uint32(58).string(message.organisationId);
    }
    if (message.ancienStatut !== "") {
      writer.uint32(66).string(message.ancienStatut);
    }
    if (message.nouveauStatut !== "") {
      writer.uint32(74).string(message.nouveauStatut);
    }
    if (message.changedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.changedAt), writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DossierStatusChangedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDossierStatusChangedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.dossierId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.abonnementId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.ancienStatut = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.nouveauStatut = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.changedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DossierStatusChangedEvent {
    return {
      eventId: isSet(object.eventId)
        ? globalThis.String(object.eventId)
        : isSet(object.event_id)
        ? globalThis.String(object.event_id)
        : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      correlationId: isSet(object.correlationId)
        ? globalThis.String(object.correlationId)
        : isSet(object.correlation_id)
        ? globalThis.String(object.correlation_id)
        : "",
      dossierId: isSet(object.dossierId)
        ? globalThis.String(object.dossierId)
        : isSet(object.dossier_id)
        ? globalThis.String(object.dossier_id)
        : "",
      abonnementId: isSet(object.abonnementId)
        ? globalThis.String(object.abonnementId)
        : isSet(object.abonnement_id)
        ? globalThis.String(object.abonnement_id)
        : "",
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      ancienStatut: isSet(object.ancienStatut)
        ? globalThis.String(object.ancienStatut)
        : isSet(object.ancien_statut)
        ? globalThis.String(object.ancien_statut)
        : "",
      nouveauStatut: isSet(object.nouveauStatut)
        ? globalThis.String(object.nouveauStatut)
        : isSet(object.nouveau_statut)
        ? globalThis.String(object.nouveau_statut)
        : "",
      changedAt: isSet(object.changedAt)
        ? fromJsonTimestamp(object.changedAt)
        : isSet(object.changed_at)
        ? fromJsonTimestamp(object.changed_at)
        : undefined,
    };
  },

  toJSON(message: DossierStatusChangedEvent): unknown {
    const obj: any = {};
    if (message.eventId !== "") {
      obj.eventId = message.eventId;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.correlationId !== "") {
      obj.correlationId = message.correlationId;
    }
    if (message.dossierId !== "") {
      obj.dossierId = message.dossierId;
    }
    if (message.abonnementId !== "") {
      obj.abonnementId = message.abonnementId;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.ancienStatut !== "") {
      obj.ancienStatut = message.ancienStatut;
    }
    if (message.nouveauStatut !== "") {
      obj.nouveauStatut = message.nouveauStatut;
    }
    if (message.changedAt !== undefined) {
      obj.changedAt = message.changedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DossierStatusChangedEvent>, I>>(base?: I): DossierStatusChangedEvent {
    return DossierStatusChangedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DossierStatusChangedEvent>, I>>(object: I): DossierStatusChangedEvent {
    const message = createBaseDossierStatusChangedEvent();
    message.eventId = object.eventId ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.correlationId = object.correlationId ?? "";
    message.dossierId = object.dossierId ?? "";
    message.abonnementId = object.abonnementId ?? "";
    message.clientId = object.clientId ?? "";
    message.organisationId = object.organisationId ?? "";
    message.ancienStatut = object.ancienStatut ?? "";
    message.nouveauStatut = object.nouveauStatut ?? "";
    message.changedAt = object.changedAt ?? undefined;
    return message;
  },
};

function createBaseDossierDecisionEvent(): DossierDecisionEvent {
  return {
    eventId: "",
    timestamp: 0,
    correlationId: "",
    dossierId: "",
    abonnementId: "",
    clientId: "",
    organisationId: "",
    decision: "",
    montantAccorde: 0,
    motifRefus: "",
    decidedAt: undefined,
  };
}

export const DossierDecisionEvent: MessageFns<DossierDecisionEvent> = {
  encode(message: DossierDecisionEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== "") {
      writer.uint32(10).string(message.eventId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).int64(message.timestamp);
    }
    if (message.correlationId !== "") {
      writer.uint32(26).string(message.correlationId);
    }
    if (message.dossierId !== "") {
      writer.uint32(34).string(message.dossierId);
    }
    if (message.abonnementId !== "") {
      writer.uint32(42).string(message.abonnementId);
    }
    if (message.clientId !== "") {
      writer.uint32(50).string(message.clientId);
    }
    if (message.organisationId !== "") {
      writer.uint32(58).string(message.organisationId);
    }
    if (message.decision !== "") {
      writer.uint32(66).string(message.decision);
    }
    if (message.montantAccorde !== 0) {
      writer.uint32(73).double(message.montantAccorde);
    }
    if (message.motifRefus !== "") {
      writer.uint32(82).string(message.motifRefus);
    }
    if (message.decidedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.decidedAt), writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DossierDecisionEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDossierDecisionEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.dossierId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.abonnementId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.decision = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 73) {
            break;
          }

          message.montantAccorde = reader.double();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.motifRefus = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.decidedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DossierDecisionEvent {
    return {
      eventId: isSet(object.eventId)
        ? globalThis.String(object.eventId)
        : isSet(object.event_id)
        ? globalThis.String(object.event_id)
        : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      correlationId: isSet(object.correlationId)
        ? globalThis.String(object.correlationId)
        : isSet(object.correlation_id)
        ? globalThis.String(object.correlation_id)
        : "",
      dossierId: isSet(object.dossierId)
        ? globalThis.String(object.dossierId)
        : isSet(object.dossier_id)
        ? globalThis.String(object.dossier_id)
        : "",
      abonnementId: isSet(object.abonnementId)
        ? globalThis.String(object.abonnementId)
        : isSet(object.abonnement_id)
        ? globalThis.String(object.abonnement_id)
        : "",
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      decision: isSet(object.decision) ? globalThis.String(object.decision) : "",
      montantAccorde: isSet(object.montantAccorde)
        ? globalThis.Number(object.montantAccorde)
        : isSet(object.montant_accorde)
        ? globalThis.Number(object.montant_accorde)
        : 0,
      motifRefus: isSet(object.motifRefus)
        ? globalThis.String(object.motifRefus)
        : isSet(object.motif_refus)
        ? globalThis.String(object.motif_refus)
        : "",
      decidedAt: isSet(object.decidedAt)
        ? fromJsonTimestamp(object.decidedAt)
        : isSet(object.decided_at)
        ? fromJsonTimestamp(object.decided_at)
        : undefined,
    };
  },

  toJSON(message: DossierDecisionEvent): unknown {
    const obj: any = {};
    if (message.eventId !== "") {
      obj.eventId = message.eventId;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.correlationId !== "") {
      obj.correlationId = message.correlationId;
    }
    if (message.dossierId !== "") {
      obj.dossierId = message.dossierId;
    }
    if (message.abonnementId !== "") {
      obj.abonnementId = message.abonnementId;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.decision !== "") {
      obj.decision = message.decision;
    }
    if (message.montantAccorde !== 0) {
      obj.montantAccorde = message.montantAccorde;
    }
    if (message.motifRefus !== "") {
      obj.motifRefus = message.motifRefus;
    }
    if (message.decidedAt !== undefined) {
      obj.decidedAt = message.decidedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DossierDecisionEvent>, I>>(base?: I): DossierDecisionEvent {
    return DossierDecisionEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DossierDecisionEvent>, I>>(object: I): DossierDecisionEvent {
    const message = createBaseDossierDecisionEvent();
    message.eventId = object.eventId ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.correlationId = object.correlationId ?? "";
    message.dossierId = object.dossierId ?? "";
    message.abonnementId = object.abonnementId ?? "";
    message.clientId = object.clientId ?? "";
    message.organisationId = object.organisationId ?? "";
    message.decision = object.decision ?? "";
    message.montantAccorde = object.montantAccorde ?? 0;
    message.motifRefus = object.motifRefus ?? "";
    message.decidedAt = object.decidedAt ?? undefined;
    return message;
  },
};

function createBaseDossierClosedEvent(): DossierClosedEvent {
  return {
    eventId: "",
    timestamp: 0,
    correlationId: "",
    dossierId: "",
    abonnementId: "",
    clientId: "",
    organisationId: "",
    motifCloture: "",
    closedAt: undefined,
  };
}

export const DossierClosedEvent: MessageFns<DossierClosedEvent> = {
  encode(message: DossierClosedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== "") {
      writer.uint32(10).string(message.eventId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).int64(message.timestamp);
    }
    if (message.correlationId !== "") {
      writer.uint32(26).string(message.correlationId);
    }
    if (message.dossierId !== "") {
      writer.uint32(34).string(message.dossierId);
    }
    if (message.abonnementId !== "") {
      writer.uint32(42).string(message.abonnementId);
    }
    if (message.clientId !== "") {
      writer.uint32(50).string(message.clientId);
    }
    if (message.organisationId !== "") {
      writer.uint32(58).string(message.organisationId);
    }
    if (message.motifCloture !== "") {
      writer.uint32(66).string(message.motifCloture);
    }
    if (message.closedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.closedAt), writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DossierClosedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDossierClosedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.dossierId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.abonnementId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.motifCloture = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.closedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DossierClosedEvent {
    return {
      eventId: isSet(object.eventId)
        ? globalThis.String(object.eventId)
        : isSet(object.event_id)
        ? globalThis.String(object.event_id)
        : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      correlationId: isSet(object.correlationId)
        ? globalThis.String(object.correlationId)
        : isSet(object.correlation_id)
        ? globalThis.String(object.correlation_id)
        : "",
      dossierId: isSet(object.dossierId)
        ? globalThis.String(object.dossierId)
        : isSet(object.dossier_id)
        ? globalThis.String(object.dossier_id)
        : "",
      abonnementId: isSet(object.abonnementId)
        ? globalThis.String(object.abonnementId)
        : isSet(object.abonnement_id)
        ? globalThis.String(object.abonnement_id)
        : "",
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      motifCloture: isSet(object.motifCloture)
        ? globalThis.String(object.motifCloture)
        : isSet(object.motif_cloture)
        ? globalThis.String(object.motif_cloture)
        : "",
      closedAt: isSet(object.closedAt)
        ? fromJsonTimestamp(object.closedAt)
        : isSet(object.closed_at)
        ? fromJsonTimestamp(object.closed_at)
        : undefined,
    };
  },

  toJSON(message: DossierClosedEvent): unknown {
    const obj: any = {};
    if (message.eventId !== "") {
      obj.eventId = message.eventId;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.correlationId !== "") {
      obj.correlationId = message.correlationId;
    }
    if (message.dossierId !== "") {
      obj.dossierId = message.dossierId;
    }
    if (message.abonnementId !== "") {
      obj.abonnementId = message.abonnementId;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.motifCloture !== "") {
      obj.motifCloture = message.motifCloture;
    }
    if (message.closedAt !== undefined) {
      obj.closedAt = message.closedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DossierClosedEvent>, I>>(base?: I): DossierClosedEvent {
    return DossierClosedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DossierClosedEvent>, I>>(object: I): DossierClosedEvent {
    const message = createBaseDossierClosedEvent();
    message.eventId = object.eventId ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.correlationId = object.correlationId ?? "";
    message.dossierId = object.dossierId ?? "";
    message.abonnementId = object.abonnementId ?? "";
    message.clientId = object.clientId ?? "";
    message.organisationId = object.organisationId ?? "";
    message.motifCloture = object.motifCloture ?? "";
    message.closedAt = object.closedAt ?? undefined;
    return message;
  },
};

function createBasePlafondThresholdReachedEvent(): PlafondThresholdReachedEvent {
  return {
    eventId: "",
    timestamp: 0,
    correlationId: "",
    abonnementId: "",
    clientId: "",
    organisationId: "",
    plafondAnnuel: 0,
    montantUtilise: 0,
    pourcentageUtilise: 0,
    reachedAt: undefined,
  };
}

export const PlafondThresholdReachedEvent: MessageFns<PlafondThresholdReachedEvent> = {
  encode(message: PlafondThresholdReachedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== "") {
      writer.uint32(10).string(message.eventId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).int64(message.timestamp);
    }
    if (message.correlationId !== "") {
      writer.uint32(26).string(message.correlationId);
    }
    if (message.abonnementId !== "") {
      writer.uint32(34).string(message.abonnementId);
    }
    if (message.clientId !== "") {
      writer.uint32(42).string(message.clientId);
    }
    if (message.organisationId !== "") {
      writer.uint32(50).string(message.organisationId);
    }
    if (message.plafondAnnuel !== 0) {
      writer.uint32(57).double(message.plafondAnnuel);
    }
    if (message.montantUtilise !== 0) {
      writer.uint32(65).double(message.montantUtilise);
    }
    if (message.pourcentageUtilise !== 0) {
      writer.uint32(73).double(message.pourcentageUtilise);
    }
    if (message.reachedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.reachedAt), writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlafondThresholdReachedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlafondThresholdReachedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.abonnementId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.plafondAnnuel = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.montantUtilise = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 73) {
            break;
          }

          message.pourcentageUtilise = reader.double();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.reachedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlafondThresholdReachedEvent {
    return {
      eventId: isSet(object.eventId)
        ? globalThis.String(object.eventId)
        : isSet(object.event_id)
        ? globalThis.String(object.event_id)
        : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      correlationId: isSet(object.correlationId)
        ? globalThis.String(object.correlationId)
        : isSet(object.correlation_id)
        ? globalThis.String(object.correlation_id)
        : "",
      abonnementId: isSet(object.abonnementId)
        ? globalThis.String(object.abonnementId)
        : isSet(object.abonnement_id)
        ? globalThis.String(object.abonnement_id)
        : "",
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      plafondAnnuel: isSet(object.plafondAnnuel)
        ? globalThis.Number(object.plafondAnnuel)
        : isSet(object.plafond_annuel)
        ? globalThis.Number(object.plafond_annuel)
        : 0,
      montantUtilise: isSet(object.montantUtilise)
        ? globalThis.Number(object.montantUtilise)
        : isSet(object.montant_utilise)
        ? globalThis.Number(object.montant_utilise)
        : 0,
      pourcentageUtilise: isSet(object.pourcentageUtilise)
        ? globalThis.Number(object.pourcentageUtilise)
        : isSet(object.pourcentage_utilise)
        ? globalThis.Number(object.pourcentage_utilise)
        : 0,
      reachedAt: isSet(object.reachedAt)
        ? fromJsonTimestamp(object.reachedAt)
        : isSet(object.reached_at)
        ? fromJsonTimestamp(object.reached_at)
        : undefined,
    };
  },

  toJSON(message: PlafondThresholdReachedEvent): unknown {
    const obj: any = {};
    if (message.eventId !== "") {
      obj.eventId = message.eventId;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.correlationId !== "") {
      obj.correlationId = message.correlationId;
    }
    if (message.abonnementId !== "") {
      obj.abonnementId = message.abonnementId;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.plafondAnnuel !== 0) {
      obj.plafondAnnuel = message.plafondAnnuel;
    }
    if (message.montantUtilise !== 0) {
      obj.montantUtilise = message.montantUtilise;
    }
    if (message.pourcentageUtilise !== 0) {
      obj.pourcentageUtilise = message.pourcentageUtilise;
    }
    if (message.reachedAt !== undefined) {
      obj.reachedAt = message.reachedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlafondThresholdReachedEvent>, I>>(base?: I): PlafondThresholdReachedEvent {
    return PlafondThresholdReachedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlafondThresholdReachedEvent>, I>>(object: I): PlafondThresholdReachedEvent {
    const message = createBasePlafondThresholdReachedEvent();
    message.eventId = object.eventId ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.correlationId = object.correlationId ?? "";
    message.abonnementId = object.abonnementId ?? "";
    message.clientId = object.clientId ?? "";
    message.organisationId = object.organisationId ?? "";
    message.plafondAnnuel = object.plafondAnnuel ?? 0;
    message.montantUtilise = object.montantUtilise ?? 0;
    message.pourcentageUtilise = object.pourcentageUtilise ?? 0;
    message.reachedAt = object.reachedAt ?? undefined;
    return message;
  },
};

function createBasePlafondExceededEvent(): PlafondExceededEvent {
  return {
    eventId: "",
    timestamp: 0,
    correlationId: "",
    abonnementId: "",
    clientId: "",
    organisationId: "",
    plafondAnnuel: 0,
    montantUtilise: 0,
    montantDepasse: 0,
    exceededAt: undefined,
  };
}

export const PlafondExceededEvent: MessageFns<PlafondExceededEvent> = {
  encode(message: PlafondExceededEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== "") {
      writer.uint32(10).string(message.eventId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).int64(message.timestamp);
    }
    if (message.correlationId !== "") {
      writer.uint32(26).string(message.correlationId);
    }
    if (message.abonnementId !== "") {
      writer.uint32(34).string(message.abonnementId);
    }
    if (message.clientId !== "") {
      writer.uint32(42).string(message.clientId);
    }
    if (message.organisationId !== "") {
      writer.uint32(50).string(message.organisationId);
    }
    if (message.plafondAnnuel !== 0) {
      writer.uint32(57).double(message.plafondAnnuel);
    }
    if (message.montantUtilise !== 0) {
      writer.uint32(65).double(message.montantUtilise);
    }
    if (message.montantDepasse !== 0) {
      writer.uint32(73).double(message.montantDepasse);
    }
    if (message.exceededAt !== undefined) {
      Timestamp.encode(toTimestamp(message.exceededAt), writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlafondExceededEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlafondExceededEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.abonnementId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.plafondAnnuel = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.montantUtilise = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 73) {
            break;
          }

          message.montantDepasse = reader.double();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.exceededAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlafondExceededEvent {
    return {
      eventId: isSet(object.eventId)
        ? globalThis.String(object.eventId)
        : isSet(object.event_id)
        ? globalThis.String(object.event_id)
        : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      correlationId: isSet(object.correlationId)
        ? globalThis.String(object.correlationId)
        : isSet(object.correlation_id)
        ? globalThis.String(object.correlation_id)
        : "",
      abonnementId: isSet(object.abonnementId)
        ? globalThis.String(object.abonnementId)
        : isSet(object.abonnement_id)
        ? globalThis.String(object.abonnement_id)
        : "",
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      plafondAnnuel: isSet(object.plafondAnnuel)
        ? globalThis.Number(object.plafondAnnuel)
        : isSet(object.plafond_annuel)
        ? globalThis.Number(object.plafond_annuel)
        : 0,
      montantUtilise: isSet(object.montantUtilise)
        ? globalThis.Number(object.montantUtilise)
        : isSet(object.montant_utilise)
        ? globalThis.Number(object.montant_utilise)
        : 0,
      montantDepasse: isSet(object.montantDepasse)
        ? globalThis.Number(object.montantDepasse)
        : isSet(object.montant_depasse)
        ? globalThis.Number(object.montant_depasse)
        : 0,
      exceededAt: isSet(object.exceededAt)
        ? fromJsonTimestamp(object.exceededAt)
        : isSet(object.exceeded_at)
        ? fromJsonTimestamp(object.exceeded_at)
        : undefined,
    };
  },

  toJSON(message: PlafondExceededEvent): unknown {
    const obj: any = {};
    if (message.eventId !== "") {
      obj.eventId = message.eventId;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.correlationId !== "") {
      obj.correlationId = message.correlationId;
    }
    if (message.abonnementId !== "") {
      obj.abonnementId = message.abonnementId;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.plafondAnnuel !== 0) {
      obj.plafondAnnuel = message.plafondAnnuel;
    }
    if (message.montantUtilise !== 0) {
      obj.montantUtilise = message.montantUtilise;
    }
    if (message.montantDepasse !== 0) {
      obj.montantDepasse = message.montantDepasse;
    }
    if (message.exceededAt !== undefined) {
      obj.exceededAt = message.exceededAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlafondExceededEvent>, I>>(base?: I): PlafondExceededEvent {
    return PlafondExceededEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlafondExceededEvent>, I>>(object: I): PlafondExceededEvent {
    const message = createBasePlafondExceededEvent();
    message.eventId = object.eventId ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.correlationId = object.correlationId ?? "";
    message.abonnementId = object.abonnementId ?? "";
    message.clientId = object.clientId ?? "";
    message.organisationId = object.organisationId ?? "";
    message.plafondAnnuel = object.plafondAnnuel ?? 0;
    message.montantUtilise = object.montantUtilise ?? 0;
    message.montantDepasse = object.montantDepasse ?? 0;
    message.exceededAt = object.exceededAt ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
