services:
  crm-frontend:
    build:
      context: ../..
      dockerfile: frontend/Dockerfile
      target: development
    container_name: alex-frontend # <--- Préfixe unique
    labels:
      - "traefik.enable=true"
      # URL : http://alex.local:8081
      - "traefik.http.routers.alex-front.rule=Host(`alex.local`)"
      - "traefik.http.services.alex-front.loadbalancer.server.port=3000"
    ports:
      - "3070:3000" # host:container (3070 libre sur TRX50, accès via Traefik sur 8081)
    env_file:
      - ../../frontend/.env.development
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
      - WATCHPACK_POLLING=true
    # depends_on retiré : on utilise le postgres global déjà sain
    # volumes retirés : le serveur n'a pas accès à ton Desktop\crm_final local
    networks:
      - shared_dev_net # <--- Correction ici
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 2G

networks:
  shared_dev_net:
    external: true