services:
  crm-frontend:
    build:
      context: ../..
      dockerfile: frontend/Dockerfile
      target: development
    container_name: dev-crm-frontend
    ports:
      - "3000:3000"
    env_file:
      - ../../frontend/.env.development
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
      - WATCHPACK_POLLING=true
    depends_on:
      postgres-main:
        condition: service_healthy
    volumes:
      - ../../frontend/src:/app/src
      - ../../frontend/public:/app/public
      # Note: node_modules and .next intentionally NOT mounted - container uses its own
      - ../../frontend/next.config.ts:/app/next.config.ts
      - ../../frontend/tsconfig.json:/app/tsconfig.json
      - ../../frontend/postcss.config.mjs:/app/postcss.config.mjs
      - ../../frontend/biome.json:/app/biome.json
      - ../../frontend/components.json:/app/components.json
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 2G

