services:
  consul:
    image: hashicorp/consul:1.17
    container_name: dev-crm-consul
    command: agent -dev -client=0.0.0.0 -ui
    ports:
      - "8500:8500"
    volumes:
      - crm_consul_data:/consul/data
    healthcheck:
      test: ["CMD", "consul", "info"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - crm-network
    restart: unless-stopped

  redis:
    image: redis:8.4-alpine
    container_name: dev-crm-redis
    ports:
      - "6380:6379"
    volumes:
      - crm_redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crm-network
    restart: unless-stopped

  postgres-main:
    image: postgres:16-alpine
    container_name: dev-crm-postgres-main
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: crm_main
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - postgres_main_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crm-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

  nats:
    image: nats:2.10-alpine
    container_name: dev-crm-nats
    command: "-js -m 8222"
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crm-network
    restart: unless-stopped

networks:
  crm-network:
    driver: bridge

volumes:
  crm_consul_data:
  crm_redis_data:
  postgres_main_data:
