services:
  # ============================================================================
  # GLOBAL INFRASTRUCTURE (managed externally on TRX50)
  # global_postgres, global_redis, global_router (Traefik) run as standalone
  # containers on shared_dev_net — do NOT redefine them here.
  # ============================================================================

  # ============================================================================
  # PER-DEVELOPER INFRASTRUCTURE (alex- prefixed)
  # ============================================================================

  # Consul - per-dev service discovery
  consul:
    image: hashicorp/consul:1.17
    container_name: alex-crm-consul
    command: agent -dev -client=0.0.0.0 -ui
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alex-consul.rule=Host(`alex-consul.local`)"
      - "traefik.http.services.alex-consul.loadbalancer.server.port=8500"
    networks:
      - shared_dev_net
    restart: unless-stopped

  # NATS - per-dev event streaming
  nats:
    image: nats:2.10-alpine
    container_name: alex-crm-nats
    command: "-js -m 8222"
    networks:
      - shared_dev_net
    restart: unless-stopped

networks:
  shared_dev_net:
    external: true