services:
  crm-service-finance:
    build:
      context: ../..
      dockerfile: services/service-finance/Dockerfile
      target: development
    container_name: dev-crm-service-finance
    ports:
      - "50059:50059"
      - "3059:3059"
    env_file:
      - ../../services/service-finance/.env.development
    environment:
      - NODE_PATH=/app/services/service-finance/node_modules
    depends_on:
      postgres-main:
        condition: service_healthy
    volumes:
      - ../../services/service-finance/src:/app/services/service-finance/src
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('net').connect(3059, 'localhost').on('connect', () => process.exit(0))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
