services:
  crm-service-commercial:
    build:
      context: ../..
      dockerfile: services/service-commercial/Dockerfile
      target: development
    container_name: dev-crm-service-commercial
    ports:
      - "50053:50053"
      - "3053:3053"
    env_file:
      - ../../services/service-commercial/.env.development
    environment:
      - NODE_PATH=/app/services/service-commercial/node_modules
    depends_on:
      postgres-main:
        condition: service_healthy
    volumes:
      - ../../services/service-commercial/src:/app/services/service-commercial/src
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('net').connect(3053, 'localhost').on('connect', () => process.exit(0))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
