services:
  crm-service-core:
    build:
      context: ../..
      dockerfile: services/service-core/Dockerfile
      target: development
    container_name: dev-crm-service-core
    ports:
      - "50052:50052"
      - "3052:3052"
    env_file:
      - ../../services/service-core/.env.development
    environment:
      - NODE_PATH=/app/services/service-core/node_modules
    depends_on:
      postgres-main:
        condition: service_healthy
    volumes:
      - ../../services/service-core/src:/app/services/service-core/src
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('net').connect(3052, 'localhost').on('connect', () => process.exit(0))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
