// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: payments/payment-info.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";

export const protobufPackage = "payment_info";

export interface CreateInformationPaiementBancaireRequest {
  organisationId: string;
  clientId: string;
  /** IBAN stored in clear text (max 34 chars) */
  iban: string;
  /** BIC stored in clear text (max 11 chars) */
  bic: string;
  /** Account holder name (max 255 chars) */
  titulaireCompte?:
    | string
    | undefined;
  /** SEPA mandate reference (max 255 chars) */
  mandatSepaReference?:
    | string
    | undefined;
  /** ISO timestamp of mandate signature */
  dateMandat?:
    | string
    | undefined;
  /** Status: ACTIF, INACTIF, EXPIRE, SUSPENDU (default: ACTIF) */
  statut?:
    | string
    | undefined;
  /** Free text comment */
  commentaire?:
    | string
    | undefined;
  /** External ID from legacy system (max 255 chars) */
  externalId?: string | undefined;
}

export interface GetInformationPaiementBancaireByIdRequest {
  id: string;
}

export interface GetInformationPaiementBancaireByClientIdRequest {
  clientId: string;
}

export interface GetInformationPaiementBancaireByExternalIdRequest {
  organisationId: string;
  externalId: string;
}

export interface UpdateInformationPaiementBancaireRequest {
  id: string;
  iban?: string | undefined;
  bic?: string | undefined;
  titulaireCompte?: string | undefined;
  mandatSepaReference?:
    | string
    | undefined;
  /** ISO timestamp */
  dateMandat?: string | undefined;
  statut?: string | undefined;
  commentaire?: string | undefined;
}

export interface UpsertInformationPaiementBancaireRequest {
  organisationId: string;
  clientId: string;
  iban: string;
  bic: string;
  titulaireCompte?: string | undefined;
  mandatSepaReference?:
    | string
    | undefined;
  /** ISO timestamp */
  dateMandat?: string | undefined;
  statut?: string | undefined;
  commentaire?:
    | string
    | undefined;
  /** Required for upsert */
  externalId: string;
  /** ISO timestamp for conflict resolution (most recent wins) */
  updatedAt?: string | undefined;
}

export interface DeleteInformationPaiementBancaireRequest {
  id: string;
}

export interface InformationPaiementBancaireResponse {
  id: string;
  organisationId: string;
  clientId: string;
  /** IBAN in clear text */
  iban: string;
  /** BIC in clear text */
  bic: string;
  titulaireCompte: string;
  mandatSepaReference: string;
  /** ISO timestamp */
  dateMandat: string;
  statut: string;
  commentaire: string;
  externalId: string;
  /** ISO timestamp */
  createdAt: string;
  /** ISO timestamp */
  updatedAt: string;
}

export interface InformationPaiementBancaireListResponse {
  items: InformationPaiementBancaireResponse[];
  total: number;
}

export interface UpsertInformationPaiementBancaireResponse {
  entity:
    | InformationPaiementBancaireResponse
    | undefined;
  /** true if created, false if updated */
  created: boolean;
}

export interface DeleteResponse {
  success: boolean;
  message: string;
}

function createBaseCreateInformationPaiementBancaireRequest(): CreateInformationPaiementBancaireRequest {
  return {
    organisationId: "",
    clientId: "",
    iban: "",
    bic: "",
    titulaireCompte: undefined,
    mandatSepaReference: undefined,
    dateMandat: undefined,
    statut: undefined,
    commentaire: undefined,
    externalId: undefined,
  };
}

export const CreateInformationPaiementBancaireRequest: MessageFns<CreateInformationPaiementBancaireRequest> = {
  encode(message: CreateInformationPaiementBancaireRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.organisationId !== "") {
      writer.uint32(10).string(message.organisationId);
    }
    if (message.clientId !== "") {
      writer.uint32(18).string(message.clientId);
    }
    if (message.iban !== "") {
      writer.uint32(26).string(message.iban);
    }
    if (message.bic !== "") {
      writer.uint32(34).string(message.bic);
    }
    if (message.titulaireCompte !== undefined) {
      writer.uint32(42).string(message.titulaireCompte);
    }
    if (message.mandatSepaReference !== undefined) {
      writer.uint32(50).string(message.mandatSepaReference);
    }
    if (message.dateMandat !== undefined) {
      writer.uint32(58).string(message.dateMandat);
    }
    if (message.statut !== undefined) {
      writer.uint32(66).string(message.statut);
    }
    if (message.commentaire !== undefined) {
      writer.uint32(74).string(message.commentaire);
    }
    if (message.externalId !== undefined) {
      writer.uint32(82).string(message.externalId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateInformationPaiementBancaireRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateInformationPaiementBancaireRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.iban = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.bic = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.titulaireCompte = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.mandatSepaReference = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.dateMandat = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.statut = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.commentaire = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.externalId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateInformationPaiementBancaireRequest {
    return {
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      iban: isSet(object.iban) ? globalThis.String(object.iban) : "",
      bic: isSet(object.bic) ? globalThis.String(object.bic) : "",
      titulaireCompte: isSet(object.titulaireCompte)
        ? globalThis.String(object.titulaireCompte)
        : isSet(object.titulaire_compte)
        ? globalThis.String(object.titulaire_compte)
        : undefined,
      mandatSepaReference: isSet(object.mandatSepaReference)
        ? globalThis.String(object.mandatSepaReference)
        : isSet(object.mandat_sepa_reference)
        ? globalThis.String(object.mandat_sepa_reference)
        : undefined,
      dateMandat: isSet(object.dateMandat)
        ? globalThis.String(object.dateMandat)
        : isSet(object.date_mandat)
        ? globalThis.String(object.date_mandat)
        : undefined,
      statut: isSet(object.statut) ? globalThis.String(object.statut) : undefined,
      commentaire: isSet(object.commentaire) ? globalThis.String(object.commentaire) : undefined,
      externalId: isSet(object.externalId)
        ? globalThis.String(object.externalId)
        : isSet(object.external_id)
        ? globalThis.String(object.external_id)
        : undefined,
    };
  },

  toJSON(message: CreateInformationPaiementBancaireRequest): unknown {
    const obj: any = {};
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.iban !== "") {
      obj.iban = message.iban;
    }
    if (message.bic !== "") {
      obj.bic = message.bic;
    }
    if (message.titulaireCompte !== undefined) {
      obj.titulaireCompte = message.titulaireCompte;
    }
    if (message.mandatSepaReference !== undefined) {
      obj.mandatSepaReference = message.mandatSepaReference;
    }
    if (message.dateMandat !== undefined) {
      obj.dateMandat = message.dateMandat;
    }
    if (message.statut !== undefined) {
      obj.statut = message.statut;
    }
    if (message.commentaire !== undefined) {
      obj.commentaire = message.commentaire;
    }
    if (message.externalId !== undefined) {
      obj.externalId = message.externalId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateInformationPaiementBancaireRequest>, I>>(
    base?: I,
  ): CreateInformationPaiementBancaireRequest {
    return CreateInformationPaiementBancaireRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateInformationPaiementBancaireRequest>, I>>(
    object: I,
  ): CreateInformationPaiementBancaireRequest {
    const message = createBaseCreateInformationPaiementBancaireRequest();
    message.organisationId = object.organisationId ?? "";
    message.clientId = object.clientId ?? "";
    message.iban = object.iban ?? "";
    message.bic = object.bic ?? "";
    message.titulaireCompte = object.titulaireCompte ?? undefined;
    message.mandatSepaReference = object.mandatSepaReference ?? undefined;
    message.dateMandat = object.dateMandat ?? undefined;
    message.statut = object.statut ?? undefined;
    message.commentaire = object.commentaire ?? undefined;
    message.externalId = object.externalId ?? undefined;
    return message;
  },
};

function createBaseGetInformationPaiementBancaireByIdRequest(): GetInformationPaiementBancaireByIdRequest {
  return { id: "" };
}

export const GetInformationPaiementBancaireByIdRequest: MessageFns<GetInformationPaiementBancaireByIdRequest> = {
  encode(message: GetInformationPaiementBancaireByIdRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetInformationPaiementBancaireByIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetInformationPaiementBancaireByIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetInformationPaiementBancaireByIdRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetInformationPaiementBancaireByIdRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetInformationPaiementBancaireByIdRequest>, I>>(
    base?: I,
  ): GetInformationPaiementBancaireByIdRequest {
    return GetInformationPaiementBancaireByIdRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetInformationPaiementBancaireByIdRequest>, I>>(
    object: I,
  ): GetInformationPaiementBancaireByIdRequest {
    const message = createBaseGetInformationPaiementBancaireByIdRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseGetInformationPaiementBancaireByClientIdRequest(): GetInformationPaiementBancaireByClientIdRequest {
  return { clientId: "" };
}

export const GetInformationPaiementBancaireByClientIdRequest: MessageFns<
  GetInformationPaiementBancaireByClientIdRequest
> = {
  encode(
    message: GetInformationPaiementBancaireByClientIdRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.clientId !== "") {
      writer.uint32(10).string(message.clientId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetInformationPaiementBancaireByClientIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetInformationPaiementBancaireByClientIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetInformationPaiementBancaireByClientIdRequest {
    return {
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
    };
  },

  toJSON(message: GetInformationPaiementBancaireByClientIdRequest): unknown {
    const obj: any = {};
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetInformationPaiementBancaireByClientIdRequest>, I>>(
    base?: I,
  ): GetInformationPaiementBancaireByClientIdRequest {
    return GetInformationPaiementBancaireByClientIdRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetInformationPaiementBancaireByClientIdRequest>, I>>(
    object: I,
  ): GetInformationPaiementBancaireByClientIdRequest {
    const message = createBaseGetInformationPaiementBancaireByClientIdRequest();
    message.clientId = object.clientId ?? "";
    return message;
  },
};

function createBaseGetInformationPaiementBancaireByExternalIdRequest(): GetInformationPaiementBancaireByExternalIdRequest {
  return { organisationId: "", externalId: "" };
}

export const GetInformationPaiementBancaireByExternalIdRequest: MessageFns<
  GetInformationPaiementBancaireByExternalIdRequest
> = {
  encode(
    message: GetInformationPaiementBancaireByExternalIdRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.organisationId !== "") {
      writer.uint32(10).string(message.organisationId);
    }
    if (message.externalId !== "") {
      writer.uint32(18).string(message.externalId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetInformationPaiementBancaireByExternalIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetInformationPaiementBancaireByExternalIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.externalId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetInformationPaiementBancaireByExternalIdRequest {
    return {
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      externalId: isSet(object.externalId)
        ? globalThis.String(object.externalId)
        : isSet(object.external_id)
        ? globalThis.String(object.external_id)
        : "",
    };
  },

  toJSON(message: GetInformationPaiementBancaireByExternalIdRequest): unknown {
    const obj: any = {};
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.externalId !== "") {
      obj.externalId = message.externalId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetInformationPaiementBancaireByExternalIdRequest>, I>>(
    base?: I,
  ): GetInformationPaiementBancaireByExternalIdRequest {
    return GetInformationPaiementBancaireByExternalIdRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetInformationPaiementBancaireByExternalIdRequest>, I>>(
    object: I,
  ): GetInformationPaiementBancaireByExternalIdRequest {
    const message = createBaseGetInformationPaiementBancaireByExternalIdRequest();
    message.organisationId = object.organisationId ?? "";
    message.externalId = object.externalId ?? "";
    return message;
  },
};

function createBaseUpdateInformationPaiementBancaireRequest(): UpdateInformationPaiementBancaireRequest {
  return {
    id: "",
    iban: undefined,
    bic: undefined,
    titulaireCompte: undefined,
    mandatSepaReference: undefined,
    dateMandat: undefined,
    statut: undefined,
    commentaire: undefined,
  };
}

export const UpdateInformationPaiementBancaireRequest: MessageFns<UpdateInformationPaiementBancaireRequest> = {
  encode(message: UpdateInformationPaiementBancaireRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.iban !== undefined) {
      writer.uint32(18).string(message.iban);
    }
    if (message.bic !== undefined) {
      writer.uint32(26).string(message.bic);
    }
    if (message.titulaireCompte !== undefined) {
      writer.uint32(34).string(message.titulaireCompte);
    }
    if (message.mandatSepaReference !== undefined) {
      writer.uint32(42).string(message.mandatSepaReference);
    }
    if (message.dateMandat !== undefined) {
      writer.uint32(50).string(message.dateMandat);
    }
    if (message.statut !== undefined) {
      writer.uint32(58).string(message.statut);
    }
    if (message.commentaire !== undefined) {
      writer.uint32(66).string(message.commentaire);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateInformationPaiementBancaireRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateInformationPaiementBancaireRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.iban = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.bic = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.titulaireCompte = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.mandatSepaReference = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.dateMandat = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.statut = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.commentaire = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateInformationPaiementBancaireRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      iban: isSet(object.iban) ? globalThis.String(object.iban) : undefined,
      bic: isSet(object.bic) ? globalThis.String(object.bic) : undefined,
      titulaireCompte: isSet(object.titulaireCompte)
        ? globalThis.String(object.titulaireCompte)
        : isSet(object.titulaire_compte)
        ? globalThis.String(object.titulaire_compte)
        : undefined,
      mandatSepaReference: isSet(object.mandatSepaReference)
        ? globalThis.String(object.mandatSepaReference)
        : isSet(object.mandat_sepa_reference)
        ? globalThis.String(object.mandat_sepa_reference)
        : undefined,
      dateMandat: isSet(object.dateMandat)
        ? globalThis.String(object.dateMandat)
        : isSet(object.date_mandat)
        ? globalThis.String(object.date_mandat)
        : undefined,
      statut: isSet(object.statut) ? globalThis.String(object.statut) : undefined,
      commentaire: isSet(object.commentaire) ? globalThis.String(object.commentaire) : undefined,
    };
  },

  toJSON(message: UpdateInformationPaiementBancaireRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.iban !== undefined) {
      obj.iban = message.iban;
    }
    if (message.bic !== undefined) {
      obj.bic = message.bic;
    }
    if (message.titulaireCompte !== undefined) {
      obj.titulaireCompte = message.titulaireCompte;
    }
    if (message.mandatSepaReference !== undefined) {
      obj.mandatSepaReference = message.mandatSepaReference;
    }
    if (message.dateMandat !== undefined) {
      obj.dateMandat = message.dateMandat;
    }
    if (message.statut !== undefined) {
      obj.statut = message.statut;
    }
    if (message.commentaire !== undefined) {
      obj.commentaire = message.commentaire;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateInformationPaiementBancaireRequest>, I>>(
    base?: I,
  ): UpdateInformationPaiementBancaireRequest {
    return UpdateInformationPaiementBancaireRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateInformationPaiementBancaireRequest>, I>>(
    object: I,
  ): UpdateInformationPaiementBancaireRequest {
    const message = createBaseUpdateInformationPaiementBancaireRequest();
    message.id = object.id ?? "";
    message.iban = object.iban ?? undefined;
    message.bic = object.bic ?? undefined;
    message.titulaireCompte = object.titulaireCompte ?? undefined;
    message.mandatSepaReference = object.mandatSepaReference ?? undefined;
    message.dateMandat = object.dateMandat ?? undefined;
    message.statut = object.statut ?? undefined;
    message.commentaire = object.commentaire ?? undefined;
    return message;
  },
};

function createBaseUpsertInformationPaiementBancaireRequest(): UpsertInformationPaiementBancaireRequest {
  return {
    organisationId: "",
    clientId: "",
    iban: "",
    bic: "",
    titulaireCompte: undefined,
    mandatSepaReference: undefined,
    dateMandat: undefined,
    statut: undefined,
    commentaire: undefined,
    externalId: "",
    updatedAt: undefined,
  };
}

export const UpsertInformationPaiementBancaireRequest: MessageFns<UpsertInformationPaiementBancaireRequest> = {
  encode(message: UpsertInformationPaiementBancaireRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.organisationId !== "") {
      writer.uint32(10).string(message.organisationId);
    }
    if (message.clientId !== "") {
      writer.uint32(18).string(message.clientId);
    }
    if (message.iban !== "") {
      writer.uint32(26).string(message.iban);
    }
    if (message.bic !== "") {
      writer.uint32(34).string(message.bic);
    }
    if (message.titulaireCompte !== undefined) {
      writer.uint32(42).string(message.titulaireCompte);
    }
    if (message.mandatSepaReference !== undefined) {
      writer.uint32(50).string(message.mandatSepaReference);
    }
    if (message.dateMandat !== undefined) {
      writer.uint32(58).string(message.dateMandat);
    }
    if (message.statut !== undefined) {
      writer.uint32(66).string(message.statut);
    }
    if (message.commentaire !== undefined) {
      writer.uint32(74).string(message.commentaire);
    }
    if (message.externalId !== "") {
      writer.uint32(82).string(message.externalId);
    }
    if (message.updatedAt !== undefined) {
      writer.uint32(90).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpsertInformationPaiementBancaireRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpsertInformationPaiementBancaireRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.iban = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.bic = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.titulaireCompte = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.mandatSepaReference = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.dateMandat = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.statut = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.commentaire = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.externalId = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpsertInformationPaiementBancaireRequest {
    return {
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      iban: isSet(object.iban) ? globalThis.String(object.iban) : "",
      bic: isSet(object.bic) ? globalThis.String(object.bic) : "",
      titulaireCompte: isSet(object.titulaireCompte)
        ? globalThis.String(object.titulaireCompte)
        : isSet(object.titulaire_compte)
        ? globalThis.String(object.titulaire_compte)
        : undefined,
      mandatSepaReference: isSet(object.mandatSepaReference)
        ? globalThis.String(object.mandatSepaReference)
        : isSet(object.mandat_sepa_reference)
        ? globalThis.String(object.mandat_sepa_reference)
        : undefined,
      dateMandat: isSet(object.dateMandat)
        ? globalThis.String(object.dateMandat)
        : isSet(object.date_mandat)
        ? globalThis.String(object.date_mandat)
        : undefined,
      statut: isSet(object.statut) ? globalThis.String(object.statut) : undefined,
      commentaire: isSet(object.commentaire) ? globalThis.String(object.commentaire) : undefined,
      externalId: isSet(object.externalId)
        ? globalThis.String(object.externalId)
        : isSet(object.external_id)
        ? globalThis.String(object.external_id)
        : "",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : undefined,
    };
  },

  toJSON(message: UpsertInformationPaiementBancaireRequest): unknown {
    const obj: any = {};
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.iban !== "") {
      obj.iban = message.iban;
    }
    if (message.bic !== "") {
      obj.bic = message.bic;
    }
    if (message.titulaireCompte !== undefined) {
      obj.titulaireCompte = message.titulaireCompte;
    }
    if (message.mandatSepaReference !== undefined) {
      obj.mandatSepaReference = message.mandatSepaReference;
    }
    if (message.dateMandat !== undefined) {
      obj.dateMandat = message.dateMandat;
    }
    if (message.statut !== undefined) {
      obj.statut = message.statut;
    }
    if (message.commentaire !== undefined) {
      obj.commentaire = message.commentaire;
    }
    if (message.externalId !== "") {
      obj.externalId = message.externalId;
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpsertInformationPaiementBancaireRequest>, I>>(
    base?: I,
  ): UpsertInformationPaiementBancaireRequest {
    return UpsertInformationPaiementBancaireRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpsertInformationPaiementBancaireRequest>, I>>(
    object: I,
  ): UpsertInformationPaiementBancaireRequest {
    const message = createBaseUpsertInformationPaiementBancaireRequest();
    message.organisationId = object.organisationId ?? "";
    message.clientId = object.clientId ?? "";
    message.iban = object.iban ?? "";
    message.bic = object.bic ?? "";
    message.titulaireCompte = object.titulaireCompte ?? undefined;
    message.mandatSepaReference = object.mandatSepaReference ?? undefined;
    message.dateMandat = object.dateMandat ?? undefined;
    message.statut = object.statut ?? undefined;
    message.commentaire = object.commentaire ?? undefined;
    message.externalId = object.externalId ?? "";
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

function createBaseDeleteInformationPaiementBancaireRequest(): DeleteInformationPaiementBancaireRequest {
  return { id: "" };
}

export const DeleteInformationPaiementBancaireRequest: MessageFns<DeleteInformationPaiementBancaireRequest> = {
  encode(message: DeleteInformationPaiementBancaireRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteInformationPaiementBancaireRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteInformationPaiementBancaireRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteInformationPaiementBancaireRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: DeleteInformationPaiementBancaireRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteInformationPaiementBancaireRequest>, I>>(
    base?: I,
  ): DeleteInformationPaiementBancaireRequest {
    return DeleteInformationPaiementBancaireRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteInformationPaiementBancaireRequest>, I>>(
    object: I,
  ): DeleteInformationPaiementBancaireRequest {
    const message = createBaseDeleteInformationPaiementBancaireRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseInformationPaiementBancaireResponse(): InformationPaiementBancaireResponse {
  return {
    id: "",
    organisationId: "",
    clientId: "",
    iban: "",
    bic: "",
    titulaireCompte: "",
    mandatSepaReference: "",
    dateMandat: "",
    statut: "",
    commentaire: "",
    externalId: "",
    createdAt: "",
    updatedAt: "",
  };
}

export const InformationPaiementBancaireResponse: MessageFns<InformationPaiementBancaireResponse> = {
  encode(message: InformationPaiementBancaireResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.organisationId !== "") {
      writer.uint32(18).string(message.organisationId);
    }
    if (message.clientId !== "") {
      writer.uint32(26).string(message.clientId);
    }
    if (message.iban !== "") {
      writer.uint32(34).string(message.iban);
    }
    if (message.bic !== "") {
      writer.uint32(42).string(message.bic);
    }
    if (message.titulaireCompte !== "") {
      writer.uint32(50).string(message.titulaireCompte);
    }
    if (message.mandatSepaReference !== "") {
      writer.uint32(58).string(message.mandatSepaReference);
    }
    if (message.dateMandat !== "") {
      writer.uint32(66).string(message.dateMandat);
    }
    if (message.statut !== "") {
      writer.uint32(74).string(message.statut);
    }
    if (message.commentaire !== "") {
      writer.uint32(82).string(message.commentaire);
    }
    if (message.externalId !== "") {
      writer.uint32(90).string(message.externalId);
    }
    if (message.createdAt !== "") {
      writer.uint32(98).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(106).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InformationPaiementBancaireResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInformationPaiementBancaireResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.iban = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.bic = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.titulaireCompte = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.mandatSepaReference = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.dateMandat = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.statut = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.commentaire = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.externalId = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InformationPaiementBancaireResponse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      iban: isSet(object.iban) ? globalThis.String(object.iban) : "",
      bic: isSet(object.bic) ? globalThis.String(object.bic) : "",
      titulaireCompte: isSet(object.titulaireCompte)
        ? globalThis.String(object.titulaireCompte)
        : isSet(object.titulaire_compte)
        ? globalThis.String(object.titulaire_compte)
        : "",
      mandatSepaReference: isSet(object.mandatSepaReference)
        ? globalThis.String(object.mandatSepaReference)
        : isSet(object.mandat_sepa_reference)
        ? globalThis.String(object.mandat_sepa_reference)
        : "",
      dateMandat: isSet(object.dateMandat)
        ? globalThis.String(object.dateMandat)
        : isSet(object.date_mandat)
        ? globalThis.String(object.date_mandat)
        : "",
      statut: isSet(object.statut) ? globalThis.String(object.statut) : "",
      commentaire: isSet(object.commentaire) ? globalThis.String(object.commentaire) : "",
      externalId: isSet(object.externalId)
        ? globalThis.String(object.externalId)
        : isSet(object.external_id)
        ? globalThis.String(object.external_id)
        : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "",
    };
  },

  toJSON(message: InformationPaiementBancaireResponse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.iban !== "") {
      obj.iban = message.iban;
    }
    if (message.bic !== "") {
      obj.bic = message.bic;
    }
    if (message.titulaireCompte !== "") {
      obj.titulaireCompte = message.titulaireCompte;
    }
    if (message.mandatSepaReference !== "") {
      obj.mandatSepaReference = message.mandatSepaReference;
    }
    if (message.dateMandat !== "") {
      obj.dateMandat = message.dateMandat;
    }
    if (message.statut !== "") {
      obj.statut = message.statut;
    }
    if (message.commentaire !== "") {
      obj.commentaire = message.commentaire;
    }
    if (message.externalId !== "") {
      obj.externalId = message.externalId;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InformationPaiementBancaireResponse>, I>>(
    base?: I,
  ): InformationPaiementBancaireResponse {
    return InformationPaiementBancaireResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InformationPaiementBancaireResponse>, I>>(
    object: I,
  ): InformationPaiementBancaireResponse {
    const message = createBaseInformationPaiementBancaireResponse();
    message.id = object.id ?? "";
    message.organisationId = object.organisationId ?? "";
    message.clientId = object.clientId ?? "";
    message.iban = object.iban ?? "";
    message.bic = object.bic ?? "";
    message.titulaireCompte = object.titulaireCompte ?? "";
    message.mandatSepaReference = object.mandatSepaReference ?? "";
    message.dateMandat = object.dateMandat ?? "";
    message.statut = object.statut ?? "";
    message.commentaire = object.commentaire ?? "";
    message.externalId = object.externalId ?? "";
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

function createBaseInformationPaiementBancaireListResponse(): InformationPaiementBancaireListResponse {
  return { items: [], total: 0 };
}

export const InformationPaiementBancaireListResponse: MessageFns<InformationPaiementBancaireListResponse> = {
  encode(message: InformationPaiementBancaireListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      InformationPaiementBancaireResponse.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InformationPaiementBancaireListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInformationPaiementBancaireListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(InformationPaiementBancaireResponse.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InformationPaiementBancaireListResponse {
    return {
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => InformationPaiementBancaireResponse.fromJSON(e))
        : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
    };
  },

  toJSON(message: InformationPaiementBancaireListResponse): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => InformationPaiementBancaireResponse.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InformationPaiementBancaireListResponse>, I>>(
    base?: I,
  ): InformationPaiementBancaireListResponse {
    return InformationPaiementBancaireListResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InformationPaiementBancaireListResponse>, I>>(
    object: I,
  ): InformationPaiementBancaireListResponse {
    const message = createBaseInformationPaiementBancaireListResponse();
    message.items = object.items?.map((e) => InformationPaiementBancaireResponse.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    return message;
  },
};

function createBaseUpsertInformationPaiementBancaireResponse(): UpsertInformationPaiementBancaireResponse {
  return { entity: undefined, created: false };
}

export const UpsertInformationPaiementBancaireResponse: MessageFns<UpsertInformationPaiementBancaireResponse> = {
  encode(message: UpsertInformationPaiementBancaireResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entity !== undefined) {
      InformationPaiementBancaireResponse.encode(message.entity, writer.uint32(10).fork()).join();
    }
    if (message.created !== false) {
      writer.uint32(16).bool(message.created);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpsertInformationPaiementBancaireResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpsertInformationPaiementBancaireResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entity = InformationPaiementBancaireResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.created = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpsertInformationPaiementBancaireResponse {
    return {
      entity: isSet(object.entity) ? InformationPaiementBancaireResponse.fromJSON(object.entity) : undefined,
      created: isSet(object.created) ? globalThis.Boolean(object.created) : false,
    };
  },

  toJSON(message: UpsertInformationPaiementBancaireResponse): unknown {
    const obj: any = {};
    if (message.entity !== undefined) {
      obj.entity = InformationPaiementBancaireResponse.toJSON(message.entity);
    }
    if (message.created !== false) {
      obj.created = message.created;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpsertInformationPaiementBancaireResponse>, I>>(
    base?: I,
  ): UpsertInformationPaiementBancaireResponse {
    return UpsertInformationPaiementBancaireResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpsertInformationPaiementBancaireResponse>, I>>(
    object: I,
  ): UpsertInformationPaiementBancaireResponse {
    const message = createBaseUpsertInformationPaiementBancaireResponse();
    message.entity = (object.entity !== undefined && object.entity !== null)
      ? InformationPaiementBancaireResponse.fromPartial(object.entity)
      : undefined;
    message.created = object.created ?? false;
    return message;
  },
};

function createBaseDeleteResponse(): DeleteResponse {
  return { success: false, message: "" };
}

export const DeleteResponse: MessageFns<DeleteResponse> = {
  encode(message: DeleteResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: DeleteResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteResponse>, I>>(base?: I): DeleteResponse {
    return DeleteResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteResponse>, I>>(object: I): DeleteResponse {
    const message = createBaseDeleteResponse();
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    return message;
  },
};

export type InformationPaiementBancaireServiceService = typeof InformationPaiementBancaireServiceService;
export const InformationPaiementBancaireServiceService = {
  create: {
    path: "/payment_info.InformationPaiementBancaireService/Create",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateInformationPaiementBancaireRequest): Buffer =>
      Buffer.from(CreateInformationPaiementBancaireRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateInformationPaiementBancaireRequest =>
      CreateInformationPaiementBancaireRequest.decode(value),
    responseSerialize: (value: InformationPaiementBancaireResponse): Buffer =>
      Buffer.from(InformationPaiementBancaireResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): InformationPaiementBancaireResponse =>
      InformationPaiementBancaireResponse.decode(value),
  },
  getById: {
    path: "/payment_info.InformationPaiementBancaireService/GetById",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetInformationPaiementBancaireByIdRequest): Buffer =>
      Buffer.from(GetInformationPaiementBancaireByIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetInformationPaiementBancaireByIdRequest =>
      GetInformationPaiementBancaireByIdRequest.decode(value),
    responseSerialize: (value: InformationPaiementBancaireResponse): Buffer =>
      Buffer.from(InformationPaiementBancaireResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): InformationPaiementBancaireResponse =>
      InformationPaiementBancaireResponse.decode(value),
  },
  getByClientId: {
    path: "/payment_info.InformationPaiementBancaireService/GetByClientId",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetInformationPaiementBancaireByClientIdRequest): Buffer =>
      Buffer.from(GetInformationPaiementBancaireByClientIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetInformationPaiementBancaireByClientIdRequest =>
      GetInformationPaiementBancaireByClientIdRequest.decode(value),
    responseSerialize: (value: InformationPaiementBancaireListResponse): Buffer =>
      Buffer.from(InformationPaiementBancaireListResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): InformationPaiementBancaireListResponse =>
      InformationPaiementBancaireListResponse.decode(value),
  },
  getByExternalId: {
    path: "/payment_info.InformationPaiementBancaireService/GetByExternalId",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetInformationPaiementBancaireByExternalIdRequest): Buffer =>
      Buffer.from(GetInformationPaiementBancaireByExternalIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetInformationPaiementBancaireByExternalIdRequest =>
      GetInformationPaiementBancaireByExternalIdRequest.decode(value),
    responseSerialize: (value: InformationPaiementBancaireResponse): Buffer =>
      Buffer.from(InformationPaiementBancaireResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): InformationPaiementBancaireResponse =>
      InformationPaiementBancaireResponse.decode(value),
  },
  update: {
    path: "/payment_info.InformationPaiementBancaireService/Update",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateInformationPaiementBancaireRequest): Buffer =>
      Buffer.from(UpdateInformationPaiementBancaireRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateInformationPaiementBancaireRequest =>
      UpdateInformationPaiementBancaireRequest.decode(value),
    responseSerialize: (value: InformationPaiementBancaireResponse): Buffer =>
      Buffer.from(InformationPaiementBancaireResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): InformationPaiementBancaireResponse =>
      InformationPaiementBancaireResponse.decode(value),
  },
  upsertByExternalId: {
    path: "/payment_info.InformationPaiementBancaireService/UpsertByExternalId",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpsertInformationPaiementBancaireRequest): Buffer =>
      Buffer.from(UpsertInformationPaiementBancaireRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpsertInformationPaiementBancaireRequest =>
      UpsertInformationPaiementBancaireRequest.decode(value),
    responseSerialize: (value: UpsertInformationPaiementBancaireResponse): Buffer =>
      Buffer.from(UpsertInformationPaiementBancaireResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpsertInformationPaiementBancaireResponse =>
      UpsertInformationPaiementBancaireResponse.decode(value),
  },
  delete: {
    path: "/payment_info.InformationPaiementBancaireService/Delete",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeleteInformationPaiementBancaireRequest): Buffer =>
      Buffer.from(DeleteInformationPaiementBancaireRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteInformationPaiementBancaireRequest =>
      DeleteInformationPaiementBancaireRequest.decode(value),
    responseSerialize: (value: DeleteResponse): Buffer => Buffer.from(DeleteResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeleteResponse => DeleteResponse.decode(value),
  },
} as const;

export interface InformationPaiementBancaireServiceServer extends UntypedServiceImplementation {
  create: handleUnaryCall<CreateInformationPaiementBancaireRequest, InformationPaiementBancaireResponse>;
  getById: handleUnaryCall<GetInformationPaiementBancaireByIdRequest, InformationPaiementBancaireResponse>;
  getByClientId: handleUnaryCall<
    GetInformationPaiementBancaireByClientIdRequest,
    InformationPaiementBancaireListResponse
  >;
  getByExternalId: handleUnaryCall<
    GetInformationPaiementBancaireByExternalIdRequest,
    InformationPaiementBancaireResponse
  >;
  update: handleUnaryCall<UpdateInformationPaiementBancaireRequest, InformationPaiementBancaireResponse>;
  upsertByExternalId: handleUnaryCall<
    UpsertInformationPaiementBancaireRequest,
    UpsertInformationPaiementBancaireResponse
  >;
  delete: handleUnaryCall<DeleteInformationPaiementBancaireRequest, DeleteResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
