import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1769426320545 implements MigrationInterface {
    name = 'Init1769426320545'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "stripe_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "societe_id" character varying NOT NULL, "nom" character varying NOT NULL, "stripe_secret_key" character varying, "stripe_publishable_key" character varying, "stripe_webhook_secret" character varying, "is_test_mode" boolean NOT NULL DEFAULT true, "actif" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e2022498b81a00e4c9e5b00f418" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_19c71a553b9b7dc044a792fcb3" ON "stripe_accounts" ("societe_id") `);
        await queryRunner.query(`CREATE TABLE "slimpay_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "societe_id" character varying NOT NULL, "nom" character varying NOT NULL, "app_name" character varying, "app_secret" character varying, "webhook_secret" character varying, "is_sandbox" boolean NOT NULL DEFAULT true, "actif" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_96f339435362540faa6bb92ae12" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_123c04f6575fcb49458e3ffb1f" ON "slimpay_accounts" ("societe_id") `);
        await queryRunner.query(`CREATE TYPE "public"."schedules_provider_enum" AS ENUM('stripe', 'paypal', 'gocardless', 'slimpay', 'multisafepay', 'emerchantpay')`);
        await queryRunner.query(`CREATE TYPE "public"."schedules_frequency_enum" AS ENUM('weekly', 'monthly', 'quarterly', 'yearly')`);
        await queryRunner.query(`CREATE TYPE "public"."schedules_status_enum" AS ENUM('active', 'paused', 'cancelled', 'completed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organisation_id" uuid, "client_id" character varying NOT NULL, "societe_id" character varying NOT NULL, "contrat_id" character varying, "facture_id" character varying, "provider" "public"."schedules_provider_enum" NOT NULL, "provider_account_id" character varying NOT NULL, "provider_subscription_id" character varying, "provider_customer_id" character varying, "amount" numeric(10,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'EUR', "frequency" "public"."schedules_frequency_enum" NOT NULL DEFAULT 'monthly', "status" "public"."schedules_status_enum" NOT NULL DEFAULT 'active', "planned_debit_date" TIMESTAMP, "next_payment_date" TIMESTAMP, "last_payment_date" TIMESTAMP, "start_date" TIMESTAMP NOT NULL, "end_date" TIMESTAMP, "retry_count" integer NOT NULL DEFAULT '0', "max_retries" integer NOT NULL DEFAULT '3', "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7e33fc2ea755a5765e3564e66dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e5e25b01630cda190d295b3570" ON "schedules" ("organisation_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e2b48c798a6f5d7827dd7d714e" ON "schedules" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0854dbfa12ffeb916c6fae897" ON "schedules" ("societe_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2e4f14222fa3ed2ed2dfd345e5" ON "schedules" ("contrat_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7522c162699673cc78c66ea890" ON "schedules" ("facture_id") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_intents_provider_enum" AS ENUM('stripe', 'paypal', 'gocardless', 'slimpay', 'multisafepay', 'emerchantpay')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_intents_status_enum" AS ENUM('pending', 'processing', 'succeeded', 'failed', 'cancelled', 'refunded', 'partially_refunded')`);
        await queryRunner.query(`CREATE TABLE "payment_intents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "schedule_id" uuid, "client_id" character varying NOT NULL, "societe_id" character varying NOT NULL, "facture_id" character varying, "provider" "public"."payment_intents_provider_enum" NOT NULL, "provider_payment_id" character varying, "provider_customer_id" character varying, "amount" numeric(10,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'EUR', "status" "public"."payment_intents_status_enum" NOT NULL DEFAULT 'pending', "failure_reason" character varying, "refunded_amount" numeric(10,2) NOT NULL DEFAULT '0', "metadata" jsonb, "idempotency_key" character varying, "paid_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_27d49f2aad19ee3754bca8f6e11" UNIQUE ("provider_payment_id"), CONSTRAINT "UQ_7716d4bbdda4edfb0c48811920f" UNIQUE ("idempotency_key"), CONSTRAINT "PK_cc99975b98c8001a336976fd018" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bdacd53013f1edc2ce344db5d2" ON "payment_intents" ("schedule_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d5e3f5818e90f719857dd652bf" ON "payment_intents" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_35b650a5b8382ed4394714564e" ON "payment_intents" ("societe_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc3c03acf2a40cac6a026b9840" ON "payment_intents" ("facture_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7716d4bbdda4edfb0c48811920" ON "payment_intents" ("idempotency_key") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_events_provider_enum" AS ENUM('stripe', 'paypal', 'gocardless', 'slimpay', 'multisafepay', 'emerchantpay')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_events_event_type_enum" AS ENUM('payment.created', 'payment.processing', 'payment.succeeded', 'payment.failed', 'payment.cancelled', 'refund.created', 'refund.succeeded', 'refund.failed', 'schedule.created', 'schedule.updated', 'schedule.paused', 'schedule.resumed', 'schedule.cancelled', 'mandate.created', 'mandate.active', 'mandate.failed', 'mandate.cancelled', 'webhook.received', 'webhook.processed', 'webhook.failed')`);
        await queryRunner.query(`CREATE TABLE "payment_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payment_intent_id" uuid, "schedule_id" character varying, "societe_id" character varying NOT NULL, "provider" "public"."payment_events_provider_enum", "event_type" "public"."payment_events_event_type_enum" NOT NULL, "provider_event_id" character varying, "payload" jsonb, "error_message" character varying, "processed" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9f1d16fc78b33e676940a32e8b5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_99e5628c7b9f69c35161d803fa" ON "payment_events" ("payment_intent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_21652ec75c6f7b48977bc8ee27" ON "payment_events" ("schedule_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_725614ecc88ce46de7dc2ee158" ON "payment_events" ("societe_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c30027078754c19e9d5d3afcb4" ON "payment_events" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_4bc808d38b0b93bfe7c0a87093" ON "payment_events" ("created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."portal_payment_session_status_enum" AS ENUM('CREATED', 'ACTIVE', 'REDIRECTED', 'COMPLETED', 'FAILED', 'EXPIRED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."portal_payment_session_psp_provider_enum" AS ENUM('STRIPE', 'PAYPAL', 'GOCARDLESS', 'EMERCHANTPAY', 'SLIMPAY', 'MULTISAFEPAY')`);
        await queryRunner.query(`CREATE TABLE "portal_payment_session" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organisation_id" character varying NOT NULL, "societe_id" character varying NOT NULL, "customer_id" character varying NOT NULL, "contract_id" uuid, "payment_intent_id" character varying, "token_hash" character varying(64) NOT NULL, "token_version" character varying(4) NOT NULL DEFAULT 'v1', "status" "public"."portal_payment_session_status_enum" NOT NULL DEFAULT 'CREATED', "allowed_actions" text NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "max_uses" integer NOT NULL DEFAULT '1', "use_count" integer NOT NULL DEFAULT '0', "idempotency_key_hash" character varying(64), "amount_cents" bigint NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'EUR', "description" character varying(500), "mandate_id" character varying, "rum_masked" character varying(50), "psp_state" character varying(64), "psp_redirect_url" text, "psp_provider" "public"."portal_payment_session_psp_provider_enum", "psp_session_id" character varying(255), "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "last_accessed_at" TIMESTAMP WITH TIME ZONE, "consumed_at" TIMESTAMP WITH TIME ZONE, "revoked_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_ab8928ffa8e1cd4d7f3ec7b0abd" UNIQUE ("token_hash"), CONSTRAINT "PK_cf018f7af39bb145a72aeecc6a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_df64358669da6b59984cd779fb" ON "portal_payment_session" ("organisation_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_22fe0317b160d921a83ef0bc45" ON "portal_payment_session" ("societe_id") `);
        await queryRunner.query(`CREATE INDEX "idx_portal_session_contract" ON "portal_payment_session" ("contract_id") `);
        await queryRunner.query(`CREATE INDEX "idx_portal_session_idempotency" ON "portal_payment_session" ("idempotency_key_hash") `);
        await queryRunner.query(`CREATE INDEX "idx_portal_session_psp_state" ON "portal_payment_session" ("psp_state") `);
        await queryRunner.query(`CREATE INDEX "idx_portal_session_expires" ON "portal_payment_session" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_portal_session_customer" ON "portal_payment_session" ("customer_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."psp_event_inbox_psp_provider_enum" AS ENUM('STRIPE', 'PAYPAL', 'GOCARDLESS', 'EMERCHANTPAY', 'SLIMPAY', 'MULTISAFEPAY')`);
        await queryRunner.query(`CREATE TYPE "public"."psp_event_inbox_status_enum" AS ENUM('RECEIVED', 'VERIFIED', 'REJECTED', 'PROCESSED', 'FAILED', 'DUPLICATE')`);
        await queryRunner.query(`CREATE TABLE "psp_event_inbox" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "psp_provider" "public"."psp_event_inbox_psp_provider_enum" NOT NULL, "psp_event_id" character varying(255) NOT NULL, "psp_event_type" character varying(128), "portal_session_id" uuid, "payment_intent_id" character varying, "raw_payload" text NOT NULL, "signature" character varying(512), "status" "public"."psp_event_inbox_status_enum" NOT NULL DEFAULT 'RECEIVED', "error_message" text, "received_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "verified_at" TIMESTAMP WITH TIME ZONE, "processed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_373aef0f62baf02cc189bda32d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_psp_event_status" ON "psp_event_inbox" ("status", "received_at") `);
        await queryRunner.query(`CREATE INDEX "idx_psp_event_session" ON "psp_event_inbox" ("portal_session_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_psp_event_unique" ON "psp_event_inbox" ("psp_provider", "psp_event_id") `);
        await queryRunner.query(`CREATE TYPE "public"."portal_session_audit_event_type_enum" AS ENUM('SESSION_CREATED', 'SESSION_ACCESSED', 'SESSION_ACTIVATED', 'SESSION_EXPIRED', 'SESSION_CANCELLED', 'REDIRECT_INITIATED', 'REDIRECT_COMPLETED', 'CALLBACK_RECEIVED', 'PAYMENT_INITIATED', 'PAYMENT_COMPLETED', 'PAYMENT_FAILED', 'WEBHOOK_RECEIVED', 'WEBHOOK_VERIFIED', 'WEBHOOK_REJECTED', 'WEBHOOK_PROCESSED', 'TOKEN_VALIDATED', 'TOKEN_REJECTED', 'RATE_LIMIT_HIT', 'REPLAY_DETECTED')`);
        await queryRunner.query(`CREATE TYPE "public"."portal_session_audit_actor_type_enum" AS ENUM('PORTAL_TOKEN', 'AUTHENTICATED_USER', 'ADMIN', 'WEBHOOK', 'SYSTEM')`);
        await queryRunner.query(`CREATE TABLE "portal_session_audit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "portal_session_id" uuid NOT NULL, "event_type" "public"."portal_session_audit_event_type_enum" NOT NULL, "actor_type" "public"."portal_session_audit_actor_type_enum" NOT NULL, "request_id" character varying(64), "correlation_id" character varying(64), "ip_address_hash" character varying(64), "user_agent_hash" character varying(64), "geo_country" character varying(2), "previous_status" character varying(32), "new_status" character varying(32), "data" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a008f18d194e70ea0cd825ea7be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_portal_audit_request_id" ON "portal_session_audit" ("request_id") `);
        await queryRunner.query(`CREATE INDEX "idx_portal_audit_event_type" ON "portal_session_audit" ("event_type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_portal_audit_session" ON "portal_session_audit" ("portal_session_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "paypal_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "societe_id" character varying NOT NULL, "nom" character varying NOT NULL, "client_id" character varying, "client_secret" character varying, "webhook_id" character varying, "is_sandbox" boolean NOT NULL DEFAULT true, "actif" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_08d054255fa00fc33cb971d384f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_147b649b758be18f89c8e7e37a" ON "paypal_accounts" ("societe_id") `);
        await queryRunner.query(`CREATE TABLE "gocardless_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "societe_id" character varying NOT NULL, "nom" character varying NOT NULL, "access_token" character varying, "webhook_secret" character varying, "is_sandbox" boolean NOT NULL DEFAULT true, "actif" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8ab898daa4b630046ff9a020244" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ccc3ddc7b5c2b77a072844b3aa" ON "gocardless_accounts" ("societe_id") `);
        await queryRunner.query(`CREATE TABLE "multisafepay_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "societe_id" character varying NOT NULL, "nom" character varying NOT NULL, "api_key" character varying, "webhook_secret" character varying, "is_sandbox" boolean NOT NULL DEFAULT true, "actif" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e508d7a7b7607129d872d6bac4f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ed6bbe64f116e65111a542f09b" ON "multisafepay_accounts" ("societe_id") `);
        await queryRunner.query(`CREATE TABLE "emerchantpay_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "societe_id" character varying NOT NULL, "nom" character varying NOT NULL, "api_login" character varying, "api_password" character varying, "terminal_token" character varying, "webhook_public_key" text, "is_sandbox" boolean NOT NULL DEFAULT true, "actif" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a6cfd32efadf2df0357226cc107" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a05fe444c59dad93739a696e0b" ON "emerchantpay_accounts" ("societe_id") `);
        await queryRunner.query(`CREATE TYPE "public"."gocardless_mandates_status_enum" AS ENUM('pending_customer_approval', 'pending_submission', 'submitted', 'active', 'suspended_by_payer', 'failed', 'cancelled', 'expired', 'consumed', 'blocked')`);
        await queryRunner.query(`CREATE TABLE "gocardless_mandates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "client_id" character varying NOT NULL, "societe_id" character varying NOT NULL, "mandate_id" character varying NOT NULL, "rum" character varying(35) NOT NULL, "customer_id" character varying, "customer_bank_account_id" character varying, "status" "public"."gocardless_mandates_status_enum" NOT NULL DEFAULT 'pending_customer_approval', "scheme" character varying, "bank_name" character varying, "account_holder_name" character varying, "account_number_ending" character varying, "next_possible_charge_date" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cbde37058cbbd31d014cd9134f1" UNIQUE ("mandate_id"), CONSTRAINT "UQ_838d9c8d693c8371f2b565d2169" UNIQUE ("rum"), CONSTRAINT "PK_a2ad516e665167dda570906c385" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_15e2abcf90de6d944e622f3fdf" ON "gocardless_mandates" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d67b8da0e675f27c52bff1235c" ON "gocardless_mandates" ("societe_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_838d9c8d693c8371f2b565d216" ON "gocardless_mandates" ("rum") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_audit_logs_action_enum" AS ENUM('PAYMENT_CREATED', 'PAYMENT_SUBMITTED', 'PAYMENT_SUCCEEDED', 'PAYMENT_FAILED', 'PAYMENT_CANCELLED', 'PAYMENT_REFUNDED', 'MANDATE_CREATED', 'MANDATE_ACTIVATED', 'MANDATE_CANCELLED', 'SCHEDULE_CREATED', 'SCHEDULE_PAUSED', 'SCHEDULE_RESUMED', 'SCHEDULE_CANCELLED', 'EMISSION_STARTED', 'EMISSION_COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "payment_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "societe_id" character varying NOT NULL, "entity_type" character varying NOT NULL, "entity_id" character varying NOT NULL, "action" "public"."payment_audit_logs_action_enum" NOT NULL, "actor_id" character varying, "actor_type" character varying, "actor_ip" character varying, "previous_state" jsonb, "new_state" jsonb, "metadata" jsonb, "correlation_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1f3c2d028e1ec2c6e889bf3e4b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c939b1ddf7729f5465d229bc9a" ON "payment_audit_logs" ("societe_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9a2256b792cc232638caa9883" ON "payment_audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_e2ea953c01c984ffb685940f94" ON "payment_audit_logs" ("actor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_92417b14841ce65844c42dc1bc" ON "payment_audit_logs" ("correlation_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_eb25738c2010350e686af0e51a" ON "payment_audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_0469ac3dc4fba25b97cc480bd7" ON "payment_audit_logs" ("actor_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_2fec33f5db2e6611c938ab6440" ON "payment_audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0c8a100d7adcf3b1239ebd4bb" ON "payment_audit_logs" ("societe_id", "created_at") `);
        await queryRunner.query(`DROP INDEX "public"."idx_psp_event_status"`);
        await queryRunner.query(`CREATE INDEX "idx_psp_event_status" ON "psp_event_inbox" ("status", "received_at") `);
        await queryRunner.query(`ALTER TABLE "payment_intents" ADD CONSTRAINT "FK_bdacd53013f1edc2ce344db5d23" FOREIGN KEY ("schedule_id") REFERENCES "schedules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_events" ADD CONSTRAINT "FK_99e5628c7b9f69c35161d803fa0" FOREIGN KEY ("payment_intent_id") REFERENCES "payment_intents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "psp_event_inbox" ADD CONSTRAINT "FK_35956ee2c00bb557ff45af68425" FOREIGN KEY ("portal_session_id") REFERENCES "portal_payment_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portal_session_audit" ADD CONSTRAINT "FK_46da69655af03e66bd2899399e5" FOREIGN KEY ("portal_session_id") REFERENCES "portal_payment_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "portal_session_audit" DROP CONSTRAINT "FK_46da69655af03e66bd2899399e5"`);
        await queryRunner.query(`ALTER TABLE "psp_event_inbox" DROP CONSTRAINT "FK_35956ee2c00bb557ff45af68425"`);
        await queryRunner.query(`ALTER TABLE "payment_events" DROP CONSTRAINT "FK_99e5628c7b9f69c35161d803fa0"`);
        await queryRunner.query(`ALTER TABLE "payment_intents" DROP CONSTRAINT "FK_bdacd53013f1edc2ce344db5d23"`);
        await queryRunner.query(`DROP INDEX "public"."idx_psp_event_status"`);
        await queryRunner.query(`CREATE INDEX "idx_psp_event_status" ON "psp_event_inbox" ("status", "received_at") `);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0c8a100d7adcf3b1239ebd4bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2fec33f5db2e6611c938ab6440"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0469ac3dc4fba25b97cc480bd7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb25738c2010350e686af0e51a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92417b14841ce65844c42dc1bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2ea953c01c984ffb685940f94"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9a2256b792cc232638caa9883"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c939b1ddf7729f5465d229bc9a"`);
        await queryRunner.query(`DROP TABLE "payment_audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."payment_audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_838d9c8d693c8371f2b565d216"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d67b8da0e675f27c52bff1235c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15e2abcf90de6d944e622f3fdf"`);
        await queryRunner.query(`DROP TABLE "gocardless_mandates"`);
        await queryRunner.query(`DROP TYPE "public"."gocardless_mandates_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a05fe444c59dad93739a696e0b"`);
        await queryRunner.query(`DROP TABLE "emerchantpay_accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed6bbe64f116e65111a542f09b"`);
        await queryRunner.query(`DROP TABLE "multisafepay_accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccc3ddc7b5c2b77a072844b3aa"`);
        await queryRunner.query(`DROP TABLE "gocardless_accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_147b649b758be18f89c8e7e37a"`);
        await queryRunner.query(`DROP TABLE "paypal_accounts"`);
        await queryRunner.query(`DROP INDEX "public"."idx_portal_audit_session"`);
        await queryRunner.query(`DROP INDEX "public"."idx_portal_audit_event_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_portal_audit_request_id"`);
        await queryRunner.query(`DROP TABLE "portal_session_audit"`);
        await queryRunner.query(`DROP TYPE "public"."portal_session_audit_actor_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."portal_session_audit_event_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_psp_event_unique"`);
        await queryRunner.query(`DROP INDEX "public"."idx_psp_event_session"`);
        await queryRunner.query(`DROP INDEX "public"."idx_psp_event_status"`);
        await queryRunner.query(`DROP TABLE "psp_event_inbox"`);
        await queryRunner.query(`DROP TYPE "public"."psp_event_inbox_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."psp_event_inbox_psp_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_portal_session_customer"`);
        await queryRunner.query(`DROP INDEX "public"."idx_portal_session_expires"`);
        await queryRunner.query(`DROP INDEX "public"."idx_portal_session_psp_state"`);
        await queryRunner.query(`DROP INDEX "public"."idx_portal_session_idempotency"`);
        await queryRunner.query(`DROP INDEX "public"."idx_portal_session_contract"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22fe0317b160d921a83ef0bc45"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df64358669da6b59984cd779fb"`);
        await queryRunner.query(`DROP TABLE "portal_payment_session"`);
        await queryRunner.query(`DROP TYPE "public"."portal_payment_session_psp_provider_enum"`);
        await queryRunner.query(`DROP TYPE "public"."portal_payment_session_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4bc808d38b0b93bfe7c0a87093"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c30027078754c19e9d5d3afcb4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_725614ecc88ce46de7dc2ee158"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21652ec75c6f7b48977bc8ee27"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99e5628c7b9f69c35161d803fa"`);
        await queryRunner.query(`DROP TABLE "payment_events"`);
        await queryRunner.query(`DROP TYPE "public"."payment_events_event_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_events_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7716d4bbdda4edfb0c48811920"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc3c03acf2a40cac6a026b9840"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35b650a5b8382ed4394714564e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5e3f5818e90f719857dd652bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bdacd53013f1edc2ce344db5d2"`);
        await queryRunner.query(`DROP TABLE "payment_intents"`);
        await queryRunner.query(`DROP TYPE "public"."payment_intents_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_intents_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7522c162699673cc78c66ea890"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e4f14222fa3ed2ed2dfd345e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0854dbfa12ffeb916c6fae897"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2b48c798a6f5d7827dd7d714e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5e25b01630cda190d295b3570"`);
        await queryRunner.query(`DROP TABLE "schedules"`);
        await queryRunner.query(`DROP TYPE "public"."schedules_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."schedules_frequency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."schedules_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_123c04f6575fcb49458e3ffb1f"`);
        await queryRunner.query(`DROP TABLE "slimpay_accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19c71a553b9b7dc044a792fcb3"`);
        await queryRunner.query(`DROP TABLE "stripe_accounts"`);
    }

}
