// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: winleadplus/winleadplus.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";

export const protobufPackage = "winleadplus";

export interface WinLeadPlusConfig {
  id: string;
  organisationId: string;
  apiEndpoint: string;
  enabled: boolean;
  syncIntervalMinutes: number;
  lastSyncAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface CreateWinLeadPlusConfigRequest {
  organisationId: string;
  apiEndpoint: string;
  enabled: boolean;
  syncIntervalMinutes: number;
}

export interface UpdateWinLeadPlusConfigRequest {
  id: string;
  apiEndpoint?: string | undefined;
  enabled?: boolean | undefined;
  syncIntervalMinutes?: number | undefined;
}

export interface GetWinLeadPlusConfigRequest {
  organisationId: string;
}

export interface HasWinLeadPlusConfigResponse {
  enabled: boolean;
}

export interface WinLeadPlusMapping {
  id: string;
  organisationId: string;
  winleadplusProspectId: string;
  crmClientId: string;
  crmContratIds: string[];
  lastSyncedAt: string;
}

export interface CreateWinLeadPlusMappingRequest {
  organisationId: string;
  winleadplusProspectId: string;
  crmClientId: string;
  crmContratIds: string[];
}

export interface UpdateWinLeadPlusMappingRequest {
  id: string;
  crmClientId?: string | undefined;
  crmContratIds: string[];
}

export interface GetWinLeadPlusMappingRequest {
  id: string;
}

export interface ListWinLeadPlusMappingsRequest {
  organisationId: string;
  winleadplusProspectId?: string | undefined;
  crmClientId?: string | undefined;
}

export interface ListWinLeadPlusMappingsResponse {
  mappings: WinLeadPlusMapping[];
}

export interface WinLeadPlusSyncLog {
  id: string;
  organisationId: string;
  startedAt: string;
  finishedAt?: string | undefined;
  status: string;
  totalProspects: number;
  created: number;
  updated: number;
  skipped: number;
  errors: string[];
}

export interface GetWinLeadPlusSyncLogRequest {
  id: string;
}

export interface ListWinLeadPlusSyncLogsRequest {
  organisationId: string;
  limit?: number | undefined;
}

export interface ListWinLeadPlusSyncLogsResponse {
  logs: WinLeadPlusSyncLog[];
}

export interface SyncProspectsRequest {
  organisationId: string;
  dryRun: boolean;
}

export interface SyncProspectsResponse {
  success: boolean;
  syncLog: WinLeadPlusSyncLog | undefined;
}

export interface GetSyncStatusRequest {
  organisationId: string;
}

export interface GetSyncStatusResponse {
  isSyncing: boolean;
  currentSyncId?: string | undefined;
  lastSyncAt?: string | undefined;
}

export interface TestConnectionRequest {
  organisationId: string;
  apiEndpoint: string;
}

export interface TestConnectionResponse {
  success: boolean;
  message: string;
}

export interface Empty {
}

function createBaseWinLeadPlusConfig(): WinLeadPlusConfig {
  return {
    id: "",
    organisationId: "",
    apiEndpoint: "",
    enabled: false,
    syncIntervalMinutes: 0,
    lastSyncAt: undefined,
    createdAt: "",
    updatedAt: "",
  };
}

export const WinLeadPlusConfig: MessageFns<WinLeadPlusConfig> = {
  encode(message: WinLeadPlusConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.organisationId !== "") {
      writer.uint32(18).string(message.organisationId);
    }
    if (message.apiEndpoint !== "") {
      writer.uint32(26).string(message.apiEndpoint);
    }
    if (message.enabled !== false) {
      writer.uint32(32).bool(message.enabled);
    }
    if (message.syncIntervalMinutes !== 0) {
      writer.uint32(40).int32(message.syncIntervalMinutes);
    }
    if (message.lastSyncAt !== undefined) {
      writer.uint32(50).string(message.lastSyncAt);
    }
    if (message.createdAt !== "") {
      writer.uint32(58).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(66).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WinLeadPlusConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWinLeadPlusConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.apiEndpoint = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.syncIntervalMinutes = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.lastSyncAt = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WinLeadPlusConfig {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      apiEndpoint: isSet(object.apiEndpoint)
        ? globalThis.String(object.apiEndpoint)
        : isSet(object.api_endpoint)
        ? globalThis.String(object.api_endpoint)
        : "",
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      syncIntervalMinutes: isSet(object.syncIntervalMinutes)
        ? globalThis.Number(object.syncIntervalMinutes)
        : isSet(object.sync_interval_minutes)
        ? globalThis.Number(object.sync_interval_minutes)
        : 0,
      lastSyncAt: isSet(object.lastSyncAt)
        ? globalThis.String(object.lastSyncAt)
        : isSet(object.last_sync_at)
        ? globalThis.String(object.last_sync_at)
        : undefined,
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "",
    };
  },

  toJSON(message: WinLeadPlusConfig): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.apiEndpoint !== "") {
      obj.apiEndpoint = message.apiEndpoint;
    }
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    if (message.syncIntervalMinutes !== 0) {
      obj.syncIntervalMinutes = Math.round(message.syncIntervalMinutes);
    }
    if (message.lastSyncAt !== undefined) {
      obj.lastSyncAt = message.lastSyncAt;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WinLeadPlusConfig>, I>>(base?: I): WinLeadPlusConfig {
    return WinLeadPlusConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WinLeadPlusConfig>, I>>(object: I): WinLeadPlusConfig {
    const message = createBaseWinLeadPlusConfig();
    message.id = object.id ?? "";
    message.organisationId = object.organisationId ?? "";
    message.apiEndpoint = object.apiEndpoint ?? "";
    message.enabled = object.enabled ?? false;
    message.syncIntervalMinutes = object.syncIntervalMinutes ?? 0;
    message.lastSyncAt = object.lastSyncAt ?? undefined;
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

function createBaseCreateWinLeadPlusConfigRequest(): CreateWinLeadPlusConfigRequest {
  return { organisationId: "", apiEndpoint: "", enabled: false, syncIntervalMinutes: 0 };
}

export const CreateWinLeadPlusConfigRequest: MessageFns<CreateWinLeadPlusConfigRequest> = {
  encode(message: CreateWinLeadPlusConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.organisationId !== "") {
      writer.uint32(10).string(message.organisationId);
    }
    if (message.apiEndpoint !== "") {
      writer.uint32(18).string(message.apiEndpoint);
    }
    if (message.enabled !== false) {
      writer.uint32(24).bool(message.enabled);
    }
    if (message.syncIntervalMinutes !== 0) {
      writer.uint32(32).int32(message.syncIntervalMinutes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateWinLeadPlusConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateWinLeadPlusConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.apiEndpoint = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.syncIntervalMinutes = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateWinLeadPlusConfigRequest {
    return {
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      apiEndpoint: isSet(object.apiEndpoint)
        ? globalThis.String(object.apiEndpoint)
        : isSet(object.api_endpoint)
        ? globalThis.String(object.api_endpoint)
        : "",
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      syncIntervalMinutes: isSet(object.syncIntervalMinutes)
        ? globalThis.Number(object.syncIntervalMinutes)
        : isSet(object.sync_interval_minutes)
        ? globalThis.Number(object.sync_interval_minutes)
        : 0,
    };
  },

  toJSON(message: CreateWinLeadPlusConfigRequest): unknown {
    const obj: any = {};
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.apiEndpoint !== "") {
      obj.apiEndpoint = message.apiEndpoint;
    }
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    if (message.syncIntervalMinutes !== 0) {
      obj.syncIntervalMinutes = Math.round(message.syncIntervalMinutes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateWinLeadPlusConfigRequest>, I>>(base?: I): CreateWinLeadPlusConfigRequest {
    return CreateWinLeadPlusConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateWinLeadPlusConfigRequest>, I>>(
    object: I,
  ): CreateWinLeadPlusConfigRequest {
    const message = createBaseCreateWinLeadPlusConfigRequest();
    message.organisationId = object.organisationId ?? "";
    message.apiEndpoint = object.apiEndpoint ?? "";
    message.enabled = object.enabled ?? false;
    message.syncIntervalMinutes = object.syncIntervalMinutes ?? 0;
    return message;
  },
};

function createBaseUpdateWinLeadPlusConfigRequest(): UpdateWinLeadPlusConfigRequest {
  return { id: "", apiEndpoint: undefined, enabled: undefined, syncIntervalMinutes: undefined };
}

export const UpdateWinLeadPlusConfigRequest: MessageFns<UpdateWinLeadPlusConfigRequest> = {
  encode(message: UpdateWinLeadPlusConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.apiEndpoint !== undefined) {
      writer.uint32(18).string(message.apiEndpoint);
    }
    if (message.enabled !== undefined) {
      writer.uint32(24).bool(message.enabled);
    }
    if (message.syncIntervalMinutes !== undefined) {
      writer.uint32(32).int32(message.syncIntervalMinutes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateWinLeadPlusConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateWinLeadPlusConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.apiEndpoint = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.syncIntervalMinutes = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateWinLeadPlusConfigRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      apiEndpoint: isSet(object.apiEndpoint)
        ? globalThis.String(object.apiEndpoint)
        : isSet(object.api_endpoint)
        ? globalThis.String(object.api_endpoint)
        : undefined,
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : undefined,
      syncIntervalMinutes: isSet(object.syncIntervalMinutes)
        ? globalThis.Number(object.syncIntervalMinutes)
        : isSet(object.sync_interval_minutes)
        ? globalThis.Number(object.sync_interval_minutes)
        : undefined,
    };
  },

  toJSON(message: UpdateWinLeadPlusConfigRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.apiEndpoint !== undefined) {
      obj.apiEndpoint = message.apiEndpoint;
    }
    if (message.enabled !== undefined) {
      obj.enabled = message.enabled;
    }
    if (message.syncIntervalMinutes !== undefined) {
      obj.syncIntervalMinutes = Math.round(message.syncIntervalMinutes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateWinLeadPlusConfigRequest>, I>>(base?: I): UpdateWinLeadPlusConfigRequest {
    return UpdateWinLeadPlusConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateWinLeadPlusConfigRequest>, I>>(
    object: I,
  ): UpdateWinLeadPlusConfigRequest {
    const message = createBaseUpdateWinLeadPlusConfigRequest();
    message.id = object.id ?? "";
    message.apiEndpoint = object.apiEndpoint ?? undefined;
    message.enabled = object.enabled ?? undefined;
    message.syncIntervalMinutes = object.syncIntervalMinutes ?? undefined;
    return message;
  },
};

function createBaseGetWinLeadPlusConfigRequest(): GetWinLeadPlusConfigRequest {
  return { organisationId: "" };
}

export const GetWinLeadPlusConfigRequest: MessageFns<GetWinLeadPlusConfigRequest> = {
  encode(message: GetWinLeadPlusConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.organisationId !== "") {
      writer.uint32(10).string(message.organisationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWinLeadPlusConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWinLeadPlusConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetWinLeadPlusConfigRequest {
    return {
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
    };
  },

  toJSON(message: GetWinLeadPlusConfigRequest): unknown {
    const obj: any = {};
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetWinLeadPlusConfigRequest>, I>>(base?: I): GetWinLeadPlusConfigRequest {
    return GetWinLeadPlusConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetWinLeadPlusConfigRequest>, I>>(object: I): GetWinLeadPlusConfigRequest {
    const message = createBaseGetWinLeadPlusConfigRequest();
    message.organisationId = object.organisationId ?? "";
    return message;
  },
};

function createBaseHasWinLeadPlusConfigResponse(): HasWinLeadPlusConfigResponse {
  return { enabled: false };
}

export const HasWinLeadPlusConfigResponse: MessageFns<HasWinLeadPlusConfigResponse> = {
  encode(message: HasWinLeadPlusConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.enabled !== false) {
      writer.uint32(8).bool(message.enabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HasWinLeadPlusConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHasWinLeadPlusConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HasWinLeadPlusConfigResponse {
    return { enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false };
  },

  toJSON(message: HasWinLeadPlusConfigResponse): unknown {
    const obj: any = {};
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HasWinLeadPlusConfigResponse>, I>>(base?: I): HasWinLeadPlusConfigResponse {
    return HasWinLeadPlusConfigResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HasWinLeadPlusConfigResponse>, I>>(object: I): HasWinLeadPlusConfigResponse {
    const message = createBaseHasWinLeadPlusConfigResponse();
    message.enabled = object.enabled ?? false;
    return message;
  },
};

function createBaseWinLeadPlusMapping(): WinLeadPlusMapping {
  return {
    id: "",
    organisationId: "",
    winleadplusProspectId: "",
    crmClientId: "",
    crmContratIds: [],
    lastSyncedAt: "",
  };
}

export const WinLeadPlusMapping: MessageFns<WinLeadPlusMapping> = {
  encode(message: WinLeadPlusMapping, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.organisationId !== "") {
      writer.uint32(18).string(message.organisationId);
    }
    if (message.winleadplusProspectId !== "") {
      writer.uint32(26).string(message.winleadplusProspectId);
    }
    if (message.crmClientId !== "") {
      writer.uint32(34).string(message.crmClientId);
    }
    for (const v of message.crmContratIds) {
      writer.uint32(42).string(v!);
    }
    if (message.lastSyncedAt !== "") {
      writer.uint32(50).string(message.lastSyncedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WinLeadPlusMapping {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWinLeadPlusMapping();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.winleadplusProspectId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.crmClientId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.crmContratIds.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.lastSyncedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WinLeadPlusMapping {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      winleadplusProspectId: isSet(object.winleadplusProspectId)
        ? globalThis.String(object.winleadplusProspectId)
        : isSet(object.winleadplus_prospect_id)
        ? globalThis.String(object.winleadplus_prospect_id)
        : "",
      crmClientId: isSet(object.crmClientId)
        ? globalThis.String(object.crmClientId)
        : isSet(object.crm_client_id)
        ? globalThis.String(object.crm_client_id)
        : "",
      crmContratIds: globalThis.Array.isArray(object?.crmContratIds)
        ? object.crmContratIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.crm_contrat_ids)
        ? object.crm_contrat_ids.map((e: any) => globalThis.String(e))
        : [],
      lastSyncedAt: isSet(object.lastSyncedAt)
        ? globalThis.String(object.lastSyncedAt)
        : isSet(object.last_synced_at)
        ? globalThis.String(object.last_synced_at)
        : "",
    };
  },

  toJSON(message: WinLeadPlusMapping): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.winleadplusProspectId !== "") {
      obj.winleadplusProspectId = message.winleadplusProspectId;
    }
    if (message.crmClientId !== "") {
      obj.crmClientId = message.crmClientId;
    }
    if (message.crmContratIds?.length) {
      obj.crmContratIds = message.crmContratIds;
    }
    if (message.lastSyncedAt !== "") {
      obj.lastSyncedAt = message.lastSyncedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WinLeadPlusMapping>, I>>(base?: I): WinLeadPlusMapping {
    return WinLeadPlusMapping.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WinLeadPlusMapping>, I>>(object: I): WinLeadPlusMapping {
    const message = createBaseWinLeadPlusMapping();
    message.id = object.id ?? "";
    message.organisationId = object.organisationId ?? "";
    message.winleadplusProspectId = object.winleadplusProspectId ?? "";
    message.crmClientId = object.crmClientId ?? "";
    message.crmContratIds = object.crmContratIds?.map((e) => e) || [];
    message.lastSyncedAt = object.lastSyncedAt ?? "";
    return message;
  },
};

function createBaseCreateWinLeadPlusMappingRequest(): CreateWinLeadPlusMappingRequest {
  return { organisationId: "", winleadplusProspectId: "", crmClientId: "", crmContratIds: [] };
}

export const CreateWinLeadPlusMappingRequest: MessageFns<CreateWinLeadPlusMappingRequest> = {
  encode(message: CreateWinLeadPlusMappingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.organisationId !== "") {
      writer.uint32(10).string(message.organisationId);
    }
    if (message.winleadplusProspectId !== "") {
      writer.uint32(18).string(message.winleadplusProspectId);
    }
    if (message.crmClientId !== "") {
      writer.uint32(26).string(message.crmClientId);
    }
    for (const v of message.crmContratIds) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateWinLeadPlusMappingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateWinLeadPlusMappingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.winleadplusProspectId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.crmClientId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.crmContratIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateWinLeadPlusMappingRequest {
    return {
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      winleadplusProspectId: isSet(object.winleadplusProspectId)
        ? globalThis.String(object.winleadplusProspectId)
        : isSet(object.winleadplus_prospect_id)
        ? globalThis.String(object.winleadplus_prospect_id)
        : "",
      crmClientId: isSet(object.crmClientId)
        ? globalThis.String(object.crmClientId)
        : isSet(object.crm_client_id)
        ? globalThis.String(object.crm_client_id)
        : "",
      crmContratIds: globalThis.Array.isArray(object?.crmContratIds)
        ? object.crmContratIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.crm_contrat_ids)
        ? object.crm_contrat_ids.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: CreateWinLeadPlusMappingRequest): unknown {
    const obj: any = {};
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.winleadplusProspectId !== "") {
      obj.winleadplusProspectId = message.winleadplusProspectId;
    }
    if (message.crmClientId !== "") {
      obj.crmClientId = message.crmClientId;
    }
    if (message.crmContratIds?.length) {
      obj.crmContratIds = message.crmContratIds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateWinLeadPlusMappingRequest>, I>>(base?: I): CreateWinLeadPlusMappingRequest {
    return CreateWinLeadPlusMappingRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateWinLeadPlusMappingRequest>, I>>(
    object: I,
  ): CreateWinLeadPlusMappingRequest {
    const message = createBaseCreateWinLeadPlusMappingRequest();
    message.organisationId = object.organisationId ?? "";
    message.winleadplusProspectId = object.winleadplusProspectId ?? "";
    message.crmClientId = object.crmClientId ?? "";
    message.crmContratIds = object.crmContratIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseUpdateWinLeadPlusMappingRequest(): UpdateWinLeadPlusMappingRequest {
  return { id: "", crmClientId: undefined, crmContratIds: [] };
}

export const UpdateWinLeadPlusMappingRequest: MessageFns<UpdateWinLeadPlusMappingRequest> = {
  encode(message: UpdateWinLeadPlusMappingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.crmClientId !== undefined) {
      writer.uint32(18).string(message.crmClientId);
    }
    for (const v of message.crmContratIds) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateWinLeadPlusMappingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateWinLeadPlusMappingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.crmClientId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.crmContratIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateWinLeadPlusMappingRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      crmClientId: isSet(object.crmClientId)
        ? globalThis.String(object.crmClientId)
        : isSet(object.crm_client_id)
        ? globalThis.String(object.crm_client_id)
        : undefined,
      crmContratIds: globalThis.Array.isArray(object?.crmContratIds)
        ? object.crmContratIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.crm_contrat_ids)
        ? object.crm_contrat_ids.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: UpdateWinLeadPlusMappingRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.crmClientId !== undefined) {
      obj.crmClientId = message.crmClientId;
    }
    if (message.crmContratIds?.length) {
      obj.crmContratIds = message.crmContratIds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateWinLeadPlusMappingRequest>, I>>(base?: I): UpdateWinLeadPlusMappingRequest {
    return UpdateWinLeadPlusMappingRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateWinLeadPlusMappingRequest>, I>>(
    object: I,
  ): UpdateWinLeadPlusMappingRequest {
    const message = createBaseUpdateWinLeadPlusMappingRequest();
    message.id = object.id ?? "";
    message.crmClientId = object.crmClientId ?? undefined;
    message.crmContratIds = object.crmContratIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetWinLeadPlusMappingRequest(): GetWinLeadPlusMappingRequest {
  return { id: "" };
}

export const GetWinLeadPlusMappingRequest: MessageFns<GetWinLeadPlusMappingRequest> = {
  encode(message: GetWinLeadPlusMappingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWinLeadPlusMappingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWinLeadPlusMappingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetWinLeadPlusMappingRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetWinLeadPlusMappingRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetWinLeadPlusMappingRequest>, I>>(base?: I): GetWinLeadPlusMappingRequest {
    return GetWinLeadPlusMappingRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetWinLeadPlusMappingRequest>, I>>(object: I): GetWinLeadPlusMappingRequest {
    const message = createBaseGetWinLeadPlusMappingRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseListWinLeadPlusMappingsRequest(): ListWinLeadPlusMappingsRequest {
  return { organisationId: "", winleadplusProspectId: undefined, crmClientId: undefined };
}

export const ListWinLeadPlusMappingsRequest: MessageFns<ListWinLeadPlusMappingsRequest> = {
  encode(message: ListWinLeadPlusMappingsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.organisationId !== "") {
      writer.uint32(10).string(message.organisationId);
    }
    if (message.winleadplusProspectId !== undefined) {
      writer.uint32(18).string(message.winleadplusProspectId);
    }
    if (message.crmClientId !== undefined) {
      writer.uint32(26).string(message.crmClientId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListWinLeadPlusMappingsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListWinLeadPlusMappingsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.winleadplusProspectId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.crmClientId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListWinLeadPlusMappingsRequest {
    return {
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      winleadplusProspectId: isSet(object.winleadplusProspectId)
        ? globalThis.String(object.winleadplusProspectId)
        : isSet(object.winleadplus_prospect_id)
        ? globalThis.String(object.winleadplus_prospect_id)
        : undefined,
      crmClientId: isSet(object.crmClientId)
        ? globalThis.String(object.crmClientId)
        : isSet(object.crm_client_id)
        ? globalThis.String(object.crm_client_id)
        : undefined,
    };
  },

  toJSON(message: ListWinLeadPlusMappingsRequest): unknown {
    const obj: any = {};
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.winleadplusProspectId !== undefined) {
      obj.winleadplusProspectId = message.winleadplusProspectId;
    }
    if (message.crmClientId !== undefined) {
      obj.crmClientId = message.crmClientId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListWinLeadPlusMappingsRequest>, I>>(base?: I): ListWinLeadPlusMappingsRequest {
    return ListWinLeadPlusMappingsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListWinLeadPlusMappingsRequest>, I>>(
    object: I,
  ): ListWinLeadPlusMappingsRequest {
    const message = createBaseListWinLeadPlusMappingsRequest();
    message.organisationId = object.organisationId ?? "";
    message.winleadplusProspectId = object.winleadplusProspectId ?? undefined;
    message.crmClientId = object.crmClientId ?? undefined;
    return message;
  },
};

function createBaseListWinLeadPlusMappingsResponse(): ListWinLeadPlusMappingsResponse {
  return { mappings: [] };
}

export const ListWinLeadPlusMappingsResponse: MessageFns<ListWinLeadPlusMappingsResponse> = {
  encode(message: ListWinLeadPlusMappingsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.mappings) {
      WinLeadPlusMapping.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListWinLeadPlusMappingsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListWinLeadPlusMappingsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.mappings.push(WinLeadPlusMapping.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListWinLeadPlusMappingsResponse {
    return {
      mappings: globalThis.Array.isArray(object?.mappings)
        ? object.mappings.map((e: any) => WinLeadPlusMapping.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListWinLeadPlusMappingsResponse): unknown {
    const obj: any = {};
    if (message.mappings?.length) {
      obj.mappings = message.mappings.map((e) => WinLeadPlusMapping.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListWinLeadPlusMappingsResponse>, I>>(base?: I): ListWinLeadPlusMappingsResponse {
    return ListWinLeadPlusMappingsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListWinLeadPlusMappingsResponse>, I>>(
    object: I,
  ): ListWinLeadPlusMappingsResponse {
    const message = createBaseListWinLeadPlusMappingsResponse();
    message.mappings = object.mappings?.map((e) => WinLeadPlusMapping.fromPartial(e)) || [];
    return message;
  },
};

function createBaseWinLeadPlusSyncLog(): WinLeadPlusSyncLog {
  return {
    id: "",
    organisationId: "",
    startedAt: "",
    finishedAt: undefined,
    status: "",
    totalProspects: 0,
    created: 0,
    updated: 0,
    skipped: 0,
    errors: [],
  };
}

export const WinLeadPlusSyncLog: MessageFns<WinLeadPlusSyncLog> = {
  encode(message: WinLeadPlusSyncLog, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.organisationId !== "") {
      writer.uint32(18).string(message.organisationId);
    }
    if (message.startedAt !== "") {
      writer.uint32(26).string(message.startedAt);
    }
    if (message.finishedAt !== undefined) {
      writer.uint32(34).string(message.finishedAt);
    }
    if (message.status !== "") {
      writer.uint32(42).string(message.status);
    }
    if (message.totalProspects !== 0) {
      writer.uint32(48).int32(message.totalProspects);
    }
    if (message.created !== 0) {
      writer.uint32(56).int32(message.created);
    }
    if (message.updated !== 0) {
      writer.uint32(64).int32(message.updated);
    }
    if (message.skipped !== 0) {
      writer.uint32(72).int32(message.skipped);
    }
    for (const v of message.errors) {
      writer.uint32(82).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WinLeadPlusSyncLog {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWinLeadPlusSyncLog();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.startedAt = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.finishedAt = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.totalProspects = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.created = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.updated = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.skipped = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.errors.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WinLeadPlusSyncLog {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      startedAt: isSet(object.startedAt)
        ? globalThis.String(object.startedAt)
        : isSet(object.started_at)
        ? globalThis.String(object.started_at)
        : "",
      finishedAt: isSet(object.finishedAt)
        ? globalThis.String(object.finishedAt)
        : isSet(object.finished_at)
        ? globalThis.String(object.finished_at)
        : undefined,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      totalProspects: isSet(object.totalProspects)
        ? globalThis.Number(object.totalProspects)
        : isSet(object.total_prospects)
        ? globalThis.Number(object.total_prospects)
        : 0,
      created: isSet(object.created) ? globalThis.Number(object.created) : 0,
      updated: isSet(object.updated) ? globalThis.Number(object.updated) : 0,
      skipped: isSet(object.skipped) ? globalThis.Number(object.skipped) : 0,
      errors: globalThis.Array.isArray(object?.errors)
        ? object.errors.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: WinLeadPlusSyncLog): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.startedAt !== "") {
      obj.startedAt = message.startedAt;
    }
    if (message.finishedAt !== undefined) {
      obj.finishedAt = message.finishedAt;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.totalProspects !== 0) {
      obj.totalProspects = Math.round(message.totalProspects);
    }
    if (message.created !== 0) {
      obj.created = Math.round(message.created);
    }
    if (message.updated !== 0) {
      obj.updated = Math.round(message.updated);
    }
    if (message.skipped !== 0) {
      obj.skipped = Math.round(message.skipped);
    }
    if (message.errors?.length) {
      obj.errors = message.errors;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WinLeadPlusSyncLog>, I>>(base?: I): WinLeadPlusSyncLog {
    return WinLeadPlusSyncLog.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WinLeadPlusSyncLog>, I>>(object: I): WinLeadPlusSyncLog {
    const message = createBaseWinLeadPlusSyncLog();
    message.id = object.id ?? "";
    message.organisationId = object.organisationId ?? "";
    message.startedAt = object.startedAt ?? "";
    message.finishedAt = object.finishedAt ?? undefined;
    message.status = object.status ?? "";
    message.totalProspects = object.totalProspects ?? 0;
    message.created = object.created ?? 0;
    message.updated = object.updated ?? 0;
    message.skipped = object.skipped ?? 0;
    message.errors = object.errors?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetWinLeadPlusSyncLogRequest(): GetWinLeadPlusSyncLogRequest {
  return { id: "" };
}

export const GetWinLeadPlusSyncLogRequest: MessageFns<GetWinLeadPlusSyncLogRequest> = {
  encode(message: GetWinLeadPlusSyncLogRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWinLeadPlusSyncLogRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWinLeadPlusSyncLogRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetWinLeadPlusSyncLogRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetWinLeadPlusSyncLogRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetWinLeadPlusSyncLogRequest>, I>>(base?: I): GetWinLeadPlusSyncLogRequest {
    return GetWinLeadPlusSyncLogRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetWinLeadPlusSyncLogRequest>, I>>(object: I): GetWinLeadPlusSyncLogRequest {
    const message = createBaseGetWinLeadPlusSyncLogRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseListWinLeadPlusSyncLogsRequest(): ListWinLeadPlusSyncLogsRequest {
  return { organisationId: "", limit: undefined };
}

export const ListWinLeadPlusSyncLogsRequest: MessageFns<ListWinLeadPlusSyncLogsRequest> = {
  encode(message: ListWinLeadPlusSyncLogsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.organisationId !== "") {
      writer.uint32(10).string(message.organisationId);
    }
    if (message.limit !== undefined) {
      writer.uint32(16).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListWinLeadPlusSyncLogsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListWinLeadPlusSyncLogsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListWinLeadPlusSyncLogsRequest {
    return {
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : undefined,
    };
  },

  toJSON(message: ListWinLeadPlusSyncLogsRequest): unknown {
    const obj: any = {};
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.limit !== undefined) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListWinLeadPlusSyncLogsRequest>, I>>(base?: I): ListWinLeadPlusSyncLogsRequest {
    return ListWinLeadPlusSyncLogsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListWinLeadPlusSyncLogsRequest>, I>>(
    object: I,
  ): ListWinLeadPlusSyncLogsRequest {
    const message = createBaseListWinLeadPlusSyncLogsRequest();
    message.organisationId = object.organisationId ?? "";
    message.limit = object.limit ?? undefined;
    return message;
  },
};

function createBaseListWinLeadPlusSyncLogsResponse(): ListWinLeadPlusSyncLogsResponse {
  return { logs: [] };
}

export const ListWinLeadPlusSyncLogsResponse: MessageFns<ListWinLeadPlusSyncLogsResponse> = {
  encode(message: ListWinLeadPlusSyncLogsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.logs) {
      WinLeadPlusSyncLog.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListWinLeadPlusSyncLogsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListWinLeadPlusSyncLogsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.logs.push(WinLeadPlusSyncLog.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListWinLeadPlusSyncLogsResponse {
    return {
      logs: globalThis.Array.isArray(object?.logs) ? object.logs.map((e: any) => WinLeadPlusSyncLog.fromJSON(e)) : [],
    };
  },

  toJSON(message: ListWinLeadPlusSyncLogsResponse): unknown {
    const obj: any = {};
    if (message.logs?.length) {
      obj.logs = message.logs.map((e) => WinLeadPlusSyncLog.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListWinLeadPlusSyncLogsResponse>, I>>(base?: I): ListWinLeadPlusSyncLogsResponse {
    return ListWinLeadPlusSyncLogsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListWinLeadPlusSyncLogsResponse>, I>>(
    object: I,
  ): ListWinLeadPlusSyncLogsResponse {
    const message = createBaseListWinLeadPlusSyncLogsResponse();
    message.logs = object.logs?.map((e) => WinLeadPlusSyncLog.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSyncProspectsRequest(): SyncProspectsRequest {
  return { organisationId: "", dryRun: false };
}

export const SyncProspectsRequest: MessageFns<SyncProspectsRequest> = {
  encode(message: SyncProspectsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.organisationId !== "") {
      writer.uint32(10).string(message.organisationId);
    }
    if (message.dryRun !== false) {
      writer.uint32(16).bool(message.dryRun);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncProspectsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncProspectsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.dryRun = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncProspectsRequest {
    return {
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      dryRun: isSet(object.dryRun)
        ? globalThis.Boolean(object.dryRun)
        : isSet(object.dry_run)
        ? globalThis.Boolean(object.dry_run)
        : false,
    };
  },

  toJSON(message: SyncProspectsRequest): unknown {
    const obj: any = {};
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.dryRun !== false) {
      obj.dryRun = message.dryRun;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncProspectsRequest>, I>>(base?: I): SyncProspectsRequest {
    return SyncProspectsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncProspectsRequest>, I>>(object: I): SyncProspectsRequest {
    const message = createBaseSyncProspectsRequest();
    message.organisationId = object.organisationId ?? "";
    message.dryRun = object.dryRun ?? false;
    return message;
  },
};

function createBaseSyncProspectsResponse(): SyncProspectsResponse {
  return { success: false, syncLog: undefined };
}

export const SyncProspectsResponse: MessageFns<SyncProspectsResponse> = {
  encode(message: SyncProspectsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.syncLog !== undefined) {
      WinLeadPlusSyncLog.encode(message.syncLog, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncProspectsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncProspectsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.syncLog = WinLeadPlusSyncLog.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncProspectsResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      syncLog: isSet(object.syncLog)
        ? WinLeadPlusSyncLog.fromJSON(object.syncLog)
        : isSet(object.sync_log)
        ? WinLeadPlusSyncLog.fromJSON(object.sync_log)
        : undefined,
    };
  },

  toJSON(message: SyncProspectsResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.syncLog !== undefined) {
      obj.syncLog = WinLeadPlusSyncLog.toJSON(message.syncLog);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncProspectsResponse>, I>>(base?: I): SyncProspectsResponse {
    return SyncProspectsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncProspectsResponse>, I>>(object: I): SyncProspectsResponse {
    const message = createBaseSyncProspectsResponse();
    message.success = object.success ?? false;
    message.syncLog = (object.syncLog !== undefined && object.syncLog !== null)
      ? WinLeadPlusSyncLog.fromPartial(object.syncLog)
      : undefined;
    return message;
  },
};

function createBaseGetSyncStatusRequest(): GetSyncStatusRequest {
  return { organisationId: "" };
}

export const GetSyncStatusRequest: MessageFns<GetSyncStatusRequest> = {
  encode(message: GetSyncStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.organisationId !== "") {
      writer.uint32(10).string(message.organisationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSyncStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSyncStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSyncStatusRequest {
    return {
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
    };
  },

  toJSON(message: GetSyncStatusRequest): unknown {
    const obj: any = {};
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSyncStatusRequest>, I>>(base?: I): GetSyncStatusRequest {
    return GetSyncStatusRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSyncStatusRequest>, I>>(object: I): GetSyncStatusRequest {
    const message = createBaseGetSyncStatusRequest();
    message.organisationId = object.organisationId ?? "";
    return message;
  },
};

function createBaseGetSyncStatusResponse(): GetSyncStatusResponse {
  return { isSyncing: false, currentSyncId: undefined, lastSyncAt: undefined };
}

export const GetSyncStatusResponse: MessageFns<GetSyncStatusResponse> = {
  encode(message: GetSyncStatusResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isSyncing !== false) {
      writer.uint32(8).bool(message.isSyncing);
    }
    if (message.currentSyncId !== undefined) {
      writer.uint32(18).string(message.currentSyncId);
    }
    if (message.lastSyncAt !== undefined) {
      writer.uint32(26).string(message.lastSyncAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSyncStatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSyncStatusResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isSyncing = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.currentSyncId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lastSyncAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSyncStatusResponse {
    return {
      isSyncing: isSet(object.isSyncing)
        ? globalThis.Boolean(object.isSyncing)
        : isSet(object.is_syncing)
        ? globalThis.Boolean(object.is_syncing)
        : false,
      currentSyncId: isSet(object.currentSyncId)
        ? globalThis.String(object.currentSyncId)
        : isSet(object.current_sync_id)
        ? globalThis.String(object.current_sync_id)
        : undefined,
      lastSyncAt: isSet(object.lastSyncAt)
        ? globalThis.String(object.lastSyncAt)
        : isSet(object.last_sync_at)
        ? globalThis.String(object.last_sync_at)
        : undefined,
    };
  },

  toJSON(message: GetSyncStatusResponse): unknown {
    const obj: any = {};
    if (message.isSyncing !== false) {
      obj.isSyncing = message.isSyncing;
    }
    if (message.currentSyncId !== undefined) {
      obj.currentSyncId = message.currentSyncId;
    }
    if (message.lastSyncAt !== undefined) {
      obj.lastSyncAt = message.lastSyncAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSyncStatusResponse>, I>>(base?: I): GetSyncStatusResponse {
    return GetSyncStatusResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSyncStatusResponse>, I>>(object: I): GetSyncStatusResponse {
    const message = createBaseGetSyncStatusResponse();
    message.isSyncing = object.isSyncing ?? false;
    message.currentSyncId = object.currentSyncId ?? undefined;
    message.lastSyncAt = object.lastSyncAt ?? undefined;
    return message;
  },
};

function createBaseTestConnectionRequest(): TestConnectionRequest {
  return { organisationId: "", apiEndpoint: "" };
}

export const TestConnectionRequest: MessageFns<TestConnectionRequest> = {
  encode(message: TestConnectionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.organisationId !== "") {
      writer.uint32(10).string(message.organisationId);
    }
    if (message.apiEndpoint !== "") {
      writer.uint32(18).string(message.apiEndpoint);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TestConnectionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTestConnectionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.organisationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.apiEndpoint = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TestConnectionRequest {
    return {
      organisationId: isSet(object.organisationId)
        ? globalThis.String(object.organisationId)
        : isSet(object.organisation_id)
        ? globalThis.String(object.organisation_id)
        : "",
      apiEndpoint: isSet(object.apiEndpoint)
        ? globalThis.String(object.apiEndpoint)
        : isSet(object.api_endpoint)
        ? globalThis.String(object.api_endpoint)
        : "",
    };
  },

  toJSON(message: TestConnectionRequest): unknown {
    const obj: any = {};
    if (message.organisationId !== "") {
      obj.organisationId = message.organisationId;
    }
    if (message.apiEndpoint !== "") {
      obj.apiEndpoint = message.apiEndpoint;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TestConnectionRequest>, I>>(base?: I): TestConnectionRequest {
    return TestConnectionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TestConnectionRequest>, I>>(object: I): TestConnectionRequest {
    const message = createBaseTestConnectionRequest();
    message.organisationId = object.organisationId ?? "";
    message.apiEndpoint = object.apiEndpoint ?? "";
    return message;
  },
};

function createBaseTestConnectionResponse(): TestConnectionResponse {
  return { success: false, message: "" };
}

export const TestConnectionResponse: MessageFns<TestConnectionResponse> = {
  encode(message: TestConnectionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TestConnectionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTestConnectionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TestConnectionResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: TestConnectionResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TestConnectionResponse>, I>>(base?: I): TestConnectionResponse {
    return TestConnectionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TestConnectionResponse>, I>>(object: I): TestConnectionResponse {
    const message = createBaseTestConnectionResponse();
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

export type WinLeadPlusSyncServiceService = typeof WinLeadPlusSyncServiceService;
export const WinLeadPlusSyncServiceService = {
  syncProspects: {
    path: "/winleadplus.WinLeadPlusSyncService/SyncProspects",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SyncProspectsRequest): Buffer => Buffer.from(SyncProspectsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SyncProspectsRequest => SyncProspectsRequest.decode(value),
    responseSerialize: (value: SyncProspectsResponse): Buffer =>
      Buffer.from(SyncProspectsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SyncProspectsResponse => SyncProspectsResponse.decode(value),
  },
  getSyncStatus: {
    path: "/winleadplus.WinLeadPlusSyncService/GetSyncStatus",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetSyncStatusRequest): Buffer => Buffer.from(GetSyncStatusRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetSyncStatusRequest => GetSyncStatusRequest.decode(value),
    responseSerialize: (value: GetSyncStatusResponse): Buffer =>
      Buffer.from(GetSyncStatusResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetSyncStatusResponse => GetSyncStatusResponse.decode(value),
  },
  getSyncLogs: {
    path: "/winleadplus.WinLeadPlusSyncService/GetSyncLogs",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ListWinLeadPlusSyncLogsRequest): Buffer =>
      Buffer.from(ListWinLeadPlusSyncLogsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListWinLeadPlusSyncLogsRequest => ListWinLeadPlusSyncLogsRequest.decode(value),
    responseSerialize: (value: ListWinLeadPlusSyncLogsResponse): Buffer =>
      Buffer.from(ListWinLeadPlusSyncLogsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListWinLeadPlusSyncLogsResponse =>
      ListWinLeadPlusSyncLogsResponse.decode(value),
  },
  testConnection: {
    path: "/winleadplus.WinLeadPlusSyncService/TestConnection",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: TestConnectionRequest): Buffer =>
      Buffer.from(TestConnectionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): TestConnectionRequest => TestConnectionRequest.decode(value),
    responseSerialize: (value: TestConnectionResponse): Buffer =>
      Buffer.from(TestConnectionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): TestConnectionResponse => TestConnectionResponse.decode(value),
  },
  getConfig: {
    path: "/winleadplus.WinLeadPlusSyncService/GetConfig",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetWinLeadPlusConfigRequest): Buffer =>
      Buffer.from(GetWinLeadPlusConfigRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetWinLeadPlusConfigRequest => GetWinLeadPlusConfigRequest.decode(value),
    responseSerialize: (value: WinLeadPlusConfig): Buffer => Buffer.from(WinLeadPlusConfig.encode(value).finish()),
    responseDeserialize: (value: Buffer): WinLeadPlusConfig => WinLeadPlusConfig.decode(value),
  },
  saveConfig: {
    path: "/winleadplus.WinLeadPlusSyncService/SaveConfig",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateWinLeadPlusConfigRequest): Buffer =>
      Buffer.from(UpdateWinLeadPlusConfigRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateWinLeadPlusConfigRequest => UpdateWinLeadPlusConfigRequest.decode(value),
    responseSerialize: (value: WinLeadPlusConfig): Buffer => Buffer.from(WinLeadPlusConfig.encode(value).finish()),
    responseDeserialize: (value: Buffer): WinLeadPlusConfig => WinLeadPlusConfig.decode(value),
  },
  hasConfig: {
    path: "/winleadplus.WinLeadPlusSyncService/HasConfig",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetWinLeadPlusConfigRequest): Buffer =>
      Buffer.from(GetWinLeadPlusConfigRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetWinLeadPlusConfigRequest => GetWinLeadPlusConfigRequest.decode(value),
    responseSerialize: (value: HasWinLeadPlusConfigResponse): Buffer =>
      Buffer.from(HasWinLeadPlusConfigResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HasWinLeadPlusConfigResponse => HasWinLeadPlusConfigResponse.decode(value),
  },
} as const;

export interface WinLeadPlusSyncServiceServer extends UntypedServiceImplementation {
  syncProspects: handleUnaryCall<SyncProspectsRequest, SyncProspectsResponse>;
  getSyncStatus: handleUnaryCall<GetSyncStatusRequest, GetSyncStatusResponse>;
  getSyncLogs: handleUnaryCall<ListWinLeadPlusSyncLogsRequest, ListWinLeadPlusSyncLogsResponse>;
  testConnection: handleUnaryCall<TestConnectionRequest, TestConnectionResponse>;
  getConfig: handleUnaryCall<GetWinLeadPlusConfigRequest, WinLeadPlusConfig>;
  saveConfig: handleUnaryCall<UpdateWinLeadPlusConfigRequest, WinLeadPlusConfig>;
  hasConfig: handleUnaryCall<GetWinLeadPlusConfigRequest, HasWinLeadPlusConfigResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
