// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               unknown
// source: organisations/organisations.proto

/* eslint-disable */

export interface Organisation {
  id: string;
  nom: string;
  description: string;
  siret: string;
  adresse: string;
  telephone: string;
  email: string;
  actif: boolean;
  etat: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateOrganisationRequest {
  /** Optional: if provided, use this ID instead of generating one */
  id: string;
  nom: string;
  description: string;
  siret: string;
  adresse: string;
  telephone: string;
  email: string;
  actif: boolean;
}

export interface KeycloakUser {
  sub: string;
  email: string;
  givenName: string;
  familyName: string;
  preferredUsername: string;
  name: string;
}

export interface CreateOrganisationWithOwnerRequest {
  nom: string;
  description: string;
  siret: string;
  adresse: string;
  telephone: string;
  email: string;
  actif: boolean;
  keycloakUser?: KeycloakUser | undefined;
}

export interface Utilisateur {
  id: string;
  keycloakId: string;
  nom: string;
  prenom: string;
  email: string;
}

export interface MembreOrganisation {
  id: string;
  roleId: string;
  etat: string;
}

export interface OrganisationWithOwner {
  organisation?: Organisation | undefined;
  utilisateur?: Utilisateur | undefined;
  membre?: MembreOrganisation | undefined;
}

export interface UpdateOrganisationRequest {
  id: string;
  nom: string;
  description: string;
  siret: string;
  adresse: string;
  telephone: string;
  email: string;
  actif: boolean;
  etat: string;
}

export interface GetOrganisationRequest {
  id: string;
}

export interface ListOrganisationRequest {
  search: string;
  actif: boolean;
  pagination?: Pagination | undefined;
}

export interface ListOrganisationResponse {
  organisations: Organisation[];
  pagination?: PaginationResult | undefined;
}

export interface DeleteOrganisationRequest {
  id: string;
}

export interface Societe {
  id: string;
  organisationId: string;
  raisonSociale: string;
  siren: string;
  numeroTva: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateSocieteRequest {
  organisationId: string;
  raisonSociale: string;
  siren: string;
  numeroTva: string;
}

export interface UpdateSocieteRequest {
  id: string;
  raisonSociale: string;
  siren: string;
  numeroTva: string;
}

export interface GetSocieteRequest {
  id: string;
}

export interface ListSocieteByOrganisationRequest {
  organisationId: string;
  pagination?: Pagination | undefined;
}

export interface ListSocieteRequest {
  search: string;
  pagination?: Pagination | undefined;
}

export interface ListSocieteResponse {
  societes: Societe[];
  pagination?: PaginationResult | undefined;
}

export interface DeleteSocieteRequest {
  id: string;
}

export interface StatutPartenaire {
  id: string;
  code: string;
  nom: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateStatutPartenaireRequest {
  code: string;
  nom: string;
  description: string;
}

export interface UpdateStatutPartenaireRequest {
  id: string;
  code: string;
  nom: string;
  description: string;
}

export interface GetStatutPartenaireRequest {
  id: string;
}

export interface GetStatutPartenaireByCodeRequest {
  code: string;
}

export interface ListStatutPartenaireRequest {
  pagination?: Pagination | undefined;
}

export interface ListStatutPartenaireResponse {
  statuts: StatutPartenaire[];
  pagination?: PaginationResult | undefined;
}

export interface DeleteStatutPartenaireRequest {
  id: string;
}

export interface PartenaireMarqueBlanche {
  id: string;
  denomination: string;
  siren: string;
  numeroTva: string;
  contactSupportEmail: string;
  telephone: string;
  statutId: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreatePartenaireRequest {
  denomination: string;
  siren: string;
  numeroTva: string;
  contactSupportEmail: string;
  telephone: string;
  statutId: string;
}

export interface UpdatePartenaireRequest {
  id: string;
  denomination: string;
  siren: string;
  numeroTva: string;
  contactSupportEmail: string;
  telephone: string;
  statutId: string;
}

export interface GetPartenaireRequest {
  id: string;
}

export interface ListPartenaireRequest {
  search: string;
  statutId: string;
  pagination?: Pagination | undefined;
}

export interface ListPartenaireResponse {
  partenaires: PartenaireMarqueBlanche[];
  pagination?: PaginationResult | undefined;
}

export interface DeletePartenaireRequest {
  id: string;
}

export interface ThemeMarque {
  id: string;
  logoUrl: string;
  couleurPrimaire: string;
  couleurSecondaire: string;
  faviconUrl: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateThemeMarqueRequest {
  logoUrl: string;
  couleurPrimaire: string;
  couleurSecondaire: string;
  faviconUrl: string;
}

export interface UpdateThemeMarqueRequest {
  id: string;
  logoUrl: string;
  couleurPrimaire: string;
  couleurSecondaire: string;
  faviconUrl: string;
}

export interface GetThemeMarqueRequest {
  id: string;
}

export interface ListThemeMarqueRequest {
  pagination?: Pagination | undefined;
}

export interface ListThemeMarqueResponse {
  themes: ThemeMarque[];
  pagination?: PaginationResult | undefined;
}

export interface DeleteThemeMarqueRequest {
  id: string;
}

export interface RolePartenaire {
  id: string;
  code: string;
  nom: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateRolePartenaireRequest {
  code: string;
  nom: string;
  description: string;
}

export interface UpdateRolePartenaireRequest {
  id: string;
  code: string;
  nom: string;
  description: string;
}

export interface GetRolePartenaireRequest {
  id: string;
}

export interface GetRolePartenaireByCodeRequest {
  code: string;
}

export interface ListRolePartenaireRequest {
  pagination?: Pagination | undefined;
}

export interface ListRolePartenaireResponse {
  roles: RolePartenaire[];
  pagination?: PaginationResult | undefined;
}

export interface DeleteRolePartenaireRequest {
  id: string;
}

export interface MembrePartenaire {
  id: string;
  utilisateurId: string;
  partenaireId: string;
  roleId: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateMembrePartenaireRequest {
  utilisateurId: string;
  partenaireId: string;
  roleId: string;
}

export interface UpdateMembrePartenaireRequest {
  id: string;
  roleId: string;
}

export interface GetMembrePartenaireRequest {
  id: string;
}

export interface ListMembreByPartenaireRequest {
  partenaireId: string;
  pagination?: Pagination | undefined;
}

export interface ListMembreByUtilisateurRequest {
  utilisateurId: string;
  pagination?: Pagination | undefined;
}

export interface ListMembrePartenaireResponse {
  membres: MembrePartenaire[];
  pagination?: PaginationResult | undefined;
}

export interface DeleteMembrePartenaireRequest {
  id: string;
}

export interface InvitationCompte {
  id: string;
  organisationId: string;
  emailInvite: string;
  roleId: string;
  token: string;
  expireAt: string;
  etat: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateInvitationCompteRequest {
  organisationId: string;
  emailInvite: string;
  roleId: string;
  expireAt: string;
}

export interface UpdateInvitationCompteRequest {
  id: string;
  etat: string;
}

export interface GetInvitationCompteRequest {
  id: string;
}

export interface GetInvitationByTokenRequest {
  token: string;
}

export interface ListInvitationByOrganisationRequest {
  organisationId: string;
  pagination?: Pagination | undefined;
}

export interface ListPendingByEmailRequest {
  email: string;
}

export interface ListInvitationCompteResponse {
  invitations: InvitationCompte[];
  pagination?: PaginationResult | undefined;
}

export interface AcceptInvitationRequest {
  id: string;
}

export interface RejectInvitationRequest {
  id: string;
}

export interface ExpireInvitationRequest {
  id: string;
}

export interface DeleteInvitationCompteRequest {
  id: string;
}

/** ========== COMMON MESSAGES ========== */
export interface Pagination {
  page: number;
  limit: number;
  sortBy: string;
  sortOrder: string;
}

export interface PaginationResult {
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface DeleteResponse {
  success: boolean;
}
